/*
runZero API

Testing SplunkAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package runzero

import (
	"context"
	"testing"

	openapiclient "github.com/runZeroInc/runzero-api/go"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_runzero_SplunkAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SplunkAPIService SplunkAssetSyncCreatedJSON", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.SplunkAPI.SplunkAssetSyncCreatedJSON(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SplunkAPIService SplunkAssetSyncUpdatedJSON", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.SplunkAPI.SplunkAssetSyncUpdatedJSON(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
