/*
runZero API

runZero API. API use is rate limited, you can make as many calls per day as you have licensed assets.

API version: 4.0.250826.0
Contact: support@runzero.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// WirelessExportResponse - Response body for the wireless export endpoint. Bare array unless `page_size` is provided.
type WirelessExportResponse struct {
	WirelessPage *WirelessPage
	ArrayOfWireless *[]Wireless
}

// WirelessPageAsWirelessExportResponse is a convenience function that returns WirelessPage wrapped in WirelessExportResponse
func WirelessPageAsWirelessExportResponse(v *WirelessPage) WirelessExportResponse {
	return WirelessExportResponse{
		WirelessPage: v,
	}
}

// []WirelessAsWirelessExportResponse is a convenience function that returns []Wireless wrapped in WirelessExportResponse
func ArrayOfWirelessAsWirelessExportResponse(v *[]Wireless) WirelessExportResponse {
	return WirelessExportResponse{
		ArrayOfWireless: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *WirelessExportResponse) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into WirelessPage
	err = newStrictDecoder(data).Decode(&dst.WirelessPage)
	if err == nil {
		jsonWirelessPage, _ := json.Marshal(dst.WirelessPage)
		if string(jsonWirelessPage) == "{}" { // empty struct
			dst.WirelessPage = nil
		} else {
			if err = validator.Validate(dst.WirelessPage); err != nil {
				dst.WirelessPage = nil
			} else {
				match++
			}
		}
	} else {
		dst.WirelessPage = nil
	}

	// try to unmarshal data into ArrayOfWireless
	err = newStrictDecoder(data).Decode(&dst.ArrayOfWireless)
	if err == nil {
		jsonArrayOfWireless, _ := json.Marshal(dst.ArrayOfWireless)
		if string(jsonArrayOfWireless) == "{}" { // empty struct
			dst.ArrayOfWireless = nil
		} else {
			if err = validator.Validate(dst.ArrayOfWireless); err != nil {
				dst.ArrayOfWireless = nil
			} else {
				match++
			}
		}
	} else {
		dst.ArrayOfWireless = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.WirelessPage = nil
		dst.ArrayOfWireless = nil

		return fmt.Errorf("data matches more than one schema in oneOf(WirelessExportResponse)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(WirelessExportResponse)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src WirelessExportResponse) MarshalJSON() ([]byte, error) {
	if src.WirelessPage != nil {
		return json.Marshal(&src.WirelessPage)
	}

	if src.ArrayOfWireless != nil {
		return json.Marshal(&src.ArrayOfWireless)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *WirelessExportResponse) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.WirelessPage != nil {
		return obj.WirelessPage
	}

	if obj.ArrayOfWireless != nil {
		return obj.ArrayOfWireless
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj WirelessExportResponse) GetActualInstanceValue() (interface{}) {
	if obj.WirelessPage != nil {
		return *obj.WirelessPage
	}

	if obj.ArrayOfWireless != nil {
		return *obj.ArrayOfWireless
	}

	// all schemas are nil
	return nil
}

type NullableWirelessExportResponse struct {
	value *WirelessExportResponse
	isSet bool
}

func (v NullableWirelessExportResponse) Get() *WirelessExportResponse {
	return v.value
}

func (v *NullableWirelessExportResponse) Set(val *WirelessExportResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableWirelessExportResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableWirelessExportResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWirelessExportResponse(val *WirelessExportResponse) *NullableWirelessExportResponse {
	return &NullableWirelessExportResponse{value: val, isSet: true}
}

func (v NullableWirelessExportResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWirelessExportResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


