/*
runZero API

runZero API. API use is rate limited, you can make as many calls per day as you have licensed assets.

API version: 4.0.250826.0
Contact: support@runzero.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package runzero

import (
	"encoding/json"
)

// checks if the FindingLinksCvesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FindingLinksCvesInner{}

// FindingLinksCvesInner struct for FindingLinksCvesInner
type FindingLinksCvesInner struct {
	Title *string `json:"title,omitempty"`
	Url   *string `json:"url,omitempty"`
}

// NewFindingLinksCvesInner instantiates a new FindingLinksCvesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFindingLinksCvesInner() *FindingLinksCvesInner {
	this := FindingLinksCvesInner{}
	return &this
}

// NewFindingLinksCvesInnerWithDefaults instantiates a new FindingLinksCvesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFindingLinksCvesInnerWithDefaults() *FindingLinksCvesInner {
	this := FindingLinksCvesInner{}
	return &this
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *FindingLinksCvesInner) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindingLinksCvesInner) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *FindingLinksCvesInner) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *FindingLinksCvesInner) SetTitle(v string) {
	o.Title = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *FindingLinksCvesInner) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindingLinksCvesInner) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *FindingLinksCvesInner) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *FindingLinksCvesInner) SetUrl(v string) {
	o.Url = &v
}

func (o FindingLinksCvesInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FindingLinksCvesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	return toSerialize, nil
}

type NullableFindingLinksCvesInner struct {
	value *FindingLinksCvesInner
	isSet bool
}

func (v NullableFindingLinksCvesInner) Get() *FindingLinksCvesInner {
	return v.value
}

func (v *NullableFindingLinksCvesInner) Set(val *FindingLinksCvesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableFindingLinksCvesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableFindingLinksCvesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFindingLinksCvesInner(val *FindingLinksCvesInner) *NullableFindingLinksCvesInner {
	return &NullableFindingLinksCvesInner{value: val, isSet: true}
}

func (v NullableFindingLinksCvesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFindingLinksCvesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
