/*
runZero API

runZero API. API use is rate limited, you can make as many calls per day as you have licensed assets.

API version: 4.0.250826.0
Contact: support@runzero.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package runzero

import (
	"encoding/json"
)

// checks if the GroupPut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupPut{}

// GroupPut struct for GroupPut
type GroupPut struct {
	Id             *string                `json:"id,omitempty"`
	Description    *string                `json:"description,omitempty"`
	Name           *string                `json:"name,omitempty"`
	ExpiresAt      *int64                 `json:"expires_at,omitempty"`
	OrgDefaultRole *string                `json:"org_default_role,omitempty"`
	OrgRoles       map[string]interface{} `json:"org_roles,omitempty"`
}

// NewGroupPut instantiates a new GroupPut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupPut() *GroupPut {
	this := GroupPut{}
	return &this
}

// NewGroupPutWithDefaults instantiates a new GroupPut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupPutWithDefaults() *GroupPut {
	this := GroupPut{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GroupPut) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupPut) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GroupPut) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *GroupPut) SetId(v string) {
	o.Id = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *GroupPut) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupPut) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *GroupPut) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *GroupPut) SetDescription(v string) {
	o.Description = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GroupPut) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupPut) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GroupPut) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GroupPut) SetName(v string) {
	o.Name = &v
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise.
func (o *GroupPut) GetExpiresAt() int64 {
	if o == nil || IsNil(o.ExpiresAt) {
		var ret int64
		return ret
	}
	return *o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupPut) GetExpiresAtOk() (*int64, bool) {
	if o == nil || IsNil(o.ExpiresAt) {
		return nil, false
	}
	return o.ExpiresAt, true
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *GroupPut) HasExpiresAt() bool {
	if o != nil && !IsNil(o.ExpiresAt) {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given int64 and assigns it to the ExpiresAt field.
func (o *GroupPut) SetExpiresAt(v int64) {
	o.ExpiresAt = &v
}

// GetOrgDefaultRole returns the OrgDefaultRole field value if set, zero value otherwise.
func (o *GroupPut) GetOrgDefaultRole() string {
	if o == nil || IsNil(o.OrgDefaultRole) {
		var ret string
		return ret
	}
	return *o.OrgDefaultRole
}

// GetOrgDefaultRoleOk returns a tuple with the OrgDefaultRole field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupPut) GetOrgDefaultRoleOk() (*string, bool) {
	if o == nil || IsNil(o.OrgDefaultRole) {
		return nil, false
	}
	return o.OrgDefaultRole, true
}

// HasOrgDefaultRole returns a boolean if a field has been set.
func (o *GroupPut) HasOrgDefaultRole() bool {
	if o != nil && !IsNil(o.OrgDefaultRole) {
		return true
	}

	return false
}

// SetOrgDefaultRole gets a reference to the given string and assigns it to the OrgDefaultRole field.
func (o *GroupPut) SetOrgDefaultRole(v string) {
	o.OrgDefaultRole = &v
}

// GetOrgRoles returns the OrgRoles field value if set, zero value otherwise.
func (o *GroupPut) GetOrgRoles() map[string]interface{} {
	if o == nil || IsNil(o.OrgRoles) {
		var ret map[string]interface{}
		return ret
	}
	return o.OrgRoles
}

// GetOrgRolesOk returns a tuple with the OrgRoles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupPut) GetOrgRolesOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.OrgRoles) {
		return map[string]interface{}{}, false
	}
	return o.OrgRoles, true
}

// HasOrgRoles returns a boolean if a field has been set.
func (o *GroupPut) HasOrgRoles() bool {
	if o != nil && !IsNil(o.OrgRoles) {
		return true
	}

	return false
}

// SetOrgRoles gets a reference to the given map[string]interface{} and assigns it to the OrgRoles field.
func (o *GroupPut) SetOrgRoles(v map[string]interface{}) {
	o.OrgRoles = v
}

func (o GroupPut) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupPut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.ExpiresAt) {
		toSerialize["expires_at"] = o.ExpiresAt
	}
	if !IsNil(o.OrgDefaultRole) {
		toSerialize["org_default_role"] = o.OrgDefaultRole
	}
	if !IsNil(o.OrgRoles) {
		toSerialize["org_roles"] = o.OrgRoles
	}
	return toSerialize, nil
}

type NullableGroupPut struct {
	value *GroupPut
	isSet bool
}

func (v NullableGroupPut) Get() *GroupPut {
	return v.value
}

func (v *NullableGroupPut) Set(val *GroupPut) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupPut) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupPut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupPut(val *GroupPut) *NullableGroupPut {
	return &NullableGroupPut{value: val, isSet: true}
}

func (v NullableGroupPut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupPut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
