/*
runZero API

runZero API. API use is rate limited, you can make as many calls per day as you have licensed assets.

API version: 4.0.250826.0
Contact: support@runzero.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the EventPage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EventPage{}

// EventPage A page of events returned from a paginated export.
type EventPage struct {
	Events []Event `json:"events,omitempty"`
	// The key to use for the next page of results
	NextKey *string `json:"next_key,omitempty"`
}

// NewEventPage instantiates a new EventPage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEventPage() *EventPage {
	this := EventPage{}
	return &this
}

// NewEventPageWithDefaults instantiates a new EventPage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventPageWithDefaults() *EventPage {
	this := EventPage{}
	return &this
}

// GetEvents returns the Events field value if set, zero value otherwise.
func (o *EventPage) GetEvents() []Event {
	if o == nil || IsNil(o.Events) {
		var ret []Event
		return ret
	}
	return o.Events
}

// GetEventsOk returns a tuple with the Events field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventPage) GetEventsOk() ([]Event, bool) {
	if o == nil || IsNil(o.Events) {
		return nil, false
	}
	return o.Events, true
}

// HasEvents returns a boolean if a field has been set.
func (o *EventPage) HasEvents() bool {
	if o != nil && !IsNil(o.Events) {
		return true
	}

	return false
}

// SetEvents gets a reference to the given []Event and assigns it to the Events field.
func (o *EventPage) SetEvents(v []Event) {
	o.Events = v
}

// GetNextKey returns the NextKey field value if set, zero value otherwise.
func (o *EventPage) GetNextKey() string {
	if o == nil || IsNil(o.NextKey) {
		var ret string
		return ret
	}
	return *o.NextKey
}

// GetNextKeyOk returns a tuple with the NextKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventPage) GetNextKeyOk() (*string, bool) {
	if o == nil || IsNil(o.NextKey) {
		return nil, false
	}
	return o.NextKey, true
}

// HasNextKey returns a boolean if a field has been set.
func (o *EventPage) HasNextKey() bool {
	if o != nil && !IsNil(o.NextKey) {
		return true
	}

	return false
}

// SetNextKey gets a reference to the given string and assigns it to the NextKey field.
func (o *EventPage) SetNextKey(v string) {
	o.NextKey = &v
}

func (o EventPage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EventPage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Events) {
		toSerialize["events"] = o.Events
	}
	if !IsNil(o.NextKey) {
		toSerialize["next_key"] = o.NextKey
	}
	return toSerialize, nil
}

type NullableEventPage struct {
	value *EventPage
	isSet bool
}

func (v NullableEventPage) Get() *EventPage {
	return v.value
}

func (v *NullableEventPage) Set(val *EventPage) {
	v.value = val
	v.isSet = true
}

func (v NullableEventPage) IsSet() bool {
	return v.isSet
}

func (v *NullableEventPage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventPage(val *EventPage) *NullableEventPage {
	return &NullableEventPage{value: val, isSet: true}
}

func (v NullableEventPage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventPage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


