/*
runZero API

runZero API. API use is rate limited, you can make as many calls per day as you have licensed assets.

API version: 4.0.250826.0
Contact: support@runzero.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package runzero

import (
	"encoding/json"
)

// checks if the AssetOwnerships type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssetOwnerships{}

// AssetOwnerships struct for AssetOwnerships
type AssetOwnerships struct {
	Ownerships []AssetOwnershipsOwnershipsInner `json:"ownerships,omitempty"`
}

// NewAssetOwnerships instantiates a new AssetOwnerships object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssetOwnerships() *AssetOwnerships {
	this := AssetOwnerships{}
	return &this
}

// NewAssetOwnershipsWithDefaults instantiates a new AssetOwnerships object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssetOwnershipsWithDefaults() *AssetOwnerships {
	this := AssetOwnerships{}
	return &this
}

// GetOwnerships returns the Ownerships field value if set, zero value otherwise.
func (o *AssetOwnerships) GetOwnerships() []AssetOwnershipsOwnershipsInner {
	if o == nil || IsNil(o.Ownerships) {
		var ret []AssetOwnershipsOwnershipsInner
		return ret
	}
	return o.Ownerships
}

// GetOwnershipsOk returns a tuple with the Ownerships field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetOwnerships) GetOwnershipsOk() ([]AssetOwnershipsOwnershipsInner, bool) {
	if o == nil || IsNil(o.Ownerships) {
		return nil, false
	}
	return o.Ownerships, true
}

// HasOwnerships returns a boolean if a field has been set.
func (o *AssetOwnerships) HasOwnerships() bool {
	if o != nil && !IsNil(o.Ownerships) {
		return true
	}

	return false
}

// SetOwnerships gets a reference to the given []AssetOwnershipsOwnershipsInner and assigns it to the Ownerships field.
func (o *AssetOwnerships) SetOwnerships(v []AssetOwnershipsOwnershipsInner) {
	o.Ownerships = v
}

func (o AssetOwnerships) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssetOwnerships) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Ownerships) {
		toSerialize["ownerships"] = o.Ownerships
	}
	return toSerialize, nil
}

type NullableAssetOwnerships struct {
	value *AssetOwnerships
	isSet bool
}

func (v NullableAssetOwnerships) Get() *AssetOwnerships {
	return v.value
}

func (v *NullableAssetOwnerships) Set(val *AssetOwnerships) {
	v.value = val
	v.isSet = true
}

func (v NullableAssetOwnerships) IsSet() bool {
	return v.isSet
}

func (v *NullableAssetOwnerships) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssetOwnerships(val *AssetOwnerships) *NullableAssetOwnerships {
	return &NullableAssetOwnerships{value: val, isSet: true}
}

func (v NullableAssetOwnerships) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssetOwnerships) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
