/*
runZero API

runZero API. API use is rate limited, you can make as many calls per day as you have licensed assets.

API version: 4.0.250826.0
Contact: support@runzero.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package runzero

import (
	"encoding/json"
)

// checks if the AssetOwnershipsOwnershipsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssetOwnershipsOwnershipsInner{}

// AssetOwnershipsOwnershipsInner struct for AssetOwnershipsOwnershipsInner
type AssetOwnershipsOwnershipsInner struct {
	OwnershipTypeId *string `json:"ownership_type_id,omitempty"`
	Owner           *string `json:"owner,omitempty"`
}

// NewAssetOwnershipsOwnershipsInner instantiates a new AssetOwnershipsOwnershipsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssetOwnershipsOwnershipsInner() *AssetOwnershipsOwnershipsInner {
	this := AssetOwnershipsOwnershipsInner{}
	return &this
}

// NewAssetOwnershipsOwnershipsInnerWithDefaults instantiates a new AssetOwnershipsOwnershipsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssetOwnershipsOwnershipsInnerWithDefaults() *AssetOwnershipsOwnershipsInner {
	this := AssetOwnershipsOwnershipsInner{}
	return &this
}

// GetOwnershipTypeId returns the OwnershipTypeId field value if set, zero value otherwise.
func (o *AssetOwnershipsOwnershipsInner) GetOwnershipTypeId() string {
	if o == nil || IsNil(o.OwnershipTypeId) {
		var ret string
		return ret
	}
	return *o.OwnershipTypeId
}

// GetOwnershipTypeIdOk returns a tuple with the OwnershipTypeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetOwnershipsOwnershipsInner) GetOwnershipTypeIdOk() (*string, bool) {
	if o == nil || IsNil(o.OwnershipTypeId) {
		return nil, false
	}
	return o.OwnershipTypeId, true
}

// HasOwnershipTypeId returns a boolean if a field has been set.
func (o *AssetOwnershipsOwnershipsInner) HasOwnershipTypeId() bool {
	if o != nil && !IsNil(o.OwnershipTypeId) {
		return true
	}

	return false
}

// SetOwnershipTypeId gets a reference to the given string and assigns it to the OwnershipTypeId field.
func (o *AssetOwnershipsOwnershipsInner) SetOwnershipTypeId(v string) {
	o.OwnershipTypeId = &v
}

// GetOwner returns the Owner field value if set, zero value otherwise.
func (o *AssetOwnershipsOwnershipsInner) GetOwner() string {
	if o == nil || IsNil(o.Owner) {
		var ret string
		return ret
	}
	return *o.Owner
}

// GetOwnerOk returns a tuple with the Owner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetOwnershipsOwnershipsInner) GetOwnerOk() (*string, bool) {
	if o == nil || IsNil(o.Owner) {
		return nil, false
	}
	return o.Owner, true
}

// HasOwner returns a boolean if a field has been set.
func (o *AssetOwnershipsOwnershipsInner) HasOwner() bool {
	if o != nil && !IsNil(o.Owner) {
		return true
	}

	return false
}

// SetOwner gets a reference to the given string and assigns it to the Owner field.
func (o *AssetOwnershipsOwnershipsInner) SetOwner(v string) {
	o.Owner = &v
}

func (o AssetOwnershipsOwnershipsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssetOwnershipsOwnershipsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.OwnershipTypeId) {
		toSerialize["ownership_type_id"] = o.OwnershipTypeId
	}
	if !IsNil(o.Owner) {
		toSerialize["owner"] = o.Owner
	}
	return toSerialize, nil
}

type NullableAssetOwnershipsOwnershipsInner struct {
	value *AssetOwnershipsOwnershipsInner
	isSet bool
}

func (v NullableAssetOwnershipsOwnershipsInner) Get() *AssetOwnershipsOwnershipsInner {
	return v.value
}

func (v *NullableAssetOwnershipsOwnershipsInner) Set(val *AssetOwnershipsOwnershipsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableAssetOwnershipsOwnershipsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableAssetOwnershipsOwnershipsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssetOwnershipsOwnershipsInner(val *AssetOwnershipsOwnershipsInner) *NullableAssetOwnershipsOwnershipsInner {
	return &NullableAssetOwnershipsOwnershipsInner{value: val, isSet: true}
}

func (v NullableAssetOwnershipsOwnershipsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssetOwnershipsOwnershipsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
