/*
runZero API

runZero API. API use is rate limited, you can make as many calls per day as you have licensed assets.

API version: 4.0.250826.0
Contact: support@runzero.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package runzero

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the AssetComments type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssetComments{}

// AssetComments struct for AssetComments
type AssetComments struct {
	Comments string `json:"comments"`
}

type _AssetComments AssetComments

// NewAssetComments instantiates a new AssetComments object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssetComments(comments string) *AssetComments {
	this := AssetComments{}
	this.Comments = comments
	return &this
}

// NewAssetCommentsWithDefaults instantiates a new AssetComments object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssetCommentsWithDefaults() *AssetComments {
	this := AssetComments{}
	return &this
}

// GetComments returns the Comments field value
func (o *AssetComments) GetComments() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Comments
}

// GetCommentsOk returns a tuple with the Comments field value
// and a boolean to check if the value has been set.
func (o *AssetComments) GetCommentsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Comments, true
}

// SetComments sets field value
func (o *AssetComments) SetComments(v string) {
	o.Comments = v
}

func (o AssetComments) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssetComments) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["comments"] = o.Comments
	return toSerialize, nil
}

func (o *AssetComments) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"comments",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAssetComments := _AssetComments{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAssetComments)

	if err != nil {
		return err
	}

	*o = AssetComments(varAssetComments)

	return err
}

type NullableAssetComments struct {
	value *AssetComments
	isSet bool
}

func (v NullableAssetComments) Get() *AssetComments {
	return v.value
}

func (v *NullableAssetComments) Set(val *AssetComments) {
	v.value = val
	v.isSet = true
}

func (v NullableAssetComments) IsSet() bool {
	return v.isSet
}

func (v *NullableAssetComments) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssetComments(val *AssetComments) *NullableAssetComments {
	return &NullableAssetComments{value: val, isSet: true}
}

func (v NullableAssetComments) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssetComments) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
