/*
runZero API

runZero API. API use is rate limited, you can make as many calls per day as you have licensed assets.

API version: 4.0.250826.0
Contact: support@runzero.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package runzero

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the X509CredentialFields type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &X509CredentialFields{}

// X509CredentialFields struct for X509CredentialFields
type X509CredentialFields struct {
	X509Certificate string `json:"x509_certificate"`
	PrivateKey      string `json:"private_key"`
}

type _X509CredentialFields X509CredentialFields

// NewX509CredentialFields instantiates a new X509CredentialFields object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewX509CredentialFields(x509Certificate string, privateKey string) *X509CredentialFields {
	this := X509CredentialFields{}
	this.X509Certificate = x509Certificate
	this.PrivateKey = privateKey
	return &this
}

// NewX509CredentialFieldsWithDefaults instantiates a new X509CredentialFields object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewX509CredentialFieldsWithDefaults() *X509CredentialFields {
	this := X509CredentialFields{}
	return &this
}

// GetX509Certificate returns the X509Certificate field value
func (o *X509CredentialFields) GetX509Certificate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.X509Certificate
}

// GetX509CertificateOk returns a tuple with the X509Certificate field value
// and a boolean to check if the value has been set.
func (o *X509CredentialFields) GetX509CertificateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.X509Certificate, true
}

// SetX509Certificate sets field value
func (o *X509CredentialFields) SetX509Certificate(v string) {
	o.X509Certificate = v
}

// GetPrivateKey returns the PrivateKey field value
func (o *X509CredentialFields) GetPrivateKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PrivateKey
}

// GetPrivateKeyOk returns a tuple with the PrivateKey field value
// and a boolean to check if the value has been set.
func (o *X509CredentialFields) GetPrivateKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PrivateKey, true
}

// SetPrivateKey sets field value
func (o *X509CredentialFields) SetPrivateKey(v string) {
	o.PrivateKey = v
}

func (o X509CredentialFields) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o X509CredentialFields) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["x509_certificate"] = o.X509Certificate
	toSerialize["private_key"] = o.PrivateKey
	return toSerialize, nil
}

func (o *X509CredentialFields) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"x509_certificate",
		"private_key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varX509CredentialFields := _X509CredentialFields{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varX509CredentialFields)

	if err != nil {
		return err
	}

	*o = X509CredentialFields(varX509CredentialFields)

	return err
}

type NullableX509CredentialFields struct {
	value *X509CredentialFields
	isSet bool
}

func (v NullableX509CredentialFields) Get() *X509CredentialFields {
	return v.value
}

func (v *NullableX509CredentialFields) Set(val *X509CredentialFields) {
	v.value = val
	v.isSet = true
}

func (v NullableX509CredentialFields) IsSet() bool {
	return v.isSet
}

func (v *NullableX509CredentialFields) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableX509CredentialFields(val *X509CredentialFields) *NullableX509CredentialFields {
	return &NullableX509CredentialFields{value: val, isSet: true}
}

func (v NullableX509CredentialFields) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableX509CredentialFields) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
