/*
runZero API

runZero API. API use is rate limited, you can make as many calls per day as you have licensed assets.

API version: 4.0.250826.0
Contact: support@runzero.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package runzero

import (
	"encoding/json"
)

// checks if the OrgOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrgOptions{}

// OrgOptions struct for OrgOptions
type OrgOptions struct {
	Name                            *string  `json:"name,omitempty"`
	Description                     *string  `json:"description,omitempty"`
	ParentId                        *string  `json:"parent_id,omitempty"`
	ExpirationAssetsStale           *float64 `json:"expiration_assets_stale,omitempty"`
	ExpirationAssetsOffline         *float64 `json:"expiration_assets_offline,omitempty"`
	ExpirationIntegrationAttributes *float64 `json:"expiration_integration_attributes,omitempty"`
	ExpirationScans                 *float64 `json:"expiration_scans,omitempty"`
	ExpirationVulnerabilities       *float64 `json:"expiration_vulnerabilities,omitempty"`
	KeepLatestIntegrationAttributes *string  `json:"keep_latest_integration_attributes,omitempty"`
}

// NewOrgOptions instantiates a new OrgOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrgOptions() *OrgOptions {
	this := OrgOptions{}
	return &this
}

// NewOrgOptionsWithDefaults instantiates a new OrgOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrgOptionsWithDefaults() *OrgOptions {
	this := OrgOptions{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *OrgOptions) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrgOptions) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *OrgOptions) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *OrgOptions) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *OrgOptions) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrgOptions) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *OrgOptions) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *OrgOptions) SetDescription(v string) {
	o.Description = &v
}

// GetParentId returns the ParentId field value if set, zero value otherwise.
func (o *OrgOptions) GetParentId() string {
	if o == nil || IsNil(o.ParentId) {
		var ret string
		return ret
	}
	return *o.ParentId
}

// GetParentIdOk returns a tuple with the ParentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrgOptions) GetParentIdOk() (*string, bool) {
	if o == nil || IsNil(o.ParentId) {
		return nil, false
	}
	return o.ParentId, true
}

// HasParentId returns a boolean if a field has been set.
func (o *OrgOptions) HasParentId() bool {
	if o != nil && !IsNil(o.ParentId) {
		return true
	}

	return false
}

// SetParentId gets a reference to the given string and assigns it to the ParentId field.
func (o *OrgOptions) SetParentId(v string) {
	o.ParentId = &v
}

// GetExpirationAssetsStale returns the ExpirationAssetsStale field value if set, zero value otherwise.
func (o *OrgOptions) GetExpirationAssetsStale() float64 {
	if o == nil || IsNil(o.ExpirationAssetsStale) {
		var ret float64
		return ret
	}
	return *o.ExpirationAssetsStale
}

// GetExpirationAssetsStaleOk returns a tuple with the ExpirationAssetsStale field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrgOptions) GetExpirationAssetsStaleOk() (*float64, bool) {
	if o == nil || IsNil(o.ExpirationAssetsStale) {
		return nil, false
	}
	return o.ExpirationAssetsStale, true
}

// HasExpirationAssetsStale returns a boolean if a field has been set.
func (o *OrgOptions) HasExpirationAssetsStale() bool {
	if o != nil && !IsNil(o.ExpirationAssetsStale) {
		return true
	}

	return false
}

// SetExpirationAssetsStale gets a reference to the given float64 and assigns it to the ExpirationAssetsStale field.
func (o *OrgOptions) SetExpirationAssetsStale(v float64) {
	o.ExpirationAssetsStale = &v
}

// GetExpirationAssetsOffline returns the ExpirationAssetsOffline field value if set, zero value otherwise.
func (o *OrgOptions) GetExpirationAssetsOffline() float64 {
	if o == nil || IsNil(o.ExpirationAssetsOffline) {
		var ret float64
		return ret
	}
	return *o.ExpirationAssetsOffline
}

// GetExpirationAssetsOfflineOk returns a tuple with the ExpirationAssetsOffline field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrgOptions) GetExpirationAssetsOfflineOk() (*float64, bool) {
	if o == nil || IsNil(o.ExpirationAssetsOffline) {
		return nil, false
	}
	return o.ExpirationAssetsOffline, true
}

// HasExpirationAssetsOffline returns a boolean if a field has been set.
func (o *OrgOptions) HasExpirationAssetsOffline() bool {
	if o != nil && !IsNil(o.ExpirationAssetsOffline) {
		return true
	}

	return false
}

// SetExpirationAssetsOffline gets a reference to the given float64 and assigns it to the ExpirationAssetsOffline field.
func (o *OrgOptions) SetExpirationAssetsOffline(v float64) {
	o.ExpirationAssetsOffline = &v
}

// GetExpirationIntegrationAttributes returns the ExpirationIntegrationAttributes field value if set, zero value otherwise.
func (o *OrgOptions) GetExpirationIntegrationAttributes() float64 {
	if o == nil || IsNil(o.ExpirationIntegrationAttributes) {
		var ret float64
		return ret
	}
	return *o.ExpirationIntegrationAttributes
}

// GetExpirationIntegrationAttributesOk returns a tuple with the ExpirationIntegrationAttributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrgOptions) GetExpirationIntegrationAttributesOk() (*float64, bool) {
	if o == nil || IsNil(o.ExpirationIntegrationAttributes) {
		return nil, false
	}
	return o.ExpirationIntegrationAttributes, true
}

// HasExpirationIntegrationAttributes returns a boolean if a field has been set.
func (o *OrgOptions) HasExpirationIntegrationAttributes() bool {
	if o != nil && !IsNil(o.ExpirationIntegrationAttributes) {
		return true
	}

	return false
}

// SetExpirationIntegrationAttributes gets a reference to the given float64 and assigns it to the ExpirationIntegrationAttributes field.
func (o *OrgOptions) SetExpirationIntegrationAttributes(v float64) {
	o.ExpirationIntegrationAttributes = &v
}

// GetExpirationScans returns the ExpirationScans field value if set, zero value otherwise.
func (o *OrgOptions) GetExpirationScans() float64 {
	if o == nil || IsNil(o.ExpirationScans) {
		var ret float64
		return ret
	}
	return *o.ExpirationScans
}

// GetExpirationScansOk returns a tuple with the ExpirationScans field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrgOptions) GetExpirationScansOk() (*float64, bool) {
	if o == nil || IsNil(o.ExpirationScans) {
		return nil, false
	}
	return o.ExpirationScans, true
}

// HasExpirationScans returns a boolean if a field has been set.
func (o *OrgOptions) HasExpirationScans() bool {
	if o != nil && !IsNil(o.ExpirationScans) {
		return true
	}

	return false
}

// SetExpirationScans gets a reference to the given float64 and assigns it to the ExpirationScans field.
func (o *OrgOptions) SetExpirationScans(v float64) {
	o.ExpirationScans = &v
}

// GetExpirationVulnerabilities returns the ExpirationVulnerabilities field value if set, zero value otherwise.
func (o *OrgOptions) GetExpirationVulnerabilities() float64 {
	if o == nil || IsNil(o.ExpirationVulnerabilities) {
		var ret float64
		return ret
	}
	return *o.ExpirationVulnerabilities
}

// GetExpirationVulnerabilitiesOk returns a tuple with the ExpirationVulnerabilities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrgOptions) GetExpirationVulnerabilitiesOk() (*float64, bool) {
	if o == nil || IsNil(o.ExpirationVulnerabilities) {
		return nil, false
	}
	return o.ExpirationVulnerabilities, true
}

// HasExpirationVulnerabilities returns a boolean if a field has been set.
func (o *OrgOptions) HasExpirationVulnerabilities() bool {
	if o != nil && !IsNil(o.ExpirationVulnerabilities) {
		return true
	}

	return false
}

// SetExpirationVulnerabilities gets a reference to the given float64 and assigns it to the ExpirationVulnerabilities field.
func (o *OrgOptions) SetExpirationVulnerabilities(v float64) {
	o.ExpirationVulnerabilities = &v
}

// GetKeepLatestIntegrationAttributes returns the KeepLatestIntegrationAttributes field value if set, zero value otherwise.
func (o *OrgOptions) GetKeepLatestIntegrationAttributes() string {
	if o == nil || IsNil(o.KeepLatestIntegrationAttributes) {
		var ret string
		return ret
	}
	return *o.KeepLatestIntegrationAttributes
}

// GetKeepLatestIntegrationAttributesOk returns a tuple with the KeepLatestIntegrationAttributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrgOptions) GetKeepLatestIntegrationAttributesOk() (*string, bool) {
	if o == nil || IsNil(o.KeepLatestIntegrationAttributes) {
		return nil, false
	}
	return o.KeepLatestIntegrationAttributes, true
}

// HasKeepLatestIntegrationAttributes returns a boolean if a field has been set.
func (o *OrgOptions) HasKeepLatestIntegrationAttributes() bool {
	if o != nil && !IsNil(o.KeepLatestIntegrationAttributes) {
		return true
	}

	return false
}

// SetKeepLatestIntegrationAttributes gets a reference to the given string and assigns it to the KeepLatestIntegrationAttributes field.
func (o *OrgOptions) SetKeepLatestIntegrationAttributes(v string) {
	o.KeepLatestIntegrationAttributes = &v
}

func (o OrgOptions) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrgOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.ParentId) {
		toSerialize["parent_id"] = o.ParentId
	}
	if !IsNil(o.ExpirationAssetsStale) {
		toSerialize["expiration_assets_stale"] = o.ExpirationAssetsStale
	}
	if !IsNil(o.ExpirationAssetsOffline) {
		toSerialize["expiration_assets_offline"] = o.ExpirationAssetsOffline
	}
	if !IsNil(o.ExpirationIntegrationAttributes) {
		toSerialize["expiration_integration_attributes"] = o.ExpirationIntegrationAttributes
	}
	if !IsNil(o.ExpirationScans) {
		toSerialize["expiration_scans"] = o.ExpirationScans
	}
	if !IsNil(o.ExpirationVulnerabilities) {
		toSerialize["expiration_vulnerabilities"] = o.ExpirationVulnerabilities
	}
	if !IsNil(o.KeepLatestIntegrationAttributes) {
		toSerialize["keep_latest_integration_attributes"] = o.KeepLatestIntegrationAttributes
	}
	return toSerialize, nil
}

type NullableOrgOptions struct {
	value *OrgOptions
	isSet bool
}

func (v NullableOrgOptions) Get() *OrgOptions {
	return v.value
}

func (v *NullableOrgOptions) Set(val *OrgOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableOrgOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableOrgOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrgOptions(val *OrgOptions) *NullableOrgOptions {
	return &NullableOrgOptions{value: val, isSet: true}
}

func (v NullableOrgOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrgOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
