/*
runZero API

runZero API. API use is rate limited, you can make as many calls per day as you have licensed assets.

API version: 4.0.250826.0
Contact: support@runzero.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package runzero

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the User type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &User{}

// User struct for User
type User struct {
	Id                    string                 `json:"id"`
	ClientId              *string                `json:"client_id,omitempty"`
	CreatedAt             *int64                 `json:"created_at,omitempty"`
	UpdatedAt             *int64                 `json:"updated_at,omitempty"`
	Name                  *string                `json:"name,omitempty"`
	FirstName             *string                `json:"first_name,omitempty"`
	LastName              *string                `json:"last_name,omitempty"`
	Email                 *string                `json:"email,omitempty"`
	ClientAdmin           *bool                  `json:"client_admin,omitempty"`
	OrgDefaultRole        *string                `json:"org_default_role,omitempty"`
	OrgRoles              map[string]interface{} `json:"org_roles,omitempty"`
	PasswordEnabledAt     *int64                 `json:"password_enabled_at,omitempty"`
	InviteTokenExpiration *int64                 `json:"invite_token_expiration,omitempty"`
	ResetTokenExpiration  *int64                 `json:"reset_token_expiration,omitempty"`
	TermsAgreedAsOf       *int64                 `json:"terms_agreed_as_of,omitempty"`
	LastLoginIp           NullableString         `json:"last_login_ip,omitempty"`
	LastLoginAt           *int64                 `json:"last_login_at,omitempty"`
	LastLoginUa           *string                `json:"last_login_ua,omitempty"`
	LastActivityAt        *int64                 `json:"last_activity_at,omitempty"`
	SsoOnly               *bool                  `json:"sso_only,omitempty"`
	LoginFailures         *int64                 `json:"login_failures,omitempty"`
	Actions               *int64                 `json:"actions,omitempty"`
	LastActionAt          *int64                 `json:"last_action_at,omitempty"`
	MfaEnabled            *bool                  `json:"mfa_enabled,omitempty"`
}

type _User User

// NewUser instantiates a new User object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUser(id string) *User {
	this := User{}
	this.Id = id
	return &this
}

// NewUserWithDefaults instantiates a new User object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserWithDefaults() *User {
	this := User{}
	return &this
}

// GetId returns the Id field value
func (o *User) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *User) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *User) SetId(v string) {
	o.Id = v
}

// GetClientId returns the ClientId field value if set, zero value otherwise.
func (o *User) GetClientId() string {
	if o == nil || IsNil(o.ClientId) {
		var ret string
		return ret
	}
	return *o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetClientIdOk() (*string, bool) {
	if o == nil || IsNil(o.ClientId) {
		return nil, false
	}
	return o.ClientId, true
}

// HasClientId returns a boolean if a field has been set.
func (o *User) HasClientId() bool {
	if o != nil && !IsNil(o.ClientId) {
		return true
	}

	return false
}

// SetClientId gets a reference to the given string and assigns it to the ClientId field.
func (o *User) SetClientId(v string) {
	o.ClientId = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *User) GetCreatedAt() int64 {
	if o == nil || IsNil(o.CreatedAt) {
		var ret int64
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetCreatedAtOk() (*int64, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *User) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given int64 and assigns it to the CreatedAt field.
func (o *User) SetCreatedAt(v int64) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *User) GetUpdatedAt() int64 {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret int64
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetUpdatedAtOk() (*int64, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *User) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given int64 and assigns it to the UpdatedAt field.
func (o *User) SetUpdatedAt(v int64) {
	o.UpdatedAt = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *User) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *User) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *User) SetName(v string) {
	o.Name = &v
}

// GetFirstName returns the FirstName field value if set, zero value otherwise.
func (o *User) GetFirstName() string {
	if o == nil || IsNil(o.FirstName) {
		var ret string
		return ret
	}
	return *o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetFirstNameOk() (*string, bool) {
	if o == nil || IsNil(o.FirstName) {
		return nil, false
	}
	return o.FirstName, true
}

// HasFirstName returns a boolean if a field has been set.
func (o *User) HasFirstName() bool {
	if o != nil && !IsNil(o.FirstName) {
		return true
	}

	return false
}

// SetFirstName gets a reference to the given string and assigns it to the FirstName field.
func (o *User) SetFirstName(v string) {
	o.FirstName = &v
}

// GetLastName returns the LastName field value if set, zero value otherwise.
func (o *User) GetLastName() string {
	if o == nil || IsNil(o.LastName) {
		var ret string
		return ret
	}
	return *o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetLastNameOk() (*string, bool) {
	if o == nil || IsNil(o.LastName) {
		return nil, false
	}
	return o.LastName, true
}

// HasLastName returns a boolean if a field has been set.
func (o *User) HasLastName() bool {
	if o != nil && !IsNil(o.LastName) {
		return true
	}

	return false
}

// SetLastName gets a reference to the given string and assigns it to the LastName field.
func (o *User) SetLastName(v string) {
	o.LastName = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *User) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *User) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *User) SetEmail(v string) {
	o.Email = &v
}

// GetClientAdmin returns the ClientAdmin field value if set, zero value otherwise.
func (o *User) GetClientAdmin() bool {
	if o == nil || IsNil(o.ClientAdmin) {
		var ret bool
		return ret
	}
	return *o.ClientAdmin
}

// GetClientAdminOk returns a tuple with the ClientAdmin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetClientAdminOk() (*bool, bool) {
	if o == nil || IsNil(o.ClientAdmin) {
		return nil, false
	}
	return o.ClientAdmin, true
}

// HasClientAdmin returns a boolean if a field has been set.
func (o *User) HasClientAdmin() bool {
	if o != nil && !IsNil(o.ClientAdmin) {
		return true
	}

	return false
}

// SetClientAdmin gets a reference to the given bool and assigns it to the ClientAdmin field.
func (o *User) SetClientAdmin(v bool) {
	o.ClientAdmin = &v
}

// GetOrgDefaultRole returns the OrgDefaultRole field value if set, zero value otherwise.
func (o *User) GetOrgDefaultRole() string {
	if o == nil || IsNil(o.OrgDefaultRole) {
		var ret string
		return ret
	}
	return *o.OrgDefaultRole
}

// GetOrgDefaultRoleOk returns a tuple with the OrgDefaultRole field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetOrgDefaultRoleOk() (*string, bool) {
	if o == nil || IsNil(o.OrgDefaultRole) {
		return nil, false
	}
	return o.OrgDefaultRole, true
}

// HasOrgDefaultRole returns a boolean if a field has been set.
func (o *User) HasOrgDefaultRole() bool {
	if o != nil && !IsNil(o.OrgDefaultRole) {
		return true
	}

	return false
}

// SetOrgDefaultRole gets a reference to the given string and assigns it to the OrgDefaultRole field.
func (o *User) SetOrgDefaultRole(v string) {
	o.OrgDefaultRole = &v
}

// GetOrgRoles returns the OrgRoles field value if set, zero value otherwise.
func (o *User) GetOrgRoles() map[string]interface{} {
	if o == nil || IsNil(o.OrgRoles) {
		var ret map[string]interface{}
		return ret
	}
	return o.OrgRoles
}

// GetOrgRolesOk returns a tuple with the OrgRoles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetOrgRolesOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.OrgRoles) {
		return map[string]interface{}{}, false
	}
	return o.OrgRoles, true
}

// HasOrgRoles returns a boolean if a field has been set.
func (o *User) HasOrgRoles() bool {
	if o != nil && !IsNil(o.OrgRoles) {
		return true
	}

	return false
}

// SetOrgRoles gets a reference to the given map[string]interface{} and assigns it to the OrgRoles field.
func (o *User) SetOrgRoles(v map[string]interface{}) {
	o.OrgRoles = v
}

// GetPasswordEnabledAt returns the PasswordEnabledAt field value if set, zero value otherwise.
func (o *User) GetPasswordEnabledAt() int64 {
	if o == nil || IsNil(o.PasswordEnabledAt) {
		var ret int64
		return ret
	}
	return *o.PasswordEnabledAt
}

// GetPasswordEnabledAtOk returns a tuple with the PasswordEnabledAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetPasswordEnabledAtOk() (*int64, bool) {
	if o == nil || IsNil(o.PasswordEnabledAt) {
		return nil, false
	}
	return o.PasswordEnabledAt, true
}

// HasPasswordEnabledAt returns a boolean if a field has been set.
func (o *User) HasPasswordEnabledAt() bool {
	if o != nil && !IsNil(o.PasswordEnabledAt) {
		return true
	}

	return false
}

// SetPasswordEnabledAt gets a reference to the given int64 and assigns it to the PasswordEnabledAt field.
func (o *User) SetPasswordEnabledAt(v int64) {
	o.PasswordEnabledAt = &v
}

// GetInviteTokenExpiration returns the InviteTokenExpiration field value if set, zero value otherwise.
func (o *User) GetInviteTokenExpiration() int64 {
	if o == nil || IsNil(o.InviteTokenExpiration) {
		var ret int64
		return ret
	}
	return *o.InviteTokenExpiration
}

// GetInviteTokenExpirationOk returns a tuple with the InviteTokenExpiration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetInviteTokenExpirationOk() (*int64, bool) {
	if o == nil || IsNil(o.InviteTokenExpiration) {
		return nil, false
	}
	return o.InviteTokenExpiration, true
}

// HasInviteTokenExpiration returns a boolean if a field has been set.
func (o *User) HasInviteTokenExpiration() bool {
	if o != nil && !IsNil(o.InviteTokenExpiration) {
		return true
	}

	return false
}

// SetInviteTokenExpiration gets a reference to the given int64 and assigns it to the InviteTokenExpiration field.
func (o *User) SetInviteTokenExpiration(v int64) {
	o.InviteTokenExpiration = &v
}

// GetResetTokenExpiration returns the ResetTokenExpiration field value if set, zero value otherwise.
func (o *User) GetResetTokenExpiration() int64 {
	if o == nil || IsNil(o.ResetTokenExpiration) {
		var ret int64
		return ret
	}
	return *o.ResetTokenExpiration
}

// GetResetTokenExpirationOk returns a tuple with the ResetTokenExpiration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetResetTokenExpirationOk() (*int64, bool) {
	if o == nil || IsNil(o.ResetTokenExpiration) {
		return nil, false
	}
	return o.ResetTokenExpiration, true
}

// HasResetTokenExpiration returns a boolean if a field has been set.
func (o *User) HasResetTokenExpiration() bool {
	if o != nil && !IsNil(o.ResetTokenExpiration) {
		return true
	}

	return false
}

// SetResetTokenExpiration gets a reference to the given int64 and assigns it to the ResetTokenExpiration field.
func (o *User) SetResetTokenExpiration(v int64) {
	o.ResetTokenExpiration = &v
}

// GetTermsAgreedAsOf returns the TermsAgreedAsOf field value if set, zero value otherwise.
func (o *User) GetTermsAgreedAsOf() int64 {
	if o == nil || IsNil(o.TermsAgreedAsOf) {
		var ret int64
		return ret
	}
	return *o.TermsAgreedAsOf
}

// GetTermsAgreedAsOfOk returns a tuple with the TermsAgreedAsOf field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetTermsAgreedAsOfOk() (*int64, bool) {
	if o == nil || IsNil(o.TermsAgreedAsOf) {
		return nil, false
	}
	return o.TermsAgreedAsOf, true
}

// HasTermsAgreedAsOf returns a boolean if a field has been set.
func (o *User) HasTermsAgreedAsOf() bool {
	if o != nil && !IsNil(o.TermsAgreedAsOf) {
		return true
	}

	return false
}

// SetTermsAgreedAsOf gets a reference to the given int64 and assigns it to the TermsAgreedAsOf field.
func (o *User) SetTermsAgreedAsOf(v int64) {
	o.TermsAgreedAsOf = &v
}

// GetLastLoginIp returns the LastLoginIp field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *User) GetLastLoginIp() string {
	if o == nil || IsNil(o.LastLoginIp.Get()) {
		var ret string
		return ret
	}
	return *o.LastLoginIp.Get()
}

// GetLastLoginIpOk returns a tuple with the LastLoginIp field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *User) GetLastLoginIpOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastLoginIp.Get(), o.LastLoginIp.IsSet()
}

// HasLastLoginIp returns a boolean if a field has been set.
func (o *User) HasLastLoginIp() bool {
	if o != nil && o.LastLoginIp.IsSet() {
		return true
	}

	return false
}

// SetLastLoginIp gets a reference to the given NullableString and assigns it to the LastLoginIp field.
func (o *User) SetLastLoginIp(v string) {
	o.LastLoginIp.Set(&v)
}

// SetLastLoginIpNil sets the value for LastLoginIp to be an explicit nil
func (o *User) SetLastLoginIpNil() {
	o.LastLoginIp.Set(nil)
}

// UnsetLastLoginIp ensures that no value is present for LastLoginIp, not even an explicit nil
func (o *User) UnsetLastLoginIp() {
	o.LastLoginIp.Unset()
}

// GetLastLoginAt returns the LastLoginAt field value if set, zero value otherwise.
func (o *User) GetLastLoginAt() int64 {
	if o == nil || IsNil(o.LastLoginAt) {
		var ret int64
		return ret
	}
	return *o.LastLoginAt
}

// GetLastLoginAtOk returns a tuple with the LastLoginAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetLastLoginAtOk() (*int64, bool) {
	if o == nil || IsNil(o.LastLoginAt) {
		return nil, false
	}
	return o.LastLoginAt, true
}

// HasLastLoginAt returns a boolean if a field has been set.
func (o *User) HasLastLoginAt() bool {
	if o != nil && !IsNil(o.LastLoginAt) {
		return true
	}

	return false
}

// SetLastLoginAt gets a reference to the given int64 and assigns it to the LastLoginAt field.
func (o *User) SetLastLoginAt(v int64) {
	o.LastLoginAt = &v
}

// GetLastLoginUa returns the LastLoginUa field value if set, zero value otherwise.
func (o *User) GetLastLoginUa() string {
	if o == nil || IsNil(o.LastLoginUa) {
		var ret string
		return ret
	}
	return *o.LastLoginUa
}

// GetLastLoginUaOk returns a tuple with the LastLoginUa field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetLastLoginUaOk() (*string, bool) {
	if o == nil || IsNil(o.LastLoginUa) {
		return nil, false
	}
	return o.LastLoginUa, true
}

// HasLastLoginUa returns a boolean if a field has been set.
func (o *User) HasLastLoginUa() bool {
	if o != nil && !IsNil(o.LastLoginUa) {
		return true
	}

	return false
}

// SetLastLoginUa gets a reference to the given string and assigns it to the LastLoginUa field.
func (o *User) SetLastLoginUa(v string) {
	o.LastLoginUa = &v
}

// GetLastActivityAt returns the LastActivityAt field value if set, zero value otherwise.
func (o *User) GetLastActivityAt() int64 {
	if o == nil || IsNil(o.LastActivityAt) {
		var ret int64
		return ret
	}
	return *o.LastActivityAt
}

// GetLastActivityAtOk returns a tuple with the LastActivityAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetLastActivityAtOk() (*int64, bool) {
	if o == nil || IsNil(o.LastActivityAt) {
		return nil, false
	}
	return o.LastActivityAt, true
}

// HasLastActivityAt returns a boolean if a field has been set.
func (o *User) HasLastActivityAt() bool {
	if o != nil && !IsNil(o.LastActivityAt) {
		return true
	}

	return false
}

// SetLastActivityAt gets a reference to the given int64 and assigns it to the LastActivityAt field.
func (o *User) SetLastActivityAt(v int64) {
	o.LastActivityAt = &v
}

// GetSsoOnly returns the SsoOnly field value if set, zero value otherwise.
func (o *User) GetSsoOnly() bool {
	if o == nil || IsNil(o.SsoOnly) {
		var ret bool
		return ret
	}
	return *o.SsoOnly
}

// GetSsoOnlyOk returns a tuple with the SsoOnly field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetSsoOnlyOk() (*bool, bool) {
	if o == nil || IsNil(o.SsoOnly) {
		return nil, false
	}
	return o.SsoOnly, true
}

// HasSsoOnly returns a boolean if a field has been set.
func (o *User) HasSsoOnly() bool {
	if o != nil && !IsNil(o.SsoOnly) {
		return true
	}

	return false
}

// SetSsoOnly gets a reference to the given bool and assigns it to the SsoOnly field.
func (o *User) SetSsoOnly(v bool) {
	o.SsoOnly = &v
}

// GetLoginFailures returns the LoginFailures field value if set, zero value otherwise.
func (o *User) GetLoginFailures() int64 {
	if o == nil || IsNil(o.LoginFailures) {
		var ret int64
		return ret
	}
	return *o.LoginFailures
}

// GetLoginFailuresOk returns a tuple with the LoginFailures field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetLoginFailuresOk() (*int64, bool) {
	if o == nil || IsNil(o.LoginFailures) {
		return nil, false
	}
	return o.LoginFailures, true
}

// HasLoginFailures returns a boolean if a field has been set.
func (o *User) HasLoginFailures() bool {
	if o != nil && !IsNil(o.LoginFailures) {
		return true
	}

	return false
}

// SetLoginFailures gets a reference to the given int64 and assigns it to the LoginFailures field.
func (o *User) SetLoginFailures(v int64) {
	o.LoginFailures = &v
}

// GetActions returns the Actions field value if set, zero value otherwise.
func (o *User) GetActions() int64 {
	if o == nil || IsNil(o.Actions) {
		var ret int64
		return ret
	}
	return *o.Actions
}

// GetActionsOk returns a tuple with the Actions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetActionsOk() (*int64, bool) {
	if o == nil || IsNil(o.Actions) {
		return nil, false
	}
	return o.Actions, true
}

// HasActions returns a boolean if a field has been set.
func (o *User) HasActions() bool {
	if o != nil && !IsNil(o.Actions) {
		return true
	}

	return false
}

// SetActions gets a reference to the given int64 and assigns it to the Actions field.
func (o *User) SetActions(v int64) {
	o.Actions = &v
}

// GetLastActionAt returns the LastActionAt field value if set, zero value otherwise.
func (o *User) GetLastActionAt() int64 {
	if o == nil || IsNil(o.LastActionAt) {
		var ret int64
		return ret
	}
	return *o.LastActionAt
}

// GetLastActionAtOk returns a tuple with the LastActionAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetLastActionAtOk() (*int64, bool) {
	if o == nil || IsNil(o.LastActionAt) {
		return nil, false
	}
	return o.LastActionAt, true
}

// HasLastActionAt returns a boolean if a field has been set.
func (o *User) HasLastActionAt() bool {
	if o != nil && !IsNil(o.LastActionAt) {
		return true
	}

	return false
}

// SetLastActionAt gets a reference to the given int64 and assigns it to the LastActionAt field.
func (o *User) SetLastActionAt(v int64) {
	o.LastActionAt = &v
}

// GetMfaEnabled returns the MfaEnabled field value if set, zero value otherwise.
func (o *User) GetMfaEnabled() bool {
	if o == nil || IsNil(o.MfaEnabled) {
		var ret bool
		return ret
	}
	return *o.MfaEnabled
}

// GetMfaEnabledOk returns a tuple with the MfaEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetMfaEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.MfaEnabled) {
		return nil, false
	}
	return o.MfaEnabled, true
}

// HasMfaEnabled returns a boolean if a field has been set.
func (o *User) HasMfaEnabled() bool {
	if o != nil && !IsNil(o.MfaEnabled) {
		return true
	}

	return false
}

// SetMfaEnabled gets a reference to the given bool and assigns it to the MfaEnabled field.
func (o *User) SetMfaEnabled(v bool) {
	o.MfaEnabled = &v
}

func (o User) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o User) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.ClientId) {
		toSerialize["client_id"] = o.ClientId
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.FirstName) {
		toSerialize["first_name"] = o.FirstName
	}
	if !IsNil(o.LastName) {
		toSerialize["last_name"] = o.LastName
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.ClientAdmin) {
		toSerialize["client_admin"] = o.ClientAdmin
	}
	if !IsNil(o.OrgDefaultRole) {
		toSerialize["org_default_role"] = o.OrgDefaultRole
	}
	if !IsNil(o.OrgRoles) {
		toSerialize["org_roles"] = o.OrgRoles
	}
	if !IsNil(o.PasswordEnabledAt) {
		toSerialize["password_enabled_at"] = o.PasswordEnabledAt
	}
	if !IsNil(o.InviteTokenExpiration) {
		toSerialize["invite_token_expiration"] = o.InviteTokenExpiration
	}
	if !IsNil(o.ResetTokenExpiration) {
		toSerialize["reset_token_expiration"] = o.ResetTokenExpiration
	}
	if !IsNil(o.TermsAgreedAsOf) {
		toSerialize["terms_agreed_as_of"] = o.TermsAgreedAsOf
	}
	if o.LastLoginIp.IsSet() {
		toSerialize["last_login_ip"] = o.LastLoginIp.Get()
	}
	if !IsNil(o.LastLoginAt) {
		toSerialize["last_login_at"] = o.LastLoginAt
	}
	if !IsNil(o.LastLoginUa) {
		toSerialize["last_login_ua"] = o.LastLoginUa
	}
	if !IsNil(o.LastActivityAt) {
		toSerialize["last_activity_at"] = o.LastActivityAt
	}
	if !IsNil(o.SsoOnly) {
		toSerialize["sso_only"] = o.SsoOnly
	}
	if !IsNil(o.LoginFailures) {
		toSerialize["login_failures"] = o.LoginFailures
	}
	if !IsNil(o.Actions) {
		toSerialize["actions"] = o.Actions
	}
	if !IsNil(o.LastActionAt) {
		toSerialize["last_action_at"] = o.LastActionAt
	}
	if !IsNil(o.MfaEnabled) {
		toSerialize["mfa_enabled"] = o.MfaEnabled
	}
	return toSerialize, nil
}

func (o *User) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUser := _User{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUser)

	if err != nil {
		return err
	}

	*o = User(varUser)

	return err
}

type NullableUser struct {
	value *User
	isSet bool
}

func (v NullableUser) Get() *User {
	return v.value
}

func (v *NullableUser) Set(val *User) {
	v.value = val
	v.isSet = true
}

func (v NullableUser) IsSet() bool {
	return v.isSet
}

func (v *NullableUser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUser(val *User) *NullableUser {
	return &NullableUser{value: val, isSet: true}
}

func (v NullableUser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
