/*
runZero API

runZero API. API use is rate limited, you can make as many calls per day as you have licensed assets.

API version: 4.0.250826.0
Contact: support@runzero.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UserInviteOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserInviteOptions{}

// UserInviteOptions struct for UserInviteOptions
type UserInviteOptions struct {
	FirstName *string `json:"first_name,omitempty"`
	LastName *string `json:"last_name,omitempty"`
	Email *string `json:"email,omitempty"`
	ClientAdmin *bool `json:"client_admin,omitempty"`
	OrgDefaultRole *string `json:"org_default_role,omitempty"`
	OrgRoles map[string]interface{} `json:"org_roles,omitempty"`
	Subject *string `json:"subject,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewUserInviteOptions instantiates a new UserInviteOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserInviteOptions() *UserInviteOptions {
	this := UserInviteOptions{}
	return &this
}

// NewUserInviteOptionsWithDefaults instantiates a new UserInviteOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserInviteOptionsWithDefaults() *UserInviteOptions {
	this := UserInviteOptions{}
	return &this
}

// GetFirstName returns the FirstName field value if set, zero value otherwise.
func (o *UserInviteOptions) GetFirstName() string {
	if o == nil || IsNil(o.FirstName) {
		var ret string
		return ret
	}
	return *o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInviteOptions) GetFirstNameOk() (*string, bool) {
	if o == nil || IsNil(o.FirstName) {
		return nil, false
	}
	return o.FirstName, true
}

// HasFirstName returns a boolean if a field has been set.
func (o *UserInviteOptions) HasFirstName() bool {
	if o != nil && !IsNil(o.FirstName) {
		return true
	}

	return false
}

// SetFirstName gets a reference to the given string and assigns it to the FirstName field.
func (o *UserInviteOptions) SetFirstName(v string) {
	o.FirstName = &v
}

// GetLastName returns the LastName field value if set, zero value otherwise.
func (o *UserInviteOptions) GetLastName() string {
	if o == nil || IsNil(o.LastName) {
		var ret string
		return ret
	}
	return *o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInviteOptions) GetLastNameOk() (*string, bool) {
	if o == nil || IsNil(o.LastName) {
		return nil, false
	}
	return o.LastName, true
}

// HasLastName returns a boolean if a field has been set.
func (o *UserInviteOptions) HasLastName() bool {
	if o != nil && !IsNil(o.LastName) {
		return true
	}

	return false
}

// SetLastName gets a reference to the given string and assigns it to the LastName field.
func (o *UserInviteOptions) SetLastName(v string) {
	o.LastName = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *UserInviteOptions) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInviteOptions) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *UserInviteOptions) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *UserInviteOptions) SetEmail(v string) {
	o.Email = &v
}

// GetClientAdmin returns the ClientAdmin field value if set, zero value otherwise.
func (o *UserInviteOptions) GetClientAdmin() bool {
	if o == nil || IsNil(o.ClientAdmin) {
		var ret bool
		return ret
	}
	return *o.ClientAdmin
}

// GetClientAdminOk returns a tuple with the ClientAdmin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInviteOptions) GetClientAdminOk() (*bool, bool) {
	if o == nil || IsNil(o.ClientAdmin) {
		return nil, false
	}
	return o.ClientAdmin, true
}

// HasClientAdmin returns a boolean if a field has been set.
func (o *UserInviteOptions) HasClientAdmin() bool {
	if o != nil && !IsNil(o.ClientAdmin) {
		return true
	}

	return false
}

// SetClientAdmin gets a reference to the given bool and assigns it to the ClientAdmin field.
func (o *UserInviteOptions) SetClientAdmin(v bool) {
	o.ClientAdmin = &v
}

// GetOrgDefaultRole returns the OrgDefaultRole field value if set, zero value otherwise.
func (o *UserInviteOptions) GetOrgDefaultRole() string {
	if o == nil || IsNil(o.OrgDefaultRole) {
		var ret string
		return ret
	}
	return *o.OrgDefaultRole
}

// GetOrgDefaultRoleOk returns a tuple with the OrgDefaultRole field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInviteOptions) GetOrgDefaultRoleOk() (*string, bool) {
	if o == nil || IsNil(o.OrgDefaultRole) {
		return nil, false
	}
	return o.OrgDefaultRole, true
}

// HasOrgDefaultRole returns a boolean if a field has been set.
func (o *UserInviteOptions) HasOrgDefaultRole() bool {
	if o != nil && !IsNil(o.OrgDefaultRole) {
		return true
	}

	return false
}

// SetOrgDefaultRole gets a reference to the given string and assigns it to the OrgDefaultRole field.
func (o *UserInviteOptions) SetOrgDefaultRole(v string) {
	o.OrgDefaultRole = &v
}

// GetOrgRoles returns the OrgRoles field value if set, zero value otherwise.
func (o *UserInviteOptions) GetOrgRoles() map[string]interface{} {
	if o == nil || IsNil(o.OrgRoles) {
		var ret map[string]interface{}
		return ret
	}
	return o.OrgRoles
}

// GetOrgRolesOk returns a tuple with the OrgRoles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInviteOptions) GetOrgRolesOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.OrgRoles) {
		return map[string]interface{}{}, false
	}
	return o.OrgRoles, true
}

// HasOrgRoles returns a boolean if a field has been set.
func (o *UserInviteOptions) HasOrgRoles() bool {
	if o != nil && !IsNil(o.OrgRoles) {
		return true
	}

	return false
}

// SetOrgRoles gets a reference to the given map[string]interface{} and assigns it to the OrgRoles field.
func (o *UserInviteOptions) SetOrgRoles(v map[string]interface{}) {
	o.OrgRoles = v
}

// GetSubject returns the Subject field value if set, zero value otherwise.
func (o *UserInviteOptions) GetSubject() string {
	if o == nil || IsNil(o.Subject) {
		var ret string
		return ret
	}
	return *o.Subject
}

// GetSubjectOk returns a tuple with the Subject field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInviteOptions) GetSubjectOk() (*string, bool) {
	if o == nil || IsNil(o.Subject) {
		return nil, false
	}
	return o.Subject, true
}

// HasSubject returns a boolean if a field has been set.
func (o *UserInviteOptions) HasSubject() bool {
	if o != nil && !IsNil(o.Subject) {
		return true
	}

	return false
}

// SetSubject gets a reference to the given string and assigns it to the Subject field.
func (o *UserInviteOptions) SetSubject(v string) {
	o.Subject = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *UserInviteOptions) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInviteOptions) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *UserInviteOptions) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *UserInviteOptions) SetMessage(v string) {
	o.Message = &v
}

func (o UserInviteOptions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserInviteOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FirstName) {
		toSerialize["first_name"] = o.FirstName
	}
	if !IsNil(o.LastName) {
		toSerialize["last_name"] = o.LastName
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.ClientAdmin) {
		toSerialize["client_admin"] = o.ClientAdmin
	}
	if !IsNil(o.OrgDefaultRole) {
		toSerialize["org_default_role"] = o.OrgDefaultRole
	}
	if !IsNil(o.OrgRoles) {
		toSerialize["org_roles"] = o.OrgRoles
	}
	if !IsNil(o.Subject) {
		toSerialize["subject"] = o.Subject
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableUserInviteOptions struct {
	value *UserInviteOptions
	isSet bool
}

func (v NullableUserInviteOptions) Get() *UserInviteOptions {
	return v.value
}

func (v *NullableUserInviteOptions) Set(val *UserInviteOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableUserInviteOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableUserInviteOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserInviteOptions(val *UserInviteOptions) *NullableUserInviteOptions {
	return &NullableUserInviteOptions{value: val, isSet: true}
}

func (v NullableUserInviteOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserInviteOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


