/*
runZero API

runZero API. API use is rate limited, you can make as many calls per day as you have licensed assets.

API version: 4.0.250826.0
Contact: support@runzero.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package runzero

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the LDAPCredentialFields type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LDAPCredentialFields{}

// LDAPCredentialFields struct for LDAPCredentialFields
type LDAPCredentialFields struct {
	Url         string  `json:"url"`
	Username    string  `json:"username"`
	Password    string  `json:"password"`
	BaseDn      string  `json:"base_dn"`
	Insecure    *string `json:"insecure,omitempty"`
	LegacyTls   *string `json:"legacy_tls,omitempty"`
	Thumbprints *string `json:"thumbprints,omitempty"`
}

type _LDAPCredentialFields LDAPCredentialFields

// NewLDAPCredentialFields instantiates a new LDAPCredentialFields object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLDAPCredentialFields(url string, username string, password string, baseDn string) *LDAPCredentialFields {
	this := LDAPCredentialFields{}
	this.Url = url
	this.Username = username
	this.Password = password
	this.BaseDn = baseDn
	return &this
}

// NewLDAPCredentialFieldsWithDefaults instantiates a new LDAPCredentialFields object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLDAPCredentialFieldsWithDefaults() *LDAPCredentialFields {
	this := LDAPCredentialFields{}
	return &this
}

// GetUrl returns the Url field value
func (o *LDAPCredentialFields) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *LDAPCredentialFields) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *LDAPCredentialFields) SetUrl(v string) {
	o.Url = v
}

// GetUsername returns the Username field value
func (o *LDAPCredentialFields) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *LDAPCredentialFields) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *LDAPCredentialFields) SetUsername(v string) {
	o.Username = v
}

// GetPassword returns the Password field value
func (o *LDAPCredentialFields) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *LDAPCredentialFields) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *LDAPCredentialFields) SetPassword(v string) {
	o.Password = v
}

// GetBaseDn returns the BaseDn field value
func (o *LDAPCredentialFields) GetBaseDn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BaseDn
}

// GetBaseDnOk returns a tuple with the BaseDn field value
// and a boolean to check if the value has been set.
func (o *LDAPCredentialFields) GetBaseDnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BaseDn, true
}

// SetBaseDn sets field value
func (o *LDAPCredentialFields) SetBaseDn(v string) {
	o.BaseDn = v
}

// GetInsecure returns the Insecure field value if set, zero value otherwise.
func (o *LDAPCredentialFields) GetInsecure() string {
	if o == nil || IsNil(o.Insecure) {
		var ret string
		return ret
	}
	return *o.Insecure
}

// GetInsecureOk returns a tuple with the Insecure field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LDAPCredentialFields) GetInsecureOk() (*string, bool) {
	if o == nil || IsNil(o.Insecure) {
		return nil, false
	}
	return o.Insecure, true
}

// HasInsecure returns a boolean if a field has been set.
func (o *LDAPCredentialFields) HasInsecure() bool {
	if o != nil && !IsNil(o.Insecure) {
		return true
	}

	return false
}

// SetInsecure gets a reference to the given string and assigns it to the Insecure field.
func (o *LDAPCredentialFields) SetInsecure(v string) {
	o.Insecure = &v
}

// GetLegacyTls returns the LegacyTls field value if set, zero value otherwise.
func (o *LDAPCredentialFields) GetLegacyTls() string {
	if o == nil || IsNil(o.LegacyTls) {
		var ret string
		return ret
	}
	return *o.LegacyTls
}

// GetLegacyTlsOk returns a tuple with the LegacyTls field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LDAPCredentialFields) GetLegacyTlsOk() (*string, bool) {
	if o == nil || IsNil(o.LegacyTls) {
		return nil, false
	}
	return o.LegacyTls, true
}

// HasLegacyTls returns a boolean if a field has been set.
func (o *LDAPCredentialFields) HasLegacyTls() bool {
	if o != nil && !IsNil(o.LegacyTls) {
		return true
	}

	return false
}

// SetLegacyTls gets a reference to the given string and assigns it to the LegacyTls field.
func (o *LDAPCredentialFields) SetLegacyTls(v string) {
	o.LegacyTls = &v
}

// GetThumbprints returns the Thumbprints field value if set, zero value otherwise.
func (o *LDAPCredentialFields) GetThumbprints() string {
	if o == nil || IsNil(o.Thumbprints) {
		var ret string
		return ret
	}
	return *o.Thumbprints
}

// GetThumbprintsOk returns a tuple with the Thumbprints field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LDAPCredentialFields) GetThumbprintsOk() (*string, bool) {
	if o == nil || IsNil(o.Thumbprints) {
		return nil, false
	}
	return o.Thumbprints, true
}

// HasThumbprints returns a boolean if a field has been set.
func (o *LDAPCredentialFields) HasThumbprints() bool {
	if o != nil && !IsNil(o.Thumbprints) {
		return true
	}

	return false
}

// SetThumbprints gets a reference to the given string and assigns it to the Thumbprints field.
func (o *LDAPCredentialFields) SetThumbprints(v string) {
	o.Thumbprints = &v
}

func (o LDAPCredentialFields) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LDAPCredentialFields) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["url"] = o.Url
	toSerialize["username"] = o.Username
	toSerialize["password"] = o.Password
	toSerialize["base_dn"] = o.BaseDn
	if !IsNil(o.Insecure) {
		toSerialize["insecure"] = o.Insecure
	}
	if !IsNil(o.LegacyTls) {
		toSerialize["legacy_tls"] = o.LegacyTls
	}
	if !IsNil(o.Thumbprints) {
		toSerialize["thumbprints"] = o.Thumbprints
	}
	return toSerialize, nil
}

func (o *LDAPCredentialFields) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"url",
		"username",
		"password",
		"base_dn",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLDAPCredentialFields := _LDAPCredentialFields{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLDAPCredentialFields)

	if err != nil {
		return err
	}

	*o = LDAPCredentialFields(varLDAPCredentialFields)

	return err
}

type NullableLDAPCredentialFields struct {
	value *LDAPCredentialFields
	isSet bool
}

func (v NullableLDAPCredentialFields) Get() *LDAPCredentialFields {
	return v.value
}

func (v *NullableLDAPCredentialFields) Set(val *LDAPCredentialFields) {
	v.value = val
	v.isSet = true
}

func (v NullableLDAPCredentialFields) IsSet() bool {
	return v.isSet
}

func (v *NullableLDAPCredentialFields) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLDAPCredentialFields(val *LDAPCredentialFields) *NullableLDAPCredentialFields {
	return &NullableLDAPCredentialFields{value: val, isSet: true}
}

func (v NullableLDAPCredentialFields) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLDAPCredentialFields) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
