/*
runZero API

runZero API

API version: 3.0.0
Contact: support@runzero.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// AssetTagsWithSearch struct for AssetTagsWithSearch
type AssetTagsWithSearch struct {
	Tags string `json:"tags"`
	Search string `json:"search"`
}

// NewAssetTagsWithSearch instantiates a new AssetTagsWithSearch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssetTagsWithSearch(tags string, search string) *AssetTagsWithSearch {
	this := AssetTagsWithSearch{}
	this.Tags = tags
	this.Search = search
	return &this
}

// NewAssetTagsWithSearchWithDefaults instantiates a new AssetTagsWithSearch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssetTagsWithSearchWithDefaults() *AssetTagsWithSearch {
	this := AssetTagsWithSearch{}
	return &this
}

// GetTags returns the Tags field value
func (o *AssetTagsWithSearch) GetTags() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value
// and a boolean to check if the value has been set.
func (o *AssetTagsWithSearch) GetTagsOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Tags, true
}

// SetTags sets field value
func (o *AssetTagsWithSearch) SetTags(v string) {
	o.Tags = v
}

// GetSearch returns the Search field value
func (o *AssetTagsWithSearch) GetSearch() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Search
}

// GetSearchOk returns a tuple with the Search field value
// and a boolean to check if the value has been set.
func (o *AssetTagsWithSearch) GetSearchOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Search, true
}

// SetSearch sets field value
func (o *AssetTagsWithSearch) SetSearch(v string) {
	o.Search = v
}

func (o AssetTagsWithSearch) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["tags"] = o.Tags
	}
	if true {
		toSerialize["search"] = o.Search
	}
	return json.Marshal(toSerialize)
}

type NullableAssetTagsWithSearch struct {
	value *AssetTagsWithSearch
	isSet bool
}

func (v NullableAssetTagsWithSearch) Get() *AssetTagsWithSearch {
	return v.value
}

func (v *NullableAssetTagsWithSearch) Set(val *AssetTagsWithSearch) {
	v.value = val
	v.isSet = true
}

func (v NullableAssetTagsWithSearch) IsSet() bool {
	return v.isSet
}

func (v *NullableAssetTagsWithSearch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssetTagsWithSearch(val *AssetTagsWithSearch) *NullableAssetTagsWithSearch {
	return &NullableAssetTagsWithSearch{value: val, isSet: true}
}

func (v NullableAssetTagsWithSearch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssetTagsWithSearch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


