/*
runZero API

runZero API. API use is rate limited, you can make as many calls per day as you have licensed assets.

API version: 4.0.250826.0
Contact: support@runzero.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package runzero

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the InsightVMCredentialFields type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InsightVMCredentialFields{}

// InsightVMCredentialFields struct for InsightVMCredentialFields
type InsightVMCredentialFields struct {
	ApiUrl      string  `json:"api_url"`
	Username    string  `json:"username"`
	Password    string  `json:"password"`
	Insecure    *string `json:"insecure,omitempty"`
	Thumbprints *string `json:"thumbprints,omitempty"`
}

type _InsightVMCredentialFields InsightVMCredentialFields

// NewInsightVMCredentialFields instantiates a new InsightVMCredentialFields object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInsightVMCredentialFields(apiUrl string, username string, password string) *InsightVMCredentialFields {
	this := InsightVMCredentialFields{}
	this.ApiUrl = apiUrl
	this.Username = username
	this.Password = password
	return &this
}

// NewInsightVMCredentialFieldsWithDefaults instantiates a new InsightVMCredentialFields object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInsightVMCredentialFieldsWithDefaults() *InsightVMCredentialFields {
	this := InsightVMCredentialFields{}
	return &this
}

// GetApiUrl returns the ApiUrl field value
func (o *InsightVMCredentialFields) GetApiUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApiUrl
}

// GetApiUrlOk returns a tuple with the ApiUrl field value
// and a boolean to check if the value has been set.
func (o *InsightVMCredentialFields) GetApiUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApiUrl, true
}

// SetApiUrl sets field value
func (o *InsightVMCredentialFields) SetApiUrl(v string) {
	o.ApiUrl = v
}

// GetUsername returns the Username field value
func (o *InsightVMCredentialFields) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *InsightVMCredentialFields) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *InsightVMCredentialFields) SetUsername(v string) {
	o.Username = v
}

// GetPassword returns the Password field value
func (o *InsightVMCredentialFields) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *InsightVMCredentialFields) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *InsightVMCredentialFields) SetPassword(v string) {
	o.Password = v
}

// GetInsecure returns the Insecure field value if set, zero value otherwise.
func (o *InsightVMCredentialFields) GetInsecure() string {
	if o == nil || IsNil(o.Insecure) {
		var ret string
		return ret
	}
	return *o.Insecure
}

// GetInsecureOk returns a tuple with the Insecure field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InsightVMCredentialFields) GetInsecureOk() (*string, bool) {
	if o == nil || IsNil(o.Insecure) {
		return nil, false
	}
	return o.Insecure, true
}

// HasInsecure returns a boolean if a field has been set.
func (o *InsightVMCredentialFields) HasInsecure() bool {
	if o != nil && !IsNil(o.Insecure) {
		return true
	}

	return false
}

// SetInsecure gets a reference to the given string and assigns it to the Insecure field.
func (o *InsightVMCredentialFields) SetInsecure(v string) {
	o.Insecure = &v
}

// GetThumbprints returns the Thumbprints field value if set, zero value otherwise.
func (o *InsightVMCredentialFields) GetThumbprints() string {
	if o == nil || IsNil(o.Thumbprints) {
		var ret string
		return ret
	}
	return *o.Thumbprints
}

// GetThumbprintsOk returns a tuple with the Thumbprints field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InsightVMCredentialFields) GetThumbprintsOk() (*string, bool) {
	if o == nil || IsNil(o.Thumbprints) {
		return nil, false
	}
	return o.Thumbprints, true
}

// HasThumbprints returns a boolean if a field has been set.
func (o *InsightVMCredentialFields) HasThumbprints() bool {
	if o != nil && !IsNil(o.Thumbprints) {
		return true
	}

	return false
}

// SetThumbprints gets a reference to the given string and assigns it to the Thumbprints field.
func (o *InsightVMCredentialFields) SetThumbprints(v string) {
	o.Thumbprints = &v
}

func (o InsightVMCredentialFields) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InsightVMCredentialFields) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["api_url"] = o.ApiUrl
	toSerialize["username"] = o.Username
	toSerialize["password"] = o.Password
	if !IsNil(o.Insecure) {
		toSerialize["insecure"] = o.Insecure
	}
	if !IsNil(o.Thumbprints) {
		toSerialize["thumbprints"] = o.Thumbprints
	}
	return toSerialize, nil
}

func (o *InsightVMCredentialFields) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"api_url",
		"username",
		"password",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInsightVMCredentialFields := _InsightVMCredentialFields{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInsightVMCredentialFields)

	if err != nil {
		return err
	}

	*o = InsightVMCredentialFields(varInsightVMCredentialFields)

	return err
}

type NullableInsightVMCredentialFields struct {
	value *InsightVMCredentialFields
	isSet bool
}

func (v NullableInsightVMCredentialFields) Get() *InsightVMCredentialFields {
	return v.value
}

func (v *NullableInsightVMCredentialFields) Set(val *InsightVMCredentialFields) {
	v.value = val
	v.isSet = true
}

func (v NullableInsightVMCredentialFields) IsSet() bool {
	return v.isSet
}

func (v *NullableInsightVMCredentialFields) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInsightVMCredentialFields(val *InsightVMCredentialFields) *NullableInsightVMCredentialFields {
	return &NullableInsightVMCredentialFields{value: val, isSet: true}
}

func (v NullableInsightVMCredentialFields) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInsightVMCredentialFields) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
