/*
runZero API

runZero API. API use is rate limited, you can make as many calls per day as you have licensed assets.

API version: 4.0.250826.0
Contact: support@runzero.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package runzero

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the DirectoryGroup type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DirectoryGroup{}

// DirectoryGroup struct for DirectoryGroup
type DirectoryGroup struct {
	Id                            string             `json:"id"`
	DirectoryGroupId              *string            `json:"directory_group_id,omitempty"`
	DirectoryGroupOrganizationId  *string            `json:"directory_group_organization_id,omitempty"`
	DirectoryGroupSiteId          *string            `json:"directory_group_site_id,omitempty"`
	DirectoryGroupSourceId        *int32             `json:"directory_group_source_id,omitempty"`
	DirectoryGroupCreatedAt       *int64             `json:"directory_group_created_at,omitempty"`
	DirectoryGroupUpdatedAt       *int64             `json:"directory_group_updated_at,omitempty"`
	DirectoryGroupGroupId         *string            `json:"directory_group_group_id,omitempty"`
	DirectoryGroupUserCount       *int64             `json:"directory_group_user_count,omitempty"`
	DirectoryGroupName            *string            `json:"directory_group_name,omitempty"`
	DirectoryGroupDisplayName     *string            `json:"directory_group_display_name,omitempty"`
	DirectoryGroupDescription     *string            `json:"directory_group_description,omitempty"`
	DirectoryGroupEmail           *string            `json:"directory_group_email,omitempty"`
	DirectoryGroupEmailNormalized *string            `json:"directory_group_email_normalized,omitempty"`
	DirectoryGroupAttributes      *map[string]string `json:"directory_group_attributes,omitempty"`
}

type _DirectoryGroup DirectoryGroup

// NewDirectoryGroup instantiates a new DirectoryGroup object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDirectoryGroup(id string) *DirectoryGroup {
	this := DirectoryGroup{}
	this.Id = id
	return &this
}

// NewDirectoryGroupWithDefaults instantiates a new DirectoryGroup object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDirectoryGroupWithDefaults() *DirectoryGroup {
	this := DirectoryGroup{}
	return &this
}

// GetId returns the Id field value
func (o *DirectoryGroup) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DirectoryGroup) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DirectoryGroup) SetId(v string) {
	o.Id = v
}

// GetDirectoryGroupId returns the DirectoryGroupId field value if set, zero value otherwise.
func (o *DirectoryGroup) GetDirectoryGroupId() string {
	if o == nil || IsNil(o.DirectoryGroupId) {
		var ret string
		return ret
	}
	return *o.DirectoryGroupId
}

// GetDirectoryGroupIdOk returns a tuple with the DirectoryGroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectoryGroup) GetDirectoryGroupIdOk() (*string, bool) {
	if o == nil || IsNil(o.DirectoryGroupId) {
		return nil, false
	}
	return o.DirectoryGroupId, true
}

// HasDirectoryGroupId returns a boolean if a field has been set.
func (o *DirectoryGroup) HasDirectoryGroupId() bool {
	if o != nil && !IsNil(o.DirectoryGroupId) {
		return true
	}

	return false
}

// SetDirectoryGroupId gets a reference to the given string and assigns it to the DirectoryGroupId field.
func (o *DirectoryGroup) SetDirectoryGroupId(v string) {
	o.DirectoryGroupId = &v
}

// GetDirectoryGroupOrganizationId returns the DirectoryGroupOrganizationId field value if set, zero value otherwise.
func (o *DirectoryGroup) GetDirectoryGroupOrganizationId() string {
	if o == nil || IsNil(o.DirectoryGroupOrganizationId) {
		var ret string
		return ret
	}
	return *o.DirectoryGroupOrganizationId
}

// GetDirectoryGroupOrganizationIdOk returns a tuple with the DirectoryGroupOrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectoryGroup) GetDirectoryGroupOrganizationIdOk() (*string, bool) {
	if o == nil || IsNil(o.DirectoryGroupOrganizationId) {
		return nil, false
	}
	return o.DirectoryGroupOrganizationId, true
}

// HasDirectoryGroupOrganizationId returns a boolean if a field has been set.
func (o *DirectoryGroup) HasDirectoryGroupOrganizationId() bool {
	if o != nil && !IsNil(o.DirectoryGroupOrganizationId) {
		return true
	}

	return false
}

// SetDirectoryGroupOrganizationId gets a reference to the given string and assigns it to the DirectoryGroupOrganizationId field.
func (o *DirectoryGroup) SetDirectoryGroupOrganizationId(v string) {
	o.DirectoryGroupOrganizationId = &v
}

// GetDirectoryGroupSiteId returns the DirectoryGroupSiteId field value if set, zero value otherwise.
func (o *DirectoryGroup) GetDirectoryGroupSiteId() string {
	if o == nil || IsNil(o.DirectoryGroupSiteId) {
		var ret string
		return ret
	}
	return *o.DirectoryGroupSiteId
}

// GetDirectoryGroupSiteIdOk returns a tuple with the DirectoryGroupSiteId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectoryGroup) GetDirectoryGroupSiteIdOk() (*string, bool) {
	if o == nil || IsNil(o.DirectoryGroupSiteId) {
		return nil, false
	}
	return o.DirectoryGroupSiteId, true
}

// HasDirectoryGroupSiteId returns a boolean if a field has been set.
func (o *DirectoryGroup) HasDirectoryGroupSiteId() bool {
	if o != nil && !IsNil(o.DirectoryGroupSiteId) {
		return true
	}

	return false
}

// SetDirectoryGroupSiteId gets a reference to the given string and assigns it to the DirectoryGroupSiteId field.
func (o *DirectoryGroup) SetDirectoryGroupSiteId(v string) {
	o.DirectoryGroupSiteId = &v
}

// GetDirectoryGroupSourceId returns the DirectoryGroupSourceId field value if set, zero value otherwise.
func (o *DirectoryGroup) GetDirectoryGroupSourceId() int32 {
	if o == nil || IsNil(o.DirectoryGroupSourceId) {
		var ret int32
		return ret
	}
	return *o.DirectoryGroupSourceId
}

// GetDirectoryGroupSourceIdOk returns a tuple with the DirectoryGroupSourceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectoryGroup) GetDirectoryGroupSourceIdOk() (*int32, bool) {
	if o == nil || IsNil(o.DirectoryGroupSourceId) {
		return nil, false
	}
	return o.DirectoryGroupSourceId, true
}

// HasDirectoryGroupSourceId returns a boolean if a field has been set.
func (o *DirectoryGroup) HasDirectoryGroupSourceId() bool {
	if o != nil && !IsNil(o.DirectoryGroupSourceId) {
		return true
	}

	return false
}

// SetDirectoryGroupSourceId gets a reference to the given int32 and assigns it to the DirectoryGroupSourceId field.
func (o *DirectoryGroup) SetDirectoryGroupSourceId(v int32) {
	o.DirectoryGroupSourceId = &v
}

// GetDirectoryGroupCreatedAt returns the DirectoryGroupCreatedAt field value if set, zero value otherwise.
func (o *DirectoryGroup) GetDirectoryGroupCreatedAt() int64 {
	if o == nil || IsNil(o.DirectoryGroupCreatedAt) {
		var ret int64
		return ret
	}
	return *o.DirectoryGroupCreatedAt
}

// GetDirectoryGroupCreatedAtOk returns a tuple with the DirectoryGroupCreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectoryGroup) GetDirectoryGroupCreatedAtOk() (*int64, bool) {
	if o == nil || IsNil(o.DirectoryGroupCreatedAt) {
		return nil, false
	}
	return o.DirectoryGroupCreatedAt, true
}

// HasDirectoryGroupCreatedAt returns a boolean if a field has been set.
func (o *DirectoryGroup) HasDirectoryGroupCreatedAt() bool {
	if o != nil && !IsNil(o.DirectoryGroupCreatedAt) {
		return true
	}

	return false
}

// SetDirectoryGroupCreatedAt gets a reference to the given int64 and assigns it to the DirectoryGroupCreatedAt field.
func (o *DirectoryGroup) SetDirectoryGroupCreatedAt(v int64) {
	o.DirectoryGroupCreatedAt = &v
}

// GetDirectoryGroupUpdatedAt returns the DirectoryGroupUpdatedAt field value if set, zero value otherwise.
func (o *DirectoryGroup) GetDirectoryGroupUpdatedAt() int64 {
	if o == nil || IsNil(o.DirectoryGroupUpdatedAt) {
		var ret int64
		return ret
	}
	return *o.DirectoryGroupUpdatedAt
}

// GetDirectoryGroupUpdatedAtOk returns a tuple with the DirectoryGroupUpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectoryGroup) GetDirectoryGroupUpdatedAtOk() (*int64, bool) {
	if o == nil || IsNil(o.DirectoryGroupUpdatedAt) {
		return nil, false
	}
	return o.DirectoryGroupUpdatedAt, true
}

// HasDirectoryGroupUpdatedAt returns a boolean if a field has been set.
func (o *DirectoryGroup) HasDirectoryGroupUpdatedAt() bool {
	if o != nil && !IsNil(o.DirectoryGroupUpdatedAt) {
		return true
	}

	return false
}

// SetDirectoryGroupUpdatedAt gets a reference to the given int64 and assigns it to the DirectoryGroupUpdatedAt field.
func (o *DirectoryGroup) SetDirectoryGroupUpdatedAt(v int64) {
	o.DirectoryGroupUpdatedAt = &v
}

// GetDirectoryGroupGroupId returns the DirectoryGroupGroupId field value if set, zero value otherwise.
func (o *DirectoryGroup) GetDirectoryGroupGroupId() string {
	if o == nil || IsNil(o.DirectoryGroupGroupId) {
		var ret string
		return ret
	}
	return *o.DirectoryGroupGroupId
}

// GetDirectoryGroupGroupIdOk returns a tuple with the DirectoryGroupGroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectoryGroup) GetDirectoryGroupGroupIdOk() (*string, bool) {
	if o == nil || IsNil(o.DirectoryGroupGroupId) {
		return nil, false
	}
	return o.DirectoryGroupGroupId, true
}

// HasDirectoryGroupGroupId returns a boolean if a field has been set.
func (o *DirectoryGroup) HasDirectoryGroupGroupId() bool {
	if o != nil && !IsNil(o.DirectoryGroupGroupId) {
		return true
	}

	return false
}

// SetDirectoryGroupGroupId gets a reference to the given string and assigns it to the DirectoryGroupGroupId field.
func (o *DirectoryGroup) SetDirectoryGroupGroupId(v string) {
	o.DirectoryGroupGroupId = &v
}

// GetDirectoryGroupUserCount returns the DirectoryGroupUserCount field value if set, zero value otherwise.
func (o *DirectoryGroup) GetDirectoryGroupUserCount() int64 {
	if o == nil || IsNil(o.DirectoryGroupUserCount) {
		var ret int64
		return ret
	}
	return *o.DirectoryGroupUserCount
}

// GetDirectoryGroupUserCountOk returns a tuple with the DirectoryGroupUserCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectoryGroup) GetDirectoryGroupUserCountOk() (*int64, bool) {
	if o == nil || IsNil(o.DirectoryGroupUserCount) {
		return nil, false
	}
	return o.DirectoryGroupUserCount, true
}

// HasDirectoryGroupUserCount returns a boolean if a field has been set.
func (o *DirectoryGroup) HasDirectoryGroupUserCount() bool {
	if o != nil && !IsNil(o.DirectoryGroupUserCount) {
		return true
	}

	return false
}

// SetDirectoryGroupUserCount gets a reference to the given int64 and assigns it to the DirectoryGroupUserCount field.
func (o *DirectoryGroup) SetDirectoryGroupUserCount(v int64) {
	o.DirectoryGroupUserCount = &v
}

// GetDirectoryGroupName returns the DirectoryGroupName field value if set, zero value otherwise.
func (o *DirectoryGroup) GetDirectoryGroupName() string {
	if o == nil || IsNil(o.DirectoryGroupName) {
		var ret string
		return ret
	}
	return *o.DirectoryGroupName
}

// GetDirectoryGroupNameOk returns a tuple with the DirectoryGroupName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectoryGroup) GetDirectoryGroupNameOk() (*string, bool) {
	if o == nil || IsNil(o.DirectoryGroupName) {
		return nil, false
	}
	return o.DirectoryGroupName, true
}

// HasDirectoryGroupName returns a boolean if a field has been set.
func (o *DirectoryGroup) HasDirectoryGroupName() bool {
	if o != nil && !IsNil(o.DirectoryGroupName) {
		return true
	}

	return false
}

// SetDirectoryGroupName gets a reference to the given string and assigns it to the DirectoryGroupName field.
func (o *DirectoryGroup) SetDirectoryGroupName(v string) {
	o.DirectoryGroupName = &v
}

// GetDirectoryGroupDisplayName returns the DirectoryGroupDisplayName field value if set, zero value otherwise.
func (o *DirectoryGroup) GetDirectoryGroupDisplayName() string {
	if o == nil || IsNil(o.DirectoryGroupDisplayName) {
		var ret string
		return ret
	}
	return *o.DirectoryGroupDisplayName
}

// GetDirectoryGroupDisplayNameOk returns a tuple with the DirectoryGroupDisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectoryGroup) GetDirectoryGroupDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DirectoryGroupDisplayName) {
		return nil, false
	}
	return o.DirectoryGroupDisplayName, true
}

// HasDirectoryGroupDisplayName returns a boolean if a field has been set.
func (o *DirectoryGroup) HasDirectoryGroupDisplayName() bool {
	if o != nil && !IsNil(o.DirectoryGroupDisplayName) {
		return true
	}

	return false
}

// SetDirectoryGroupDisplayName gets a reference to the given string and assigns it to the DirectoryGroupDisplayName field.
func (o *DirectoryGroup) SetDirectoryGroupDisplayName(v string) {
	o.DirectoryGroupDisplayName = &v
}

// GetDirectoryGroupDescription returns the DirectoryGroupDescription field value if set, zero value otherwise.
func (o *DirectoryGroup) GetDirectoryGroupDescription() string {
	if o == nil || IsNil(o.DirectoryGroupDescription) {
		var ret string
		return ret
	}
	return *o.DirectoryGroupDescription
}

// GetDirectoryGroupDescriptionOk returns a tuple with the DirectoryGroupDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectoryGroup) GetDirectoryGroupDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.DirectoryGroupDescription) {
		return nil, false
	}
	return o.DirectoryGroupDescription, true
}

// HasDirectoryGroupDescription returns a boolean if a field has been set.
func (o *DirectoryGroup) HasDirectoryGroupDescription() bool {
	if o != nil && !IsNil(o.DirectoryGroupDescription) {
		return true
	}

	return false
}

// SetDirectoryGroupDescription gets a reference to the given string and assigns it to the DirectoryGroupDescription field.
func (o *DirectoryGroup) SetDirectoryGroupDescription(v string) {
	o.DirectoryGroupDescription = &v
}

// GetDirectoryGroupEmail returns the DirectoryGroupEmail field value if set, zero value otherwise.
func (o *DirectoryGroup) GetDirectoryGroupEmail() string {
	if o == nil || IsNil(o.DirectoryGroupEmail) {
		var ret string
		return ret
	}
	return *o.DirectoryGroupEmail
}

// GetDirectoryGroupEmailOk returns a tuple with the DirectoryGroupEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectoryGroup) GetDirectoryGroupEmailOk() (*string, bool) {
	if o == nil || IsNil(o.DirectoryGroupEmail) {
		return nil, false
	}
	return o.DirectoryGroupEmail, true
}

// HasDirectoryGroupEmail returns a boolean if a field has been set.
func (o *DirectoryGroup) HasDirectoryGroupEmail() bool {
	if o != nil && !IsNil(o.DirectoryGroupEmail) {
		return true
	}

	return false
}

// SetDirectoryGroupEmail gets a reference to the given string and assigns it to the DirectoryGroupEmail field.
func (o *DirectoryGroup) SetDirectoryGroupEmail(v string) {
	o.DirectoryGroupEmail = &v
}

// GetDirectoryGroupEmailNormalized returns the DirectoryGroupEmailNormalized field value if set, zero value otherwise.
func (o *DirectoryGroup) GetDirectoryGroupEmailNormalized() string {
	if o == nil || IsNil(o.DirectoryGroupEmailNormalized) {
		var ret string
		return ret
	}
	return *o.DirectoryGroupEmailNormalized
}

// GetDirectoryGroupEmailNormalizedOk returns a tuple with the DirectoryGroupEmailNormalized field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectoryGroup) GetDirectoryGroupEmailNormalizedOk() (*string, bool) {
	if o == nil || IsNil(o.DirectoryGroupEmailNormalized) {
		return nil, false
	}
	return o.DirectoryGroupEmailNormalized, true
}

// HasDirectoryGroupEmailNormalized returns a boolean if a field has been set.
func (o *DirectoryGroup) HasDirectoryGroupEmailNormalized() bool {
	if o != nil && !IsNil(o.DirectoryGroupEmailNormalized) {
		return true
	}

	return false
}

// SetDirectoryGroupEmailNormalized gets a reference to the given string and assigns it to the DirectoryGroupEmailNormalized field.
func (o *DirectoryGroup) SetDirectoryGroupEmailNormalized(v string) {
	o.DirectoryGroupEmailNormalized = &v
}

// GetDirectoryGroupAttributes returns the DirectoryGroupAttributes field value if set, zero value otherwise.
func (o *DirectoryGroup) GetDirectoryGroupAttributes() map[string]string {
	if o == nil || IsNil(o.DirectoryGroupAttributes) {
		var ret map[string]string
		return ret
	}
	return *o.DirectoryGroupAttributes
}

// GetDirectoryGroupAttributesOk returns a tuple with the DirectoryGroupAttributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectoryGroup) GetDirectoryGroupAttributesOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.DirectoryGroupAttributes) {
		return nil, false
	}
	return o.DirectoryGroupAttributes, true
}

// HasDirectoryGroupAttributes returns a boolean if a field has been set.
func (o *DirectoryGroup) HasDirectoryGroupAttributes() bool {
	if o != nil && !IsNil(o.DirectoryGroupAttributes) {
		return true
	}

	return false
}

// SetDirectoryGroupAttributes gets a reference to the given map[string]string and assigns it to the DirectoryGroupAttributes field.
func (o *DirectoryGroup) SetDirectoryGroupAttributes(v map[string]string) {
	o.DirectoryGroupAttributes = &v
}

func (o DirectoryGroup) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DirectoryGroup) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.DirectoryGroupId) {
		toSerialize["directory_group_id"] = o.DirectoryGroupId
	}
	if !IsNil(o.DirectoryGroupOrganizationId) {
		toSerialize["directory_group_organization_id"] = o.DirectoryGroupOrganizationId
	}
	if !IsNil(o.DirectoryGroupSiteId) {
		toSerialize["directory_group_site_id"] = o.DirectoryGroupSiteId
	}
	if !IsNil(o.DirectoryGroupSourceId) {
		toSerialize["directory_group_source_id"] = o.DirectoryGroupSourceId
	}
	if !IsNil(o.DirectoryGroupCreatedAt) {
		toSerialize["directory_group_created_at"] = o.DirectoryGroupCreatedAt
	}
	if !IsNil(o.DirectoryGroupUpdatedAt) {
		toSerialize["directory_group_updated_at"] = o.DirectoryGroupUpdatedAt
	}
	if !IsNil(o.DirectoryGroupGroupId) {
		toSerialize["directory_group_group_id"] = o.DirectoryGroupGroupId
	}
	if !IsNil(o.DirectoryGroupUserCount) {
		toSerialize["directory_group_user_count"] = o.DirectoryGroupUserCount
	}
	if !IsNil(o.DirectoryGroupName) {
		toSerialize["directory_group_name"] = o.DirectoryGroupName
	}
	if !IsNil(o.DirectoryGroupDisplayName) {
		toSerialize["directory_group_display_name"] = o.DirectoryGroupDisplayName
	}
	if !IsNil(o.DirectoryGroupDescription) {
		toSerialize["directory_group_description"] = o.DirectoryGroupDescription
	}
	if !IsNil(o.DirectoryGroupEmail) {
		toSerialize["directory_group_email"] = o.DirectoryGroupEmail
	}
	if !IsNil(o.DirectoryGroupEmailNormalized) {
		toSerialize["directory_group_email_normalized"] = o.DirectoryGroupEmailNormalized
	}
	if !IsNil(o.DirectoryGroupAttributes) {
		toSerialize["directory_group_attributes"] = o.DirectoryGroupAttributes
	}
	return toSerialize, nil
}

func (o *DirectoryGroup) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDirectoryGroup := _DirectoryGroup{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDirectoryGroup)

	if err != nil {
		return err
	}

	*o = DirectoryGroup(varDirectoryGroup)

	return err
}

type NullableDirectoryGroup struct {
	value *DirectoryGroup
	isSet bool
}

func (v NullableDirectoryGroup) Get() *DirectoryGroup {
	return v.value
}

func (v *NullableDirectoryGroup) Set(val *DirectoryGroup) {
	v.value = val
	v.isSet = true
}

func (v NullableDirectoryGroup) IsSet() bool {
	return v.isSet
}

func (v *NullableDirectoryGroup) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDirectoryGroup(val *DirectoryGroup) *NullableDirectoryGroup {
	return &NullableDirectoryGroup{value: val, isSet: true}
}

func (v NullableDirectoryGroup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDirectoryGroup) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
