/*
runZero API

runZero API. API use is rate limited, you can make as many calls per day as you have licensed assets.

API version: 4.0.250826.0
Contact: support@runzero.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package runzero

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the AzureClientSecretCredentialFields type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AzureClientSecretCredentialFields{}

// AzureClientSecretCredentialFields struct for AzureClientSecretCredentialFields
type AzureClientSecretCredentialFields struct {
	ClientId          string  `json:"client_id"`
	ClientSecret      string  `json:"client_secret"`
	TenantId          string  `json:"tenant_id"`
	Environment       string  `json:"environment"`
	MultiSubscription *string `json:"multi_subscription,omitempty"`
	SubscriptionId    *string `json:"subscription_id,omitempty"`
}

type _AzureClientSecretCredentialFields AzureClientSecretCredentialFields

// NewAzureClientSecretCredentialFields instantiates a new AzureClientSecretCredentialFields object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAzureClientSecretCredentialFields(clientId string, clientSecret string, tenantId string, environment string) *AzureClientSecretCredentialFields {
	this := AzureClientSecretCredentialFields{}
	this.ClientId = clientId
	this.ClientSecret = clientSecret
	this.TenantId = tenantId
	this.Environment = environment
	return &this
}

// NewAzureClientSecretCredentialFieldsWithDefaults instantiates a new AzureClientSecretCredentialFields object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAzureClientSecretCredentialFieldsWithDefaults() *AzureClientSecretCredentialFields {
	this := AzureClientSecretCredentialFields{}
	return &this
}

// GetClientId returns the ClientId field value
func (o *AzureClientSecretCredentialFields) GetClientId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value
// and a boolean to check if the value has been set.
func (o *AzureClientSecretCredentialFields) GetClientIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientId, true
}

// SetClientId sets field value
func (o *AzureClientSecretCredentialFields) SetClientId(v string) {
	o.ClientId = v
}

// GetClientSecret returns the ClientSecret field value
func (o *AzureClientSecretCredentialFields) GetClientSecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientSecret
}

// GetClientSecretOk returns a tuple with the ClientSecret field value
// and a boolean to check if the value has been set.
func (o *AzureClientSecretCredentialFields) GetClientSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientSecret, true
}

// SetClientSecret sets field value
func (o *AzureClientSecretCredentialFields) SetClientSecret(v string) {
	o.ClientSecret = v
}

// GetTenantId returns the TenantId field value
func (o *AzureClientSecretCredentialFields) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *AzureClientSecretCredentialFields) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *AzureClientSecretCredentialFields) SetTenantId(v string) {
	o.TenantId = v
}

// GetEnvironment returns the Environment field value
func (o *AzureClientSecretCredentialFields) GetEnvironment() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Environment
}

// GetEnvironmentOk returns a tuple with the Environment field value
// and a boolean to check if the value has been set.
func (o *AzureClientSecretCredentialFields) GetEnvironmentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Environment, true
}

// SetEnvironment sets field value
func (o *AzureClientSecretCredentialFields) SetEnvironment(v string) {
	o.Environment = v
}

// GetMultiSubscription returns the MultiSubscription field value if set, zero value otherwise.
func (o *AzureClientSecretCredentialFields) GetMultiSubscription() string {
	if o == nil || IsNil(o.MultiSubscription) {
		var ret string
		return ret
	}
	return *o.MultiSubscription
}

// GetMultiSubscriptionOk returns a tuple with the MultiSubscription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AzureClientSecretCredentialFields) GetMultiSubscriptionOk() (*string, bool) {
	if o == nil || IsNil(o.MultiSubscription) {
		return nil, false
	}
	return o.MultiSubscription, true
}

// HasMultiSubscription returns a boolean if a field has been set.
func (o *AzureClientSecretCredentialFields) HasMultiSubscription() bool {
	if o != nil && !IsNil(o.MultiSubscription) {
		return true
	}

	return false
}

// SetMultiSubscription gets a reference to the given string and assigns it to the MultiSubscription field.
func (o *AzureClientSecretCredentialFields) SetMultiSubscription(v string) {
	o.MultiSubscription = &v
}

// GetSubscriptionId returns the SubscriptionId field value if set, zero value otherwise.
func (o *AzureClientSecretCredentialFields) GetSubscriptionId() string {
	if o == nil || IsNil(o.SubscriptionId) {
		var ret string
		return ret
	}
	return *o.SubscriptionId
}

// GetSubscriptionIdOk returns a tuple with the SubscriptionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AzureClientSecretCredentialFields) GetSubscriptionIdOk() (*string, bool) {
	if o == nil || IsNil(o.SubscriptionId) {
		return nil, false
	}
	return o.SubscriptionId, true
}

// HasSubscriptionId returns a boolean if a field has been set.
func (o *AzureClientSecretCredentialFields) HasSubscriptionId() bool {
	if o != nil && !IsNil(o.SubscriptionId) {
		return true
	}

	return false
}

// SetSubscriptionId gets a reference to the given string and assigns it to the SubscriptionId field.
func (o *AzureClientSecretCredentialFields) SetSubscriptionId(v string) {
	o.SubscriptionId = &v
}

func (o AzureClientSecretCredentialFields) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AzureClientSecretCredentialFields) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["client_id"] = o.ClientId
	toSerialize["client_secret"] = o.ClientSecret
	toSerialize["tenant_id"] = o.TenantId
	toSerialize["environment"] = o.Environment
	if !IsNil(o.MultiSubscription) {
		toSerialize["multi_subscription"] = o.MultiSubscription
	}
	if !IsNil(o.SubscriptionId) {
		toSerialize["subscription_id"] = o.SubscriptionId
	}
	return toSerialize, nil
}

func (o *AzureClientSecretCredentialFields) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"client_id",
		"client_secret",
		"tenant_id",
		"environment",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAzureClientSecretCredentialFields := _AzureClientSecretCredentialFields{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAzureClientSecretCredentialFields)

	if err != nil {
		return err
	}

	*o = AzureClientSecretCredentialFields(varAzureClientSecretCredentialFields)

	return err
}

type NullableAzureClientSecretCredentialFields struct {
	value *AzureClientSecretCredentialFields
	isSet bool
}

func (v NullableAzureClientSecretCredentialFields) Get() *AzureClientSecretCredentialFields {
	return v.value
}

func (v *NullableAzureClientSecretCredentialFields) Set(val *AzureClientSecretCredentialFields) {
	v.value = val
	v.isSet = true
}

func (v NullableAzureClientSecretCredentialFields) IsSet() bool {
	return v.isSet
}

func (v *NullableAzureClientSecretCredentialFields) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAzureClientSecretCredentialFields(val *AzureClientSecretCredentialFields) *NullableAzureClientSecretCredentialFields {
	return &NullableAzureClientSecretCredentialFields{value: val, isSet: true}
}

func (v NullableAzureClientSecretCredentialFields) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAzureClientSecretCredentialFields) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
