/*
runZero API

runZero API. API use is rate limited, you can make as many calls per day as you have licensed assets.

API version: 4.0.250826.0
Contact: support@runzero.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CrowdstrikeCredentialFields type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CrowdstrikeCredentialFields{}

// CrowdstrikeCredentialFields struct for CrowdstrikeCredentialFields
type CrowdstrikeCredentialFields struct {
	ClientId string `json:"client_id"`
	ClientSecret string `json:"client_secret"`
	ApiUrl string `json:"api_url"`
}

type _CrowdstrikeCredentialFields CrowdstrikeCredentialFields

// NewCrowdstrikeCredentialFields instantiates a new CrowdstrikeCredentialFields object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCrowdstrikeCredentialFields(clientId string, clientSecret string, apiUrl string) *CrowdstrikeCredentialFields {
	this := CrowdstrikeCredentialFields{}
	this.ClientId = clientId
	this.ClientSecret = clientSecret
	this.ApiUrl = apiUrl
	return &this
}

// NewCrowdstrikeCredentialFieldsWithDefaults instantiates a new CrowdstrikeCredentialFields object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCrowdstrikeCredentialFieldsWithDefaults() *CrowdstrikeCredentialFields {
	this := CrowdstrikeCredentialFields{}
	return &this
}

// GetClientId returns the ClientId field value
func (o *CrowdstrikeCredentialFields) GetClientId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value
// and a boolean to check if the value has been set.
func (o *CrowdstrikeCredentialFields) GetClientIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientId, true
}

// SetClientId sets field value
func (o *CrowdstrikeCredentialFields) SetClientId(v string) {
	o.ClientId = v
}

// GetClientSecret returns the ClientSecret field value
func (o *CrowdstrikeCredentialFields) GetClientSecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientSecret
}

// GetClientSecretOk returns a tuple with the ClientSecret field value
// and a boolean to check if the value has been set.
func (o *CrowdstrikeCredentialFields) GetClientSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientSecret, true
}

// SetClientSecret sets field value
func (o *CrowdstrikeCredentialFields) SetClientSecret(v string) {
	o.ClientSecret = v
}

// GetApiUrl returns the ApiUrl field value
func (o *CrowdstrikeCredentialFields) GetApiUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApiUrl
}

// GetApiUrlOk returns a tuple with the ApiUrl field value
// and a boolean to check if the value has been set.
func (o *CrowdstrikeCredentialFields) GetApiUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApiUrl, true
}

// SetApiUrl sets field value
func (o *CrowdstrikeCredentialFields) SetApiUrl(v string) {
	o.ApiUrl = v
}

func (o CrowdstrikeCredentialFields) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CrowdstrikeCredentialFields) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["client_id"] = o.ClientId
	toSerialize["client_secret"] = o.ClientSecret
	toSerialize["api_url"] = o.ApiUrl
	return toSerialize, nil
}

func (o *CrowdstrikeCredentialFields) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"client_id",
		"client_secret",
		"api_url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCrowdstrikeCredentialFields := _CrowdstrikeCredentialFields{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCrowdstrikeCredentialFields)

	if err != nil {
		return err
	}

	*o = CrowdstrikeCredentialFields(varCrowdstrikeCredentialFields)

	return err
}

type NullableCrowdstrikeCredentialFields struct {
	value *CrowdstrikeCredentialFields
	isSet bool
}

func (v NullableCrowdstrikeCredentialFields) Get() *CrowdstrikeCredentialFields {
	return v.value
}

func (v *NullableCrowdstrikeCredentialFields) Set(val *CrowdstrikeCredentialFields) {
	v.value = val
	v.isSet = true
}

func (v NullableCrowdstrikeCredentialFields) IsSet() bool {
	return v.isSet
}

func (v *NullableCrowdstrikeCredentialFields) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCrowdstrikeCredentialFields(val *CrowdstrikeCredentialFields) *NullableCrowdstrikeCredentialFields {
	return &NullableCrowdstrikeCredentialFields{value: val, isSet: true}
}

func (v NullableCrowdstrikeCredentialFields) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCrowdstrikeCredentialFields) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


