/*
runZero API

runZero API. API use is rate limited, you can make as many calls per day as you have licensed assets.

API version: 4.0.250826.0
Contact: support@runzero.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package runzero

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ShodanCredentialFields type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ShodanCredentialFields{}

// ShodanCredentialFields struct for ShodanCredentialFields
type ShodanCredentialFields struct {
	ApiKey string `json:"api_key"`
}

type _ShodanCredentialFields ShodanCredentialFields

// NewShodanCredentialFields instantiates a new ShodanCredentialFields object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewShodanCredentialFields(apiKey string) *ShodanCredentialFields {
	this := ShodanCredentialFields{}
	this.ApiKey = apiKey
	return &this
}

// NewShodanCredentialFieldsWithDefaults instantiates a new ShodanCredentialFields object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewShodanCredentialFieldsWithDefaults() *ShodanCredentialFields {
	this := ShodanCredentialFields{}
	return &this
}

// GetApiKey returns the ApiKey field value
func (o *ShodanCredentialFields) GetApiKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApiKey
}

// GetApiKeyOk returns a tuple with the ApiKey field value
// and a boolean to check if the value has been set.
func (o *ShodanCredentialFields) GetApiKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApiKey, true
}

// SetApiKey sets field value
func (o *ShodanCredentialFields) SetApiKey(v string) {
	o.ApiKey = v
}

func (o ShodanCredentialFields) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ShodanCredentialFields) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["api_key"] = o.ApiKey
	return toSerialize, nil
}

func (o *ShodanCredentialFields) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"api_key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varShodanCredentialFields := _ShodanCredentialFields{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varShodanCredentialFields)

	if err != nil {
		return err
	}

	*o = ShodanCredentialFields(varShodanCredentialFields)

	return err
}

type NullableShodanCredentialFields struct {
	value *ShodanCredentialFields
	isSet bool
}

func (v NullableShodanCredentialFields) Get() *ShodanCredentialFields {
	return v.value
}

func (v *NullableShodanCredentialFields) Set(val *ShodanCredentialFields) {
	v.value = val
	v.isSet = true
}

func (v NullableShodanCredentialFields) IsSet() bool {
	return v.isSet
}

func (v *NullableShodanCredentialFields) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableShodanCredentialFields(val *ShodanCredentialFields) *NullableShodanCredentialFields {
	return &NullableShodanCredentialFields{value: val, isSet: true}
}

func (v NullableShodanCredentialFields) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableShodanCredentialFields) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
