/*
runZero API

runZero API. API use is rate limited, you can make as many calls per day as you have licensed assets.

API version: 4.0.250826.0
Contact: support@runzero.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package runzero

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the MirakiCredentialFields type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MirakiCredentialFields{}

// MirakiCredentialFields struct for MirakiCredentialFields
type MirakiCredentialFields struct {
	ApiUrl string `json:"api_url"`
	ApiKey string `json:"api_key"`
}

type _MirakiCredentialFields MirakiCredentialFields

// NewMirakiCredentialFields instantiates a new MirakiCredentialFields object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMirakiCredentialFields(apiUrl string, apiKey string) *MirakiCredentialFields {
	this := MirakiCredentialFields{}
	this.ApiUrl = apiUrl
	this.ApiKey = apiKey
	return &this
}

// NewMirakiCredentialFieldsWithDefaults instantiates a new MirakiCredentialFields object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMirakiCredentialFieldsWithDefaults() *MirakiCredentialFields {
	this := MirakiCredentialFields{}
	return &this
}

// GetApiUrl returns the ApiUrl field value
func (o *MirakiCredentialFields) GetApiUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApiUrl
}

// GetApiUrlOk returns a tuple with the ApiUrl field value
// and a boolean to check if the value has been set.
func (o *MirakiCredentialFields) GetApiUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApiUrl, true
}

// SetApiUrl sets field value
func (o *MirakiCredentialFields) SetApiUrl(v string) {
	o.ApiUrl = v
}

// GetApiKey returns the ApiKey field value
func (o *MirakiCredentialFields) GetApiKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApiKey
}

// GetApiKeyOk returns a tuple with the ApiKey field value
// and a boolean to check if the value has been set.
func (o *MirakiCredentialFields) GetApiKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApiKey, true
}

// SetApiKey sets field value
func (o *MirakiCredentialFields) SetApiKey(v string) {
	o.ApiKey = v
}

func (o MirakiCredentialFields) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MirakiCredentialFields) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["api_url"] = o.ApiUrl
	toSerialize["api_key"] = o.ApiKey
	return toSerialize, nil
}

func (o *MirakiCredentialFields) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"api_url",
		"api_key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMirakiCredentialFields := _MirakiCredentialFields{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMirakiCredentialFields)

	if err != nil {
		return err
	}

	*o = MirakiCredentialFields(varMirakiCredentialFields)

	return err
}

type NullableMirakiCredentialFields struct {
	value *MirakiCredentialFields
	isSet bool
}

func (v NullableMirakiCredentialFields) Get() *MirakiCredentialFields {
	return v.value
}

func (v *NullableMirakiCredentialFields) Set(val *MirakiCredentialFields) {
	v.value = val
	v.isSet = true
}

func (v NullableMirakiCredentialFields) IsSet() bool {
	return v.isSet
}

func (v *NullableMirakiCredentialFields) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMirakiCredentialFields(val *MirakiCredentialFields) *NullableMirakiCredentialFields {
	return &NullableMirakiCredentialFields{value: val, isSet: true}
}

func (v NullableMirakiCredentialFields) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMirakiCredentialFields) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
