/*
runZero API

runZero API. API use is rate limited, you can make as many calls per day as you have licensed assets.

API version: 4.0.250826.0
Contact: support@runzero.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AssetIDs type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssetIDs{}

// AssetIDs struct for AssetIDs
type AssetIDs struct {
	AssetIds []string `json:"asset_ids"`
}

type _AssetIDs AssetIDs

// NewAssetIDs instantiates a new AssetIDs object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssetIDs(assetIds []string) *AssetIDs {
	this := AssetIDs{}
	this.AssetIds = assetIds
	return &this
}

// NewAssetIDsWithDefaults instantiates a new AssetIDs object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssetIDsWithDefaults() *AssetIDs {
	this := AssetIDs{}
	return &this
}

// GetAssetIds returns the AssetIds field value
func (o *AssetIDs) GetAssetIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.AssetIds
}

// GetAssetIdsOk returns a tuple with the AssetIds field value
// and a boolean to check if the value has been set.
func (o *AssetIDs) GetAssetIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AssetIds, true
}

// SetAssetIds sets field value
func (o *AssetIDs) SetAssetIds(v []string) {
	o.AssetIds = v
}

func (o AssetIDs) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssetIDs) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["asset_ids"] = o.AssetIds
	return toSerialize, nil
}

func (o *AssetIDs) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"asset_ids",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAssetIDs := _AssetIDs{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAssetIDs)

	if err != nil {
		return err
	}

	*o = AssetIDs(varAssetIDs)

	return err
}

type NullableAssetIDs struct {
	value *AssetIDs
	isSet bool
}

func (v NullableAssetIDs) Get() *AssetIDs {
	return v.value
}

func (v *NullableAssetIDs) Set(val *AssetIDs) {
	v.value = val
	v.isSet = true
}

func (v NullableAssetIDs) IsSet() bool {
	return v.isSet
}

func (v *NullableAssetIDs) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssetIDs(val *AssetIDs) *NullableAssetIDs {
	return &NullableAssetIDs{value: val, isSet: true}
}

func (v NullableAssetIDs) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssetIDs) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


