/*
runZero API

runZero API. API use is rate limited, you can make as many calls per day as you have licensed assets.

API version: 4.0.250826.0
Contact: support@runzero.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AssetCriticality type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssetCriticality{}

// AssetCriticality struct for AssetCriticality
type AssetCriticality struct {
	Criticality string `json:"criticality"`
}

type _AssetCriticality AssetCriticality

// NewAssetCriticality instantiates a new AssetCriticality object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssetCriticality(criticality string) *AssetCriticality {
	this := AssetCriticality{}
	this.Criticality = criticality
	return &this
}

// NewAssetCriticalityWithDefaults instantiates a new AssetCriticality object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssetCriticalityWithDefaults() *AssetCriticality {
	this := AssetCriticality{}
	return &this
}

// GetCriticality returns the Criticality field value
func (o *AssetCriticality) GetCriticality() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Criticality
}

// GetCriticalityOk returns a tuple with the Criticality field value
// and a boolean to check if the value has been set.
func (o *AssetCriticality) GetCriticalityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Criticality, true
}

// SetCriticality sets field value
func (o *AssetCriticality) SetCriticality(v string) {
	o.Criticality = v
}

func (o AssetCriticality) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssetCriticality) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["criticality"] = o.Criticality
	return toSerialize, nil
}

func (o *AssetCriticality) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"criticality",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAssetCriticality := _AssetCriticality{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAssetCriticality)

	if err != nil {
		return err
	}

	*o = AssetCriticality(varAssetCriticality)

	return err
}

type NullableAssetCriticality struct {
	value *AssetCriticality
	isSet bool
}

func (v NullableAssetCriticality) Get() *AssetCriticality {
	return v.value
}

func (v *NullableAssetCriticality) Set(val *AssetCriticality) {
	v.value = val
	v.isSet = true
}

func (v NullableAssetCriticality) IsSet() bool {
	return v.isSet
}

func (v *NullableAssetCriticality) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssetCriticality(val *AssetCriticality) *NullableAssetCriticality {
	return &NullableAssetCriticality{value: val, isSet: true}
}

func (v NullableAssetCriticality) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssetCriticality) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


