/*
runZero API

runZero API. API use is rate limited, you can make as many calls per day as you have licensed assets.

API version: 4.0.250826.0
Contact: support@runzero.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Group type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Group{}

// Group struct for Group
type Group struct {
	Id string `json:"id"`
	Description *string `json:"description,omitempty"`
	Name *string `json:"name,omitempty"`
	RoleSummary *string `json:"role_summary,omitempty"`
	UserCount *int64 `json:"user_count,omitempty"`
	CreatedByEmail *string `json:"created_by_email,omitempty"`
	CreatedAt *int64 `json:"created_at,omitempty"`
	UpdatedAt *int64 `json:"updated_at,omitempty"`
	ExpiresAt *int64 `json:"expires_at,omitempty"`
	OrgDefaultRole *string `json:"org_default_role,omitempty"`
	OrgRoles map[string]interface{} `json:"org_roles,omitempty"`
}

type _Group Group

// NewGroup instantiates a new Group object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroup(id string) *Group {
	this := Group{}
	this.Id = id
	return &this
}

// NewGroupWithDefaults instantiates a new Group object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupWithDefaults() *Group {
	this := Group{}
	return &this
}

// GetId returns the Id field value
func (o *Group) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Group) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Group) SetId(v string) {
	o.Id = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *Group) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Group) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *Group) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *Group) SetDescription(v string) {
	o.Description = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Group) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Group) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Group) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Group) SetName(v string) {
	o.Name = &v
}

// GetRoleSummary returns the RoleSummary field value if set, zero value otherwise.
func (o *Group) GetRoleSummary() string {
	if o == nil || IsNil(o.RoleSummary) {
		var ret string
		return ret
	}
	return *o.RoleSummary
}

// GetRoleSummaryOk returns a tuple with the RoleSummary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Group) GetRoleSummaryOk() (*string, bool) {
	if o == nil || IsNil(o.RoleSummary) {
		return nil, false
	}
	return o.RoleSummary, true
}

// HasRoleSummary returns a boolean if a field has been set.
func (o *Group) HasRoleSummary() bool {
	if o != nil && !IsNil(o.RoleSummary) {
		return true
	}

	return false
}

// SetRoleSummary gets a reference to the given string and assigns it to the RoleSummary field.
func (o *Group) SetRoleSummary(v string) {
	o.RoleSummary = &v
}

// GetUserCount returns the UserCount field value if set, zero value otherwise.
func (o *Group) GetUserCount() int64 {
	if o == nil || IsNil(o.UserCount) {
		var ret int64
		return ret
	}
	return *o.UserCount
}

// GetUserCountOk returns a tuple with the UserCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Group) GetUserCountOk() (*int64, bool) {
	if o == nil || IsNil(o.UserCount) {
		return nil, false
	}
	return o.UserCount, true
}

// HasUserCount returns a boolean if a field has been set.
func (o *Group) HasUserCount() bool {
	if o != nil && !IsNil(o.UserCount) {
		return true
	}

	return false
}

// SetUserCount gets a reference to the given int64 and assigns it to the UserCount field.
func (o *Group) SetUserCount(v int64) {
	o.UserCount = &v
}

// GetCreatedByEmail returns the CreatedByEmail field value if set, zero value otherwise.
func (o *Group) GetCreatedByEmail() string {
	if o == nil || IsNil(o.CreatedByEmail) {
		var ret string
		return ret
	}
	return *o.CreatedByEmail
}

// GetCreatedByEmailOk returns a tuple with the CreatedByEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Group) GetCreatedByEmailOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedByEmail) {
		return nil, false
	}
	return o.CreatedByEmail, true
}

// HasCreatedByEmail returns a boolean if a field has been set.
func (o *Group) HasCreatedByEmail() bool {
	if o != nil && !IsNil(o.CreatedByEmail) {
		return true
	}

	return false
}

// SetCreatedByEmail gets a reference to the given string and assigns it to the CreatedByEmail field.
func (o *Group) SetCreatedByEmail(v string) {
	o.CreatedByEmail = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *Group) GetCreatedAt() int64 {
	if o == nil || IsNil(o.CreatedAt) {
		var ret int64
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Group) GetCreatedAtOk() (*int64, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Group) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given int64 and assigns it to the CreatedAt field.
func (o *Group) SetCreatedAt(v int64) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *Group) GetUpdatedAt() int64 {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret int64
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Group) GetUpdatedAtOk() (*int64, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *Group) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given int64 and assigns it to the UpdatedAt field.
func (o *Group) SetUpdatedAt(v int64) {
	o.UpdatedAt = &v
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise.
func (o *Group) GetExpiresAt() int64 {
	if o == nil || IsNil(o.ExpiresAt) {
		var ret int64
		return ret
	}
	return *o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Group) GetExpiresAtOk() (*int64, bool) {
	if o == nil || IsNil(o.ExpiresAt) {
		return nil, false
	}
	return o.ExpiresAt, true
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *Group) HasExpiresAt() bool {
	if o != nil && !IsNil(o.ExpiresAt) {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given int64 and assigns it to the ExpiresAt field.
func (o *Group) SetExpiresAt(v int64) {
	o.ExpiresAt = &v
}

// GetOrgDefaultRole returns the OrgDefaultRole field value if set, zero value otherwise.
func (o *Group) GetOrgDefaultRole() string {
	if o == nil || IsNil(o.OrgDefaultRole) {
		var ret string
		return ret
	}
	return *o.OrgDefaultRole
}

// GetOrgDefaultRoleOk returns a tuple with the OrgDefaultRole field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Group) GetOrgDefaultRoleOk() (*string, bool) {
	if o == nil || IsNil(o.OrgDefaultRole) {
		return nil, false
	}
	return o.OrgDefaultRole, true
}

// HasOrgDefaultRole returns a boolean if a field has been set.
func (o *Group) HasOrgDefaultRole() bool {
	if o != nil && !IsNil(o.OrgDefaultRole) {
		return true
	}

	return false
}

// SetOrgDefaultRole gets a reference to the given string and assigns it to the OrgDefaultRole field.
func (o *Group) SetOrgDefaultRole(v string) {
	o.OrgDefaultRole = &v
}

// GetOrgRoles returns the OrgRoles field value if set, zero value otherwise.
func (o *Group) GetOrgRoles() map[string]interface{} {
	if o == nil || IsNil(o.OrgRoles) {
		var ret map[string]interface{}
		return ret
	}
	return o.OrgRoles
}

// GetOrgRolesOk returns a tuple with the OrgRoles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Group) GetOrgRolesOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.OrgRoles) {
		return map[string]interface{}{}, false
	}
	return o.OrgRoles, true
}

// HasOrgRoles returns a boolean if a field has been set.
func (o *Group) HasOrgRoles() bool {
	if o != nil && !IsNil(o.OrgRoles) {
		return true
	}

	return false
}

// SetOrgRoles gets a reference to the given map[string]interface{} and assigns it to the OrgRoles field.
func (o *Group) SetOrgRoles(v map[string]interface{}) {
	o.OrgRoles = v
}

func (o Group) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Group) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.RoleSummary) {
		toSerialize["role_summary"] = o.RoleSummary
	}
	if !IsNil(o.UserCount) {
		toSerialize["user_count"] = o.UserCount
	}
	if !IsNil(o.CreatedByEmail) {
		toSerialize["created_by_email"] = o.CreatedByEmail
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.ExpiresAt) {
		toSerialize["expires_at"] = o.ExpiresAt
	}
	if !IsNil(o.OrgDefaultRole) {
		toSerialize["org_default_role"] = o.OrgDefaultRole
	}
	if !IsNil(o.OrgRoles) {
		toSerialize["org_roles"] = o.OrgRoles
	}
	return toSerialize, nil
}

func (o *Group) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGroup := _Group{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGroup)

	if err != nil {
		return err
	}

	*o = Group(varGroup)

	return err
}

type NullableGroup struct {
	value *Group
	isSet bool
}

func (v NullableGroup) Get() *Group {
	return v.value
}

func (v *NullableGroup) Set(val *Group) {
	v.value = val
	v.isSet = true
}

func (v NullableGroup) IsSet() bool {
	return v.isSet
}

func (v *NullableGroup) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroup(val *Group) *NullableGroup {
	return &NullableGroup{value: val, isSet: true}
}

func (v NullableGroup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroup) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


