/*
runZero API

runZero API. API use is rate limited, you can make as many calls per day as you have licensed assets.

API version: 4.0.250826.0
Contact: support@runzero.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GroupMapping type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupMapping{}

// GroupMapping struct for GroupMapping
type GroupMapping struct {
	Id string `json:"id"`
	GroupId string `json:"group_id"`
	GroupName *string `json:"group_name,omitempty"`
	SsoAttribute string `json:"sso_attribute"`
	SsoValue string `json:"sso_value"`
	Description *string `json:"description,omitempty"`
	CreatedByEmail *string `json:"created_by_email,omitempty"`
	CreatedAt *int64 `json:"created_at,omitempty"`
	UpdatedAt *int64 `json:"updated_at,omitempty"`
}

type _GroupMapping GroupMapping

// NewGroupMapping instantiates a new GroupMapping object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupMapping(id string, groupId string, ssoAttribute string, ssoValue string) *GroupMapping {
	this := GroupMapping{}
	this.Id = id
	this.GroupId = groupId
	this.SsoAttribute = ssoAttribute
	this.SsoValue = ssoValue
	return &this
}

// NewGroupMappingWithDefaults instantiates a new GroupMapping object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupMappingWithDefaults() *GroupMapping {
	this := GroupMapping{}
	return &this
}

// GetId returns the Id field value
func (o *GroupMapping) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GroupMapping) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GroupMapping) SetId(v string) {
	o.Id = v
}

// GetGroupId returns the GroupId field value
func (o *GroupMapping) GetGroupId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GroupId
}

// GetGroupIdOk returns a tuple with the GroupId field value
// and a boolean to check if the value has been set.
func (o *GroupMapping) GetGroupIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GroupId, true
}

// SetGroupId sets field value
func (o *GroupMapping) SetGroupId(v string) {
	o.GroupId = v
}

// GetGroupName returns the GroupName field value if set, zero value otherwise.
func (o *GroupMapping) GetGroupName() string {
	if o == nil || IsNil(o.GroupName) {
		var ret string
		return ret
	}
	return *o.GroupName
}

// GetGroupNameOk returns a tuple with the GroupName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupMapping) GetGroupNameOk() (*string, bool) {
	if o == nil || IsNil(o.GroupName) {
		return nil, false
	}
	return o.GroupName, true
}

// HasGroupName returns a boolean if a field has been set.
func (o *GroupMapping) HasGroupName() bool {
	if o != nil && !IsNil(o.GroupName) {
		return true
	}

	return false
}

// SetGroupName gets a reference to the given string and assigns it to the GroupName field.
func (o *GroupMapping) SetGroupName(v string) {
	o.GroupName = &v
}

// GetSsoAttribute returns the SsoAttribute field value
func (o *GroupMapping) GetSsoAttribute() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SsoAttribute
}

// GetSsoAttributeOk returns a tuple with the SsoAttribute field value
// and a boolean to check if the value has been set.
func (o *GroupMapping) GetSsoAttributeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SsoAttribute, true
}

// SetSsoAttribute sets field value
func (o *GroupMapping) SetSsoAttribute(v string) {
	o.SsoAttribute = v
}

// GetSsoValue returns the SsoValue field value
func (o *GroupMapping) GetSsoValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SsoValue
}

// GetSsoValueOk returns a tuple with the SsoValue field value
// and a boolean to check if the value has been set.
func (o *GroupMapping) GetSsoValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SsoValue, true
}

// SetSsoValue sets field value
func (o *GroupMapping) SetSsoValue(v string) {
	o.SsoValue = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *GroupMapping) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupMapping) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *GroupMapping) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *GroupMapping) SetDescription(v string) {
	o.Description = &v
}

// GetCreatedByEmail returns the CreatedByEmail field value if set, zero value otherwise.
func (o *GroupMapping) GetCreatedByEmail() string {
	if o == nil || IsNil(o.CreatedByEmail) {
		var ret string
		return ret
	}
	return *o.CreatedByEmail
}

// GetCreatedByEmailOk returns a tuple with the CreatedByEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupMapping) GetCreatedByEmailOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedByEmail) {
		return nil, false
	}
	return o.CreatedByEmail, true
}

// HasCreatedByEmail returns a boolean if a field has been set.
func (o *GroupMapping) HasCreatedByEmail() bool {
	if o != nil && !IsNil(o.CreatedByEmail) {
		return true
	}

	return false
}

// SetCreatedByEmail gets a reference to the given string and assigns it to the CreatedByEmail field.
func (o *GroupMapping) SetCreatedByEmail(v string) {
	o.CreatedByEmail = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *GroupMapping) GetCreatedAt() int64 {
	if o == nil || IsNil(o.CreatedAt) {
		var ret int64
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupMapping) GetCreatedAtOk() (*int64, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *GroupMapping) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given int64 and assigns it to the CreatedAt field.
func (o *GroupMapping) SetCreatedAt(v int64) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *GroupMapping) GetUpdatedAt() int64 {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret int64
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupMapping) GetUpdatedAtOk() (*int64, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *GroupMapping) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given int64 and assigns it to the UpdatedAt field.
func (o *GroupMapping) SetUpdatedAt(v int64) {
	o.UpdatedAt = &v
}

func (o GroupMapping) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupMapping) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["group_id"] = o.GroupId
	if !IsNil(o.GroupName) {
		toSerialize["group_name"] = o.GroupName
	}
	toSerialize["sso_attribute"] = o.SsoAttribute
	toSerialize["sso_value"] = o.SsoValue
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.CreatedByEmail) {
		toSerialize["created_by_email"] = o.CreatedByEmail
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	return toSerialize, nil
}

func (o *GroupMapping) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"group_id",
		"sso_attribute",
		"sso_value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGroupMapping := _GroupMapping{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGroupMapping)

	if err != nil {
		return err
	}

	*o = GroupMapping(varGroupMapping)

	return err
}

type NullableGroupMapping struct {
	value *GroupMapping
	isSet bool
}

func (v NullableGroupMapping) Get() *GroupMapping {
	return v.value
}

func (v *NullableGroupMapping) Set(val *GroupMapping) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupMapping) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupMapping) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupMapping(val *GroupMapping) *NullableGroupMapping {
	return &NullableGroupMapping{value: val, isSet: true}
}

func (v NullableGroupMapping) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupMapping) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


