/*
runZero API

runZero API. API use is rate limited, you can make as many calls per day as you have licensed assets.

API version: 4.0.250826.0
Contact: support@runzero.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package runzero

import (
	"encoding/json"
	"fmt"

	"gopkg.in/validator.v2"
)

// ExportWirelessJSON200Response - struct for ExportWirelessJSON200Response
type ExportWirelessJSON200Response struct {
	ExportWirelessJSON200ResponseOneOf *ExportWirelessJSON200ResponseOneOf
	ArrayOfWireless                    *[]Wireless
}

// ExportWirelessJSON200ResponseOneOfAsExportWirelessJSON200Response is a convenience function that returns ExportWirelessJSON200ResponseOneOf wrapped in ExportWirelessJSON200Response
func ExportWirelessJSON200ResponseOneOfAsExportWirelessJSON200Response(v *ExportWirelessJSON200ResponseOneOf) ExportWirelessJSON200Response {
	return ExportWirelessJSON200Response{
		ExportWirelessJSON200ResponseOneOf: v,
	}
}

// []WirelessAsExportWirelessJSON200Response is a convenience function that returns []Wireless wrapped in ExportWirelessJSON200Response
func ArrayOfWirelessAsExportWirelessJSON200Response(v *[]Wireless) ExportWirelessJSON200Response {
	return ExportWirelessJSON200Response{
		ArrayOfWireless: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *ExportWirelessJSON200Response) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ExportWirelessJSON200ResponseOneOf
	err = newStrictDecoder(data).Decode(&dst.ExportWirelessJSON200ResponseOneOf)
	if err == nil {
		jsonExportWirelessJSON200ResponseOneOf, _ := json.Marshal(dst.ExportWirelessJSON200ResponseOneOf)
		if string(jsonExportWirelessJSON200ResponseOneOf) == "{}" { // empty struct
			dst.ExportWirelessJSON200ResponseOneOf = nil
		} else {
			if err = validator.Validate(dst.ExportWirelessJSON200ResponseOneOf); err != nil {
				dst.ExportWirelessJSON200ResponseOneOf = nil
			} else {
				match++
			}
		}
	} else {
		dst.ExportWirelessJSON200ResponseOneOf = nil
	}

	// try to unmarshal data into ArrayOfWireless
	err = newStrictDecoder(data).Decode(&dst.ArrayOfWireless)
	if err == nil {
		jsonArrayOfWireless, _ := json.Marshal(dst.ArrayOfWireless)
		if string(jsonArrayOfWireless) == "{}" { // empty struct
			dst.ArrayOfWireless = nil
		} else {
			if err = validator.Validate(dst.ArrayOfWireless); err != nil {
				dst.ArrayOfWireless = nil
			} else {
				match++
			}
		}
	} else {
		dst.ArrayOfWireless = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ExportWirelessJSON200ResponseOneOf = nil
		dst.ArrayOfWireless = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ExportWirelessJSON200Response)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(ExportWirelessJSON200Response)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ExportWirelessJSON200Response) MarshalJSON() ([]byte, error) {
	if src.ExportWirelessJSON200ResponseOneOf != nil {
		return json.Marshal(&src.ExportWirelessJSON200ResponseOneOf)
	}

	if src.ArrayOfWireless != nil {
		return json.Marshal(&src.ArrayOfWireless)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ExportWirelessJSON200Response) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.ExportWirelessJSON200ResponseOneOf != nil {
		return obj.ExportWirelessJSON200ResponseOneOf
	}

	if obj.ArrayOfWireless != nil {
		return obj.ArrayOfWireless
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj ExportWirelessJSON200Response) GetActualInstanceValue() interface{} {
	if obj.ExportWirelessJSON200ResponseOneOf != nil {
		return *obj.ExportWirelessJSON200ResponseOneOf
	}

	if obj.ArrayOfWireless != nil {
		return *obj.ArrayOfWireless
	}

	// all schemas are nil
	return nil
}

type NullableExportWirelessJSON200Response struct {
	value *ExportWirelessJSON200Response
	isSet bool
}

func (v NullableExportWirelessJSON200Response) Get() *ExportWirelessJSON200Response {
	return v.value
}

func (v *NullableExportWirelessJSON200Response) Set(val *ExportWirelessJSON200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableExportWirelessJSON200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableExportWirelessJSON200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExportWirelessJSON200Response(val *ExportWirelessJSON200Response) *NullableExportWirelessJSON200Response {
	return &NullableExportWirelessJSON200Response{value: val, isSet: true}
}

func (v NullableExportWirelessJSON200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExportWirelessJSON200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
