/*
runZero API

runZero API. API use is rate limited, you can make as many calls per day as you have licensed assets.

API version: 4.0.250826.0
Contact: support@runzero.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package runzero

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the Finding type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Finding{}

// Finding struct for Finding
type Finding struct {
	Id             string  `json:"id"`
	Category       *string `json:"category,omitempty"`
	OrganizationId string  `json:"organization_id"`
	// A runZero-assigned code for the finding.
	FindingCode *string `json:"finding_code,omitempty"`
	// The title of the finding.
	Name *string `json:"name,omitempty"`
	// Additional information about the finding.
	Description *string `json:"description,omitempty"`
	// Remediation information.
	Solution       *string       `json:"solution,omitempty"`
	Links          *FindingLinks `json:"links,omitempty"`
	CreatedAt      *int64        `json:"created_at,omitempty"`
	UpdatedAt      *int64        `json:"updated_at,omitempty"`
	LastDetectedAt *int64        `json:"last_detected_at,omitempty"`
	InstanceCount  *int64        `json:"instance_count,omitempty"`
	RiskRank       *string       `json:"risk_rank,omitempty"`
	// 0 = info, 4 = critical
	RiskRankValue *int32 `json:"risk_rank_value,omitempty"`
}

type _Finding Finding

// NewFinding instantiates a new Finding object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFinding(id string, organizationId string) *Finding {
	this := Finding{}
	this.Id = id
	this.OrganizationId = organizationId
	return &this
}

// NewFindingWithDefaults instantiates a new Finding object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFindingWithDefaults() *Finding {
	this := Finding{}
	return &this
}

// GetId returns the Id field value
func (o *Finding) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Finding) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Finding) SetId(v string) {
	o.Id = v
}

// GetCategory returns the Category field value if set, zero value otherwise.
func (o *Finding) GetCategory() string {
	if o == nil || IsNil(o.Category) {
		var ret string
		return ret
	}
	return *o.Category
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Finding) GetCategoryOk() (*string, bool) {
	if o == nil || IsNil(o.Category) {
		return nil, false
	}
	return o.Category, true
}

// HasCategory returns a boolean if a field has been set.
func (o *Finding) HasCategory() bool {
	if o != nil && !IsNil(o.Category) {
		return true
	}

	return false
}

// SetCategory gets a reference to the given string and assigns it to the Category field.
func (o *Finding) SetCategory(v string) {
	o.Category = &v
}

// GetOrganizationId returns the OrganizationId field value
func (o *Finding) GetOrganizationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value
// and a boolean to check if the value has been set.
func (o *Finding) GetOrganizationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrganizationId, true
}

// SetOrganizationId sets field value
func (o *Finding) SetOrganizationId(v string) {
	o.OrganizationId = v
}

// GetFindingCode returns the FindingCode field value if set, zero value otherwise.
func (o *Finding) GetFindingCode() string {
	if o == nil || IsNil(o.FindingCode) {
		var ret string
		return ret
	}
	return *o.FindingCode
}

// GetFindingCodeOk returns a tuple with the FindingCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Finding) GetFindingCodeOk() (*string, bool) {
	if o == nil || IsNil(o.FindingCode) {
		return nil, false
	}
	return o.FindingCode, true
}

// HasFindingCode returns a boolean if a field has been set.
func (o *Finding) HasFindingCode() bool {
	if o != nil && !IsNil(o.FindingCode) {
		return true
	}

	return false
}

// SetFindingCode gets a reference to the given string and assigns it to the FindingCode field.
func (o *Finding) SetFindingCode(v string) {
	o.FindingCode = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Finding) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Finding) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Finding) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Finding) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *Finding) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Finding) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *Finding) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *Finding) SetDescription(v string) {
	o.Description = &v
}

// GetSolution returns the Solution field value if set, zero value otherwise.
func (o *Finding) GetSolution() string {
	if o == nil || IsNil(o.Solution) {
		var ret string
		return ret
	}
	return *o.Solution
}

// GetSolutionOk returns a tuple with the Solution field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Finding) GetSolutionOk() (*string, bool) {
	if o == nil || IsNil(o.Solution) {
		return nil, false
	}
	return o.Solution, true
}

// HasSolution returns a boolean if a field has been set.
func (o *Finding) HasSolution() bool {
	if o != nil && !IsNil(o.Solution) {
		return true
	}

	return false
}

// SetSolution gets a reference to the given string and assigns it to the Solution field.
func (o *Finding) SetSolution(v string) {
	o.Solution = &v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *Finding) GetLinks() FindingLinks {
	if o == nil || IsNil(o.Links) {
		var ret FindingLinks
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Finding) GetLinksOk() (*FindingLinks, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *Finding) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given FindingLinks and assigns it to the Links field.
func (o *Finding) SetLinks(v FindingLinks) {
	o.Links = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *Finding) GetCreatedAt() int64 {
	if o == nil || IsNil(o.CreatedAt) {
		var ret int64
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Finding) GetCreatedAtOk() (*int64, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Finding) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given int64 and assigns it to the CreatedAt field.
func (o *Finding) SetCreatedAt(v int64) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *Finding) GetUpdatedAt() int64 {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret int64
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Finding) GetUpdatedAtOk() (*int64, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *Finding) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given int64 and assigns it to the UpdatedAt field.
func (o *Finding) SetUpdatedAt(v int64) {
	o.UpdatedAt = &v
}

// GetLastDetectedAt returns the LastDetectedAt field value if set, zero value otherwise.
func (o *Finding) GetLastDetectedAt() int64 {
	if o == nil || IsNil(o.LastDetectedAt) {
		var ret int64
		return ret
	}
	return *o.LastDetectedAt
}

// GetLastDetectedAtOk returns a tuple with the LastDetectedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Finding) GetLastDetectedAtOk() (*int64, bool) {
	if o == nil || IsNil(o.LastDetectedAt) {
		return nil, false
	}
	return o.LastDetectedAt, true
}

// HasLastDetectedAt returns a boolean if a field has been set.
func (o *Finding) HasLastDetectedAt() bool {
	if o != nil && !IsNil(o.LastDetectedAt) {
		return true
	}

	return false
}

// SetLastDetectedAt gets a reference to the given int64 and assigns it to the LastDetectedAt field.
func (o *Finding) SetLastDetectedAt(v int64) {
	o.LastDetectedAt = &v
}

// GetInstanceCount returns the InstanceCount field value if set, zero value otherwise.
func (o *Finding) GetInstanceCount() int64 {
	if o == nil || IsNil(o.InstanceCount) {
		var ret int64
		return ret
	}
	return *o.InstanceCount
}

// GetInstanceCountOk returns a tuple with the InstanceCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Finding) GetInstanceCountOk() (*int64, bool) {
	if o == nil || IsNil(o.InstanceCount) {
		return nil, false
	}
	return o.InstanceCount, true
}

// HasInstanceCount returns a boolean if a field has been set.
func (o *Finding) HasInstanceCount() bool {
	if o != nil && !IsNil(o.InstanceCount) {
		return true
	}

	return false
}

// SetInstanceCount gets a reference to the given int64 and assigns it to the InstanceCount field.
func (o *Finding) SetInstanceCount(v int64) {
	o.InstanceCount = &v
}

// GetRiskRank returns the RiskRank field value if set, zero value otherwise.
func (o *Finding) GetRiskRank() string {
	if o == nil || IsNil(o.RiskRank) {
		var ret string
		return ret
	}
	return *o.RiskRank
}

// GetRiskRankOk returns a tuple with the RiskRank field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Finding) GetRiskRankOk() (*string, bool) {
	if o == nil || IsNil(o.RiskRank) {
		return nil, false
	}
	return o.RiskRank, true
}

// HasRiskRank returns a boolean if a field has been set.
func (o *Finding) HasRiskRank() bool {
	if o != nil && !IsNil(o.RiskRank) {
		return true
	}

	return false
}

// SetRiskRank gets a reference to the given string and assigns it to the RiskRank field.
func (o *Finding) SetRiskRank(v string) {
	o.RiskRank = &v
}

// GetRiskRankValue returns the RiskRankValue field value if set, zero value otherwise.
func (o *Finding) GetRiskRankValue() int32 {
	if o == nil || IsNil(o.RiskRankValue) {
		var ret int32
		return ret
	}
	return *o.RiskRankValue
}

// GetRiskRankValueOk returns a tuple with the RiskRankValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Finding) GetRiskRankValueOk() (*int32, bool) {
	if o == nil || IsNil(o.RiskRankValue) {
		return nil, false
	}
	return o.RiskRankValue, true
}

// HasRiskRankValue returns a boolean if a field has been set.
func (o *Finding) HasRiskRankValue() bool {
	if o != nil && !IsNil(o.RiskRankValue) {
		return true
	}

	return false
}

// SetRiskRankValue gets a reference to the given int32 and assigns it to the RiskRankValue field.
func (o *Finding) SetRiskRankValue(v int32) {
	o.RiskRankValue = &v
}

func (o Finding) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Finding) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.Category) {
		toSerialize["category"] = o.Category
	}
	toSerialize["organization_id"] = o.OrganizationId
	if !IsNil(o.FindingCode) {
		toSerialize["finding_code"] = o.FindingCode
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Solution) {
		toSerialize["solution"] = o.Solution
	}
	if !IsNil(o.Links) {
		toSerialize["links"] = o.Links
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.LastDetectedAt) {
		toSerialize["last_detected_at"] = o.LastDetectedAt
	}
	if !IsNil(o.InstanceCount) {
		toSerialize["instance_count"] = o.InstanceCount
	}
	if !IsNil(o.RiskRank) {
		toSerialize["risk_rank"] = o.RiskRank
	}
	if !IsNil(o.RiskRankValue) {
		toSerialize["risk_rank_value"] = o.RiskRankValue
	}
	return toSerialize, nil
}

func (o *Finding) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"organization_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFinding := _Finding{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFinding)

	if err != nil {
		return err
	}

	*o = Finding(varFinding)

	return err
}

type NullableFinding struct {
	value *Finding
	isSet bool
}

func (v NullableFinding) Get() *Finding {
	return v.value
}

func (v *NullableFinding) Set(val *Finding) {
	v.value = val
	v.isSet = true
}

func (v NullableFinding) IsSet() bool {
	return v.isSet
}

func (v *NullableFinding) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFinding(val *Finding) *NullableFinding {
	return &NullableFinding{value: val, isSet: true}
}

func (v NullableFinding) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFinding) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
