/*
runZero API

runZero API. API use is rate limited, you can make as many calls per day as you have licensed assets.

API version: 4.0.250826.0
Contact: support@runzero.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AssetMetric type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssetMetric{}

// AssetMetric Asset metric summary for a single asset, keyed by asset ID in the parent map.
type AssetMetric struct {
	SiteId *string `json:"site_id,omitempty"`
	// Free-form metric values keyed by metric name.
	Metrics map[string]interface{} `json:"metrics,omitempty"`
}

// NewAssetMetric instantiates a new AssetMetric object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssetMetric() *AssetMetric {
	this := AssetMetric{}
	return &this
}

// NewAssetMetricWithDefaults instantiates a new AssetMetric object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssetMetricWithDefaults() *AssetMetric {
	this := AssetMetric{}
	return &this
}

// GetSiteId returns the SiteId field value if set, zero value otherwise.
func (o *AssetMetric) GetSiteId() string {
	if o == nil || IsNil(o.SiteId) {
		var ret string
		return ret
	}
	return *o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetMetric) GetSiteIdOk() (*string, bool) {
	if o == nil || IsNil(o.SiteId) {
		return nil, false
	}
	return o.SiteId, true
}

// HasSiteId returns a boolean if a field has been set.
func (o *AssetMetric) HasSiteId() bool {
	if o != nil && !IsNil(o.SiteId) {
		return true
	}

	return false
}

// SetSiteId gets a reference to the given string and assigns it to the SiteId field.
func (o *AssetMetric) SetSiteId(v string) {
	o.SiteId = &v
}

// GetMetrics returns the Metrics field value if set, zero value otherwise.
func (o *AssetMetric) GetMetrics() map[string]interface{} {
	if o == nil || IsNil(o.Metrics) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metrics
}

// GetMetricsOk returns a tuple with the Metrics field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetMetric) GetMetricsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metrics) {
		return map[string]interface{}{}, false
	}
	return o.Metrics, true
}

// HasMetrics returns a boolean if a field has been set.
func (o *AssetMetric) HasMetrics() bool {
	if o != nil && !IsNil(o.Metrics) {
		return true
	}

	return false
}

// SetMetrics gets a reference to the given map[string]interface{} and assigns it to the Metrics field.
func (o *AssetMetric) SetMetrics(v map[string]interface{}) {
	o.Metrics = v
}

func (o AssetMetric) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssetMetric) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SiteId) {
		toSerialize["site_id"] = o.SiteId
	}
	if !IsNil(o.Metrics) {
		toSerialize["metrics"] = o.Metrics
	}
	return toSerialize, nil
}

type NullableAssetMetric struct {
	value *AssetMetric
	isSet bool
}

func (v NullableAssetMetric) Get() *AssetMetric {
	return v.value
}

func (v *NullableAssetMetric) Set(val *AssetMetric) {
	v.value = val
	v.isSet = true
}

func (v NullableAssetMetric) IsSet() bool {
	return v.isSet
}

func (v *NullableAssetMetric) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssetMetric(val *AssetMetric) *NullableAssetMetric {
	return &NullableAssetMetric{value: val, isSet: true}
}

func (v NullableAssetMetric) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssetMetric) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


