/*
runZero API

runZero API. API use is rate limited, you can make as many calls per day as you have licensed assets.

API version: 4.0.250826.0
Contact: support@runzero.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AssetServiceNow type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssetServiceNow{}

// AssetServiceNow struct for AssetServiceNow
type AssetServiceNow struct {
	AssetId string `json:"asset_id"`
	Organization *string `json:"organization,omitempty"`
	Site *string `json:"site,omitempty"`
	DetectedBy *string `json:"detected_by,omitempty"`
	Type *string `json:"type,omitempty"`
	SysClassName *string `json:"sys_class_name,omitempty"`
	OsVendor *string `json:"os_vendor,omitempty"`
	OsProduct *string `json:"os_product,omitempty"`
	OsVersion *string `json:"os_version,omitempty"`
	HwVendor *string `json:"hw_vendor,omitempty"`
	HwProduct *string `json:"hw_product,omitempty"`
	HwVersion *string `json:"hw_version,omitempty"`
	IpAddress NullableString `json:"ip_address,omitempty"`
	AddressesScope *string `json:"addresses_scope,omitempty"`
	AddressesExtra *string `json:"addresses_extra,omitempty"`
	MacAddress *string `json:"mac_address,omitempty"`
	MacManufacturer *string `json:"mac_manufacturer,omitempty"`
	NewestMacAge *string `json:"newest_mac_age,omitempty"`
	Macs *string `json:"macs,omitempty"`
	MacVendors *string `json:"mac_vendors,omitempty"`
	Name *string `json:"name,omitempty"`
	Tags *string `json:"tags,omitempty"`
	Domains *string `json:"domains,omitempty"`
	ServiceCount *int64 `json:"service_count,omitempty"`
	ServiceCountTcp *int64 `json:"service_count_tcp,omitempty"`
	ServiceCountUdp *int64 `json:"service_count_udp,omitempty"`
	ServiceCountArp *int64 `json:"service_count_arp,omitempty"`
	ServiceCountIcmp *int64 `json:"service_count_icmp,omitempty"`
	LowestTtl *int64 `json:"lowest_ttl,omitempty"`
	LowestRtt *int64 `json:"lowest_rtt,omitempty"`
	Alive *bool `json:"alive,omitempty"`
	FirstDiscovered *string `json:"first_discovered,omitempty"`
	LastDiscovered *string `json:"last_discovered,omitempty"`
	LastUpdated *string `json:"last_updated,omitempty"`
	Comments *string `json:"comments,omitempty"`
}

type _AssetServiceNow AssetServiceNow

// NewAssetServiceNow instantiates a new AssetServiceNow object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssetServiceNow(assetId string) *AssetServiceNow {
	this := AssetServiceNow{}
	this.AssetId = assetId
	return &this
}

// NewAssetServiceNowWithDefaults instantiates a new AssetServiceNow object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssetServiceNowWithDefaults() *AssetServiceNow {
	this := AssetServiceNow{}
	return &this
}

// GetAssetId returns the AssetId field value
func (o *AssetServiceNow) GetAssetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AssetId
}

// GetAssetIdOk returns a tuple with the AssetId field value
// and a boolean to check if the value has been set.
func (o *AssetServiceNow) GetAssetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AssetId, true
}

// SetAssetId sets field value
func (o *AssetServiceNow) SetAssetId(v string) {
	o.AssetId = v
}

// GetOrganization returns the Organization field value if set, zero value otherwise.
func (o *AssetServiceNow) GetOrganization() string {
	if o == nil || IsNil(o.Organization) {
		var ret string
		return ret
	}
	return *o.Organization
}

// GetOrganizationOk returns a tuple with the Organization field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetServiceNow) GetOrganizationOk() (*string, bool) {
	if o == nil || IsNil(o.Organization) {
		return nil, false
	}
	return o.Organization, true
}

// HasOrganization returns a boolean if a field has been set.
func (o *AssetServiceNow) HasOrganization() bool {
	if o != nil && !IsNil(o.Organization) {
		return true
	}

	return false
}

// SetOrganization gets a reference to the given string and assigns it to the Organization field.
func (o *AssetServiceNow) SetOrganization(v string) {
	o.Organization = &v
}

// GetSite returns the Site field value if set, zero value otherwise.
func (o *AssetServiceNow) GetSite() string {
	if o == nil || IsNil(o.Site) {
		var ret string
		return ret
	}
	return *o.Site
}

// GetSiteOk returns a tuple with the Site field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetServiceNow) GetSiteOk() (*string, bool) {
	if o == nil || IsNil(o.Site) {
		return nil, false
	}
	return o.Site, true
}

// HasSite returns a boolean if a field has been set.
func (o *AssetServiceNow) HasSite() bool {
	if o != nil && !IsNil(o.Site) {
		return true
	}

	return false
}

// SetSite gets a reference to the given string and assigns it to the Site field.
func (o *AssetServiceNow) SetSite(v string) {
	o.Site = &v
}

// GetDetectedBy returns the DetectedBy field value if set, zero value otherwise.
func (o *AssetServiceNow) GetDetectedBy() string {
	if o == nil || IsNil(o.DetectedBy) {
		var ret string
		return ret
	}
	return *o.DetectedBy
}

// GetDetectedByOk returns a tuple with the DetectedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetServiceNow) GetDetectedByOk() (*string, bool) {
	if o == nil || IsNil(o.DetectedBy) {
		return nil, false
	}
	return o.DetectedBy, true
}

// HasDetectedBy returns a boolean if a field has been set.
func (o *AssetServiceNow) HasDetectedBy() bool {
	if o != nil && !IsNil(o.DetectedBy) {
		return true
	}

	return false
}

// SetDetectedBy gets a reference to the given string and assigns it to the DetectedBy field.
func (o *AssetServiceNow) SetDetectedBy(v string) {
	o.DetectedBy = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *AssetServiceNow) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetServiceNow) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *AssetServiceNow) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *AssetServiceNow) SetType(v string) {
	o.Type = &v
}

// GetSysClassName returns the SysClassName field value if set, zero value otherwise.
func (o *AssetServiceNow) GetSysClassName() string {
	if o == nil || IsNil(o.SysClassName) {
		var ret string
		return ret
	}
	return *o.SysClassName
}

// GetSysClassNameOk returns a tuple with the SysClassName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetServiceNow) GetSysClassNameOk() (*string, bool) {
	if o == nil || IsNil(o.SysClassName) {
		return nil, false
	}
	return o.SysClassName, true
}

// HasSysClassName returns a boolean if a field has been set.
func (o *AssetServiceNow) HasSysClassName() bool {
	if o != nil && !IsNil(o.SysClassName) {
		return true
	}

	return false
}

// SetSysClassName gets a reference to the given string and assigns it to the SysClassName field.
func (o *AssetServiceNow) SetSysClassName(v string) {
	o.SysClassName = &v
}

// GetOsVendor returns the OsVendor field value if set, zero value otherwise.
func (o *AssetServiceNow) GetOsVendor() string {
	if o == nil || IsNil(o.OsVendor) {
		var ret string
		return ret
	}
	return *o.OsVendor
}

// GetOsVendorOk returns a tuple with the OsVendor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetServiceNow) GetOsVendorOk() (*string, bool) {
	if o == nil || IsNil(o.OsVendor) {
		return nil, false
	}
	return o.OsVendor, true
}

// HasOsVendor returns a boolean if a field has been set.
func (o *AssetServiceNow) HasOsVendor() bool {
	if o != nil && !IsNil(o.OsVendor) {
		return true
	}

	return false
}

// SetOsVendor gets a reference to the given string and assigns it to the OsVendor field.
func (o *AssetServiceNow) SetOsVendor(v string) {
	o.OsVendor = &v
}

// GetOsProduct returns the OsProduct field value if set, zero value otherwise.
func (o *AssetServiceNow) GetOsProduct() string {
	if o == nil || IsNil(o.OsProduct) {
		var ret string
		return ret
	}
	return *o.OsProduct
}

// GetOsProductOk returns a tuple with the OsProduct field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetServiceNow) GetOsProductOk() (*string, bool) {
	if o == nil || IsNil(o.OsProduct) {
		return nil, false
	}
	return o.OsProduct, true
}

// HasOsProduct returns a boolean if a field has been set.
func (o *AssetServiceNow) HasOsProduct() bool {
	if o != nil && !IsNil(o.OsProduct) {
		return true
	}

	return false
}

// SetOsProduct gets a reference to the given string and assigns it to the OsProduct field.
func (o *AssetServiceNow) SetOsProduct(v string) {
	o.OsProduct = &v
}

// GetOsVersion returns the OsVersion field value if set, zero value otherwise.
func (o *AssetServiceNow) GetOsVersion() string {
	if o == nil || IsNil(o.OsVersion) {
		var ret string
		return ret
	}
	return *o.OsVersion
}

// GetOsVersionOk returns a tuple with the OsVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetServiceNow) GetOsVersionOk() (*string, bool) {
	if o == nil || IsNil(o.OsVersion) {
		return nil, false
	}
	return o.OsVersion, true
}

// HasOsVersion returns a boolean if a field has been set.
func (o *AssetServiceNow) HasOsVersion() bool {
	if o != nil && !IsNil(o.OsVersion) {
		return true
	}

	return false
}

// SetOsVersion gets a reference to the given string and assigns it to the OsVersion field.
func (o *AssetServiceNow) SetOsVersion(v string) {
	o.OsVersion = &v
}

// GetHwVendor returns the HwVendor field value if set, zero value otherwise.
func (o *AssetServiceNow) GetHwVendor() string {
	if o == nil || IsNil(o.HwVendor) {
		var ret string
		return ret
	}
	return *o.HwVendor
}

// GetHwVendorOk returns a tuple with the HwVendor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetServiceNow) GetHwVendorOk() (*string, bool) {
	if o == nil || IsNil(o.HwVendor) {
		return nil, false
	}
	return o.HwVendor, true
}

// HasHwVendor returns a boolean if a field has been set.
func (o *AssetServiceNow) HasHwVendor() bool {
	if o != nil && !IsNil(o.HwVendor) {
		return true
	}

	return false
}

// SetHwVendor gets a reference to the given string and assigns it to the HwVendor field.
func (o *AssetServiceNow) SetHwVendor(v string) {
	o.HwVendor = &v
}

// GetHwProduct returns the HwProduct field value if set, zero value otherwise.
func (o *AssetServiceNow) GetHwProduct() string {
	if o == nil || IsNil(o.HwProduct) {
		var ret string
		return ret
	}
	return *o.HwProduct
}

// GetHwProductOk returns a tuple with the HwProduct field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetServiceNow) GetHwProductOk() (*string, bool) {
	if o == nil || IsNil(o.HwProduct) {
		return nil, false
	}
	return o.HwProduct, true
}

// HasHwProduct returns a boolean if a field has been set.
func (o *AssetServiceNow) HasHwProduct() bool {
	if o != nil && !IsNil(o.HwProduct) {
		return true
	}

	return false
}

// SetHwProduct gets a reference to the given string and assigns it to the HwProduct field.
func (o *AssetServiceNow) SetHwProduct(v string) {
	o.HwProduct = &v
}

// GetHwVersion returns the HwVersion field value if set, zero value otherwise.
func (o *AssetServiceNow) GetHwVersion() string {
	if o == nil || IsNil(o.HwVersion) {
		var ret string
		return ret
	}
	return *o.HwVersion
}

// GetHwVersionOk returns a tuple with the HwVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetServiceNow) GetHwVersionOk() (*string, bool) {
	if o == nil || IsNil(o.HwVersion) {
		return nil, false
	}
	return o.HwVersion, true
}

// HasHwVersion returns a boolean if a field has been set.
func (o *AssetServiceNow) HasHwVersion() bool {
	if o != nil && !IsNil(o.HwVersion) {
		return true
	}

	return false
}

// SetHwVersion gets a reference to the given string and assigns it to the HwVersion field.
func (o *AssetServiceNow) SetHwVersion(v string) {
	o.HwVersion = &v
}

// GetIpAddress returns the IpAddress field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AssetServiceNow) GetIpAddress() string {
	if o == nil || IsNil(o.IpAddress.Get()) {
		var ret string
		return ret
	}
	return *o.IpAddress.Get()
}

// GetIpAddressOk returns a tuple with the IpAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AssetServiceNow) GetIpAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.IpAddress.Get(), o.IpAddress.IsSet()
}

// HasIpAddress returns a boolean if a field has been set.
func (o *AssetServiceNow) HasIpAddress() bool {
	if o != nil && o.IpAddress.IsSet() {
		return true
	}

	return false
}

// SetIpAddress gets a reference to the given NullableString and assigns it to the IpAddress field.
func (o *AssetServiceNow) SetIpAddress(v string) {
	o.IpAddress.Set(&v)
}
// SetIpAddressNil sets the value for IpAddress to be an explicit nil
func (o *AssetServiceNow) SetIpAddressNil() {
	o.IpAddress.Set(nil)
}

// UnsetIpAddress ensures that no value is present for IpAddress, not even an explicit nil
func (o *AssetServiceNow) UnsetIpAddress() {
	o.IpAddress.Unset()
}

// GetAddressesScope returns the AddressesScope field value if set, zero value otherwise.
func (o *AssetServiceNow) GetAddressesScope() string {
	if o == nil || IsNil(o.AddressesScope) {
		var ret string
		return ret
	}
	return *o.AddressesScope
}

// GetAddressesScopeOk returns a tuple with the AddressesScope field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetServiceNow) GetAddressesScopeOk() (*string, bool) {
	if o == nil || IsNil(o.AddressesScope) {
		return nil, false
	}
	return o.AddressesScope, true
}

// HasAddressesScope returns a boolean if a field has been set.
func (o *AssetServiceNow) HasAddressesScope() bool {
	if o != nil && !IsNil(o.AddressesScope) {
		return true
	}

	return false
}

// SetAddressesScope gets a reference to the given string and assigns it to the AddressesScope field.
func (o *AssetServiceNow) SetAddressesScope(v string) {
	o.AddressesScope = &v
}

// GetAddressesExtra returns the AddressesExtra field value if set, zero value otherwise.
func (o *AssetServiceNow) GetAddressesExtra() string {
	if o == nil || IsNil(o.AddressesExtra) {
		var ret string
		return ret
	}
	return *o.AddressesExtra
}

// GetAddressesExtraOk returns a tuple with the AddressesExtra field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetServiceNow) GetAddressesExtraOk() (*string, bool) {
	if o == nil || IsNil(o.AddressesExtra) {
		return nil, false
	}
	return o.AddressesExtra, true
}

// HasAddressesExtra returns a boolean if a field has been set.
func (o *AssetServiceNow) HasAddressesExtra() bool {
	if o != nil && !IsNil(o.AddressesExtra) {
		return true
	}

	return false
}

// SetAddressesExtra gets a reference to the given string and assigns it to the AddressesExtra field.
func (o *AssetServiceNow) SetAddressesExtra(v string) {
	o.AddressesExtra = &v
}

// GetMacAddress returns the MacAddress field value if set, zero value otherwise.
func (o *AssetServiceNow) GetMacAddress() string {
	if o == nil || IsNil(o.MacAddress) {
		var ret string
		return ret
	}
	return *o.MacAddress
}

// GetMacAddressOk returns a tuple with the MacAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetServiceNow) GetMacAddressOk() (*string, bool) {
	if o == nil || IsNil(o.MacAddress) {
		return nil, false
	}
	return o.MacAddress, true
}

// HasMacAddress returns a boolean if a field has been set.
func (o *AssetServiceNow) HasMacAddress() bool {
	if o != nil && !IsNil(o.MacAddress) {
		return true
	}

	return false
}

// SetMacAddress gets a reference to the given string and assigns it to the MacAddress field.
func (o *AssetServiceNow) SetMacAddress(v string) {
	o.MacAddress = &v
}

// GetMacManufacturer returns the MacManufacturer field value if set, zero value otherwise.
func (o *AssetServiceNow) GetMacManufacturer() string {
	if o == nil || IsNil(o.MacManufacturer) {
		var ret string
		return ret
	}
	return *o.MacManufacturer
}

// GetMacManufacturerOk returns a tuple with the MacManufacturer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetServiceNow) GetMacManufacturerOk() (*string, bool) {
	if o == nil || IsNil(o.MacManufacturer) {
		return nil, false
	}
	return o.MacManufacturer, true
}

// HasMacManufacturer returns a boolean if a field has been set.
func (o *AssetServiceNow) HasMacManufacturer() bool {
	if o != nil && !IsNil(o.MacManufacturer) {
		return true
	}

	return false
}

// SetMacManufacturer gets a reference to the given string and assigns it to the MacManufacturer field.
func (o *AssetServiceNow) SetMacManufacturer(v string) {
	o.MacManufacturer = &v
}

// GetNewestMacAge returns the NewestMacAge field value if set, zero value otherwise.
func (o *AssetServiceNow) GetNewestMacAge() string {
	if o == nil || IsNil(o.NewestMacAge) {
		var ret string
		return ret
	}
	return *o.NewestMacAge
}

// GetNewestMacAgeOk returns a tuple with the NewestMacAge field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetServiceNow) GetNewestMacAgeOk() (*string, bool) {
	if o == nil || IsNil(o.NewestMacAge) {
		return nil, false
	}
	return o.NewestMacAge, true
}

// HasNewestMacAge returns a boolean if a field has been set.
func (o *AssetServiceNow) HasNewestMacAge() bool {
	if o != nil && !IsNil(o.NewestMacAge) {
		return true
	}

	return false
}

// SetNewestMacAge gets a reference to the given string and assigns it to the NewestMacAge field.
func (o *AssetServiceNow) SetNewestMacAge(v string) {
	o.NewestMacAge = &v
}

// GetMacs returns the Macs field value if set, zero value otherwise.
func (o *AssetServiceNow) GetMacs() string {
	if o == nil || IsNil(o.Macs) {
		var ret string
		return ret
	}
	return *o.Macs
}

// GetMacsOk returns a tuple with the Macs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetServiceNow) GetMacsOk() (*string, bool) {
	if o == nil || IsNil(o.Macs) {
		return nil, false
	}
	return o.Macs, true
}

// HasMacs returns a boolean if a field has been set.
func (o *AssetServiceNow) HasMacs() bool {
	if o != nil && !IsNil(o.Macs) {
		return true
	}

	return false
}

// SetMacs gets a reference to the given string and assigns it to the Macs field.
func (o *AssetServiceNow) SetMacs(v string) {
	o.Macs = &v
}

// GetMacVendors returns the MacVendors field value if set, zero value otherwise.
func (o *AssetServiceNow) GetMacVendors() string {
	if o == nil || IsNil(o.MacVendors) {
		var ret string
		return ret
	}
	return *o.MacVendors
}

// GetMacVendorsOk returns a tuple with the MacVendors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetServiceNow) GetMacVendorsOk() (*string, bool) {
	if o == nil || IsNil(o.MacVendors) {
		return nil, false
	}
	return o.MacVendors, true
}

// HasMacVendors returns a boolean if a field has been set.
func (o *AssetServiceNow) HasMacVendors() bool {
	if o != nil && !IsNil(o.MacVendors) {
		return true
	}

	return false
}

// SetMacVendors gets a reference to the given string and assigns it to the MacVendors field.
func (o *AssetServiceNow) SetMacVendors(v string) {
	o.MacVendors = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *AssetServiceNow) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetServiceNow) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *AssetServiceNow) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *AssetServiceNow) SetName(v string) {
	o.Name = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *AssetServiceNow) GetTags() string {
	if o == nil || IsNil(o.Tags) {
		var ret string
		return ret
	}
	return *o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetServiceNow) GetTagsOk() (*string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *AssetServiceNow) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given string and assigns it to the Tags field.
func (o *AssetServiceNow) SetTags(v string) {
	o.Tags = &v
}

// GetDomains returns the Domains field value if set, zero value otherwise.
func (o *AssetServiceNow) GetDomains() string {
	if o == nil || IsNil(o.Domains) {
		var ret string
		return ret
	}
	return *o.Domains
}

// GetDomainsOk returns a tuple with the Domains field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetServiceNow) GetDomainsOk() (*string, bool) {
	if o == nil || IsNil(o.Domains) {
		return nil, false
	}
	return o.Domains, true
}

// HasDomains returns a boolean if a field has been set.
func (o *AssetServiceNow) HasDomains() bool {
	if o != nil && !IsNil(o.Domains) {
		return true
	}

	return false
}

// SetDomains gets a reference to the given string and assigns it to the Domains field.
func (o *AssetServiceNow) SetDomains(v string) {
	o.Domains = &v
}

// GetServiceCount returns the ServiceCount field value if set, zero value otherwise.
func (o *AssetServiceNow) GetServiceCount() int64 {
	if o == nil || IsNil(o.ServiceCount) {
		var ret int64
		return ret
	}
	return *o.ServiceCount
}

// GetServiceCountOk returns a tuple with the ServiceCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetServiceNow) GetServiceCountOk() (*int64, bool) {
	if o == nil || IsNil(o.ServiceCount) {
		return nil, false
	}
	return o.ServiceCount, true
}

// HasServiceCount returns a boolean if a field has been set.
func (o *AssetServiceNow) HasServiceCount() bool {
	if o != nil && !IsNil(o.ServiceCount) {
		return true
	}

	return false
}

// SetServiceCount gets a reference to the given int64 and assigns it to the ServiceCount field.
func (o *AssetServiceNow) SetServiceCount(v int64) {
	o.ServiceCount = &v
}

// GetServiceCountTcp returns the ServiceCountTcp field value if set, zero value otherwise.
func (o *AssetServiceNow) GetServiceCountTcp() int64 {
	if o == nil || IsNil(o.ServiceCountTcp) {
		var ret int64
		return ret
	}
	return *o.ServiceCountTcp
}

// GetServiceCountTcpOk returns a tuple with the ServiceCountTcp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetServiceNow) GetServiceCountTcpOk() (*int64, bool) {
	if o == nil || IsNil(o.ServiceCountTcp) {
		return nil, false
	}
	return o.ServiceCountTcp, true
}

// HasServiceCountTcp returns a boolean if a field has been set.
func (o *AssetServiceNow) HasServiceCountTcp() bool {
	if o != nil && !IsNil(o.ServiceCountTcp) {
		return true
	}

	return false
}

// SetServiceCountTcp gets a reference to the given int64 and assigns it to the ServiceCountTcp field.
func (o *AssetServiceNow) SetServiceCountTcp(v int64) {
	o.ServiceCountTcp = &v
}

// GetServiceCountUdp returns the ServiceCountUdp field value if set, zero value otherwise.
func (o *AssetServiceNow) GetServiceCountUdp() int64 {
	if o == nil || IsNil(o.ServiceCountUdp) {
		var ret int64
		return ret
	}
	return *o.ServiceCountUdp
}

// GetServiceCountUdpOk returns a tuple with the ServiceCountUdp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetServiceNow) GetServiceCountUdpOk() (*int64, bool) {
	if o == nil || IsNil(o.ServiceCountUdp) {
		return nil, false
	}
	return o.ServiceCountUdp, true
}

// HasServiceCountUdp returns a boolean if a field has been set.
func (o *AssetServiceNow) HasServiceCountUdp() bool {
	if o != nil && !IsNil(o.ServiceCountUdp) {
		return true
	}

	return false
}

// SetServiceCountUdp gets a reference to the given int64 and assigns it to the ServiceCountUdp field.
func (o *AssetServiceNow) SetServiceCountUdp(v int64) {
	o.ServiceCountUdp = &v
}

// GetServiceCountArp returns the ServiceCountArp field value if set, zero value otherwise.
func (o *AssetServiceNow) GetServiceCountArp() int64 {
	if o == nil || IsNil(o.ServiceCountArp) {
		var ret int64
		return ret
	}
	return *o.ServiceCountArp
}

// GetServiceCountArpOk returns a tuple with the ServiceCountArp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetServiceNow) GetServiceCountArpOk() (*int64, bool) {
	if o == nil || IsNil(o.ServiceCountArp) {
		return nil, false
	}
	return o.ServiceCountArp, true
}

// HasServiceCountArp returns a boolean if a field has been set.
func (o *AssetServiceNow) HasServiceCountArp() bool {
	if o != nil && !IsNil(o.ServiceCountArp) {
		return true
	}

	return false
}

// SetServiceCountArp gets a reference to the given int64 and assigns it to the ServiceCountArp field.
func (o *AssetServiceNow) SetServiceCountArp(v int64) {
	o.ServiceCountArp = &v
}

// GetServiceCountIcmp returns the ServiceCountIcmp field value if set, zero value otherwise.
func (o *AssetServiceNow) GetServiceCountIcmp() int64 {
	if o == nil || IsNil(o.ServiceCountIcmp) {
		var ret int64
		return ret
	}
	return *o.ServiceCountIcmp
}

// GetServiceCountIcmpOk returns a tuple with the ServiceCountIcmp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetServiceNow) GetServiceCountIcmpOk() (*int64, bool) {
	if o == nil || IsNil(o.ServiceCountIcmp) {
		return nil, false
	}
	return o.ServiceCountIcmp, true
}

// HasServiceCountIcmp returns a boolean if a field has been set.
func (o *AssetServiceNow) HasServiceCountIcmp() bool {
	if o != nil && !IsNil(o.ServiceCountIcmp) {
		return true
	}

	return false
}

// SetServiceCountIcmp gets a reference to the given int64 and assigns it to the ServiceCountIcmp field.
func (o *AssetServiceNow) SetServiceCountIcmp(v int64) {
	o.ServiceCountIcmp = &v
}

// GetLowestTtl returns the LowestTtl field value if set, zero value otherwise.
func (o *AssetServiceNow) GetLowestTtl() int64 {
	if o == nil || IsNil(o.LowestTtl) {
		var ret int64
		return ret
	}
	return *o.LowestTtl
}

// GetLowestTtlOk returns a tuple with the LowestTtl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetServiceNow) GetLowestTtlOk() (*int64, bool) {
	if o == nil || IsNil(o.LowestTtl) {
		return nil, false
	}
	return o.LowestTtl, true
}

// HasLowestTtl returns a boolean if a field has been set.
func (o *AssetServiceNow) HasLowestTtl() bool {
	if o != nil && !IsNil(o.LowestTtl) {
		return true
	}

	return false
}

// SetLowestTtl gets a reference to the given int64 and assigns it to the LowestTtl field.
func (o *AssetServiceNow) SetLowestTtl(v int64) {
	o.LowestTtl = &v
}

// GetLowestRtt returns the LowestRtt field value if set, zero value otherwise.
func (o *AssetServiceNow) GetLowestRtt() int64 {
	if o == nil || IsNil(o.LowestRtt) {
		var ret int64
		return ret
	}
	return *o.LowestRtt
}

// GetLowestRttOk returns a tuple with the LowestRtt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetServiceNow) GetLowestRttOk() (*int64, bool) {
	if o == nil || IsNil(o.LowestRtt) {
		return nil, false
	}
	return o.LowestRtt, true
}

// HasLowestRtt returns a boolean if a field has been set.
func (o *AssetServiceNow) HasLowestRtt() bool {
	if o != nil && !IsNil(o.LowestRtt) {
		return true
	}

	return false
}

// SetLowestRtt gets a reference to the given int64 and assigns it to the LowestRtt field.
func (o *AssetServiceNow) SetLowestRtt(v int64) {
	o.LowestRtt = &v
}

// GetAlive returns the Alive field value if set, zero value otherwise.
func (o *AssetServiceNow) GetAlive() bool {
	if o == nil || IsNil(o.Alive) {
		var ret bool
		return ret
	}
	return *o.Alive
}

// GetAliveOk returns a tuple with the Alive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetServiceNow) GetAliveOk() (*bool, bool) {
	if o == nil || IsNil(o.Alive) {
		return nil, false
	}
	return o.Alive, true
}

// HasAlive returns a boolean if a field has been set.
func (o *AssetServiceNow) HasAlive() bool {
	if o != nil && !IsNil(o.Alive) {
		return true
	}

	return false
}

// SetAlive gets a reference to the given bool and assigns it to the Alive field.
func (o *AssetServiceNow) SetAlive(v bool) {
	o.Alive = &v
}

// GetFirstDiscovered returns the FirstDiscovered field value if set, zero value otherwise.
func (o *AssetServiceNow) GetFirstDiscovered() string {
	if o == nil || IsNil(o.FirstDiscovered) {
		var ret string
		return ret
	}
	return *o.FirstDiscovered
}

// GetFirstDiscoveredOk returns a tuple with the FirstDiscovered field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetServiceNow) GetFirstDiscoveredOk() (*string, bool) {
	if o == nil || IsNil(o.FirstDiscovered) {
		return nil, false
	}
	return o.FirstDiscovered, true
}

// HasFirstDiscovered returns a boolean if a field has been set.
func (o *AssetServiceNow) HasFirstDiscovered() bool {
	if o != nil && !IsNil(o.FirstDiscovered) {
		return true
	}

	return false
}

// SetFirstDiscovered gets a reference to the given string and assigns it to the FirstDiscovered field.
func (o *AssetServiceNow) SetFirstDiscovered(v string) {
	o.FirstDiscovered = &v
}

// GetLastDiscovered returns the LastDiscovered field value if set, zero value otherwise.
func (o *AssetServiceNow) GetLastDiscovered() string {
	if o == nil || IsNil(o.LastDiscovered) {
		var ret string
		return ret
	}
	return *o.LastDiscovered
}

// GetLastDiscoveredOk returns a tuple with the LastDiscovered field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetServiceNow) GetLastDiscoveredOk() (*string, bool) {
	if o == nil || IsNil(o.LastDiscovered) {
		return nil, false
	}
	return o.LastDiscovered, true
}

// HasLastDiscovered returns a boolean if a field has been set.
func (o *AssetServiceNow) HasLastDiscovered() bool {
	if o != nil && !IsNil(o.LastDiscovered) {
		return true
	}

	return false
}

// SetLastDiscovered gets a reference to the given string and assigns it to the LastDiscovered field.
func (o *AssetServiceNow) SetLastDiscovered(v string) {
	o.LastDiscovered = &v
}

// GetLastUpdated returns the LastUpdated field value if set, zero value otherwise.
func (o *AssetServiceNow) GetLastUpdated() string {
	if o == nil || IsNil(o.LastUpdated) {
		var ret string
		return ret
	}
	return *o.LastUpdated
}

// GetLastUpdatedOk returns a tuple with the LastUpdated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetServiceNow) GetLastUpdatedOk() (*string, bool) {
	if o == nil || IsNil(o.LastUpdated) {
		return nil, false
	}
	return o.LastUpdated, true
}

// HasLastUpdated returns a boolean if a field has been set.
func (o *AssetServiceNow) HasLastUpdated() bool {
	if o != nil && !IsNil(o.LastUpdated) {
		return true
	}

	return false
}

// SetLastUpdated gets a reference to the given string and assigns it to the LastUpdated field.
func (o *AssetServiceNow) SetLastUpdated(v string) {
	o.LastUpdated = &v
}

// GetComments returns the Comments field value if set, zero value otherwise.
func (o *AssetServiceNow) GetComments() string {
	if o == nil || IsNil(o.Comments) {
		var ret string
		return ret
	}
	return *o.Comments
}

// GetCommentsOk returns a tuple with the Comments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetServiceNow) GetCommentsOk() (*string, bool) {
	if o == nil || IsNil(o.Comments) {
		return nil, false
	}
	return o.Comments, true
}

// HasComments returns a boolean if a field has been set.
func (o *AssetServiceNow) HasComments() bool {
	if o != nil && !IsNil(o.Comments) {
		return true
	}

	return false
}

// SetComments gets a reference to the given string and assigns it to the Comments field.
func (o *AssetServiceNow) SetComments(v string) {
	o.Comments = &v
}

func (o AssetServiceNow) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssetServiceNow) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["asset_id"] = o.AssetId
	if !IsNil(o.Organization) {
		toSerialize["organization"] = o.Organization
	}
	if !IsNil(o.Site) {
		toSerialize["site"] = o.Site
	}
	if !IsNil(o.DetectedBy) {
		toSerialize["detected_by"] = o.DetectedBy
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.SysClassName) {
		toSerialize["sys_class_name"] = o.SysClassName
	}
	if !IsNil(o.OsVendor) {
		toSerialize["os_vendor"] = o.OsVendor
	}
	if !IsNil(o.OsProduct) {
		toSerialize["os_product"] = o.OsProduct
	}
	if !IsNil(o.OsVersion) {
		toSerialize["os_version"] = o.OsVersion
	}
	if !IsNil(o.HwVendor) {
		toSerialize["hw_vendor"] = o.HwVendor
	}
	if !IsNil(o.HwProduct) {
		toSerialize["hw_product"] = o.HwProduct
	}
	if !IsNil(o.HwVersion) {
		toSerialize["hw_version"] = o.HwVersion
	}
	if o.IpAddress.IsSet() {
		toSerialize["ip_address"] = o.IpAddress.Get()
	}
	if !IsNil(o.AddressesScope) {
		toSerialize["addresses_scope"] = o.AddressesScope
	}
	if !IsNil(o.AddressesExtra) {
		toSerialize["addresses_extra"] = o.AddressesExtra
	}
	if !IsNil(o.MacAddress) {
		toSerialize["mac_address"] = o.MacAddress
	}
	if !IsNil(o.MacManufacturer) {
		toSerialize["mac_manufacturer"] = o.MacManufacturer
	}
	if !IsNil(o.NewestMacAge) {
		toSerialize["newest_mac_age"] = o.NewestMacAge
	}
	if !IsNil(o.Macs) {
		toSerialize["macs"] = o.Macs
	}
	if !IsNil(o.MacVendors) {
		toSerialize["mac_vendors"] = o.MacVendors
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.Domains) {
		toSerialize["domains"] = o.Domains
	}
	if !IsNil(o.ServiceCount) {
		toSerialize["service_count"] = o.ServiceCount
	}
	if !IsNil(o.ServiceCountTcp) {
		toSerialize["service_count_tcp"] = o.ServiceCountTcp
	}
	if !IsNil(o.ServiceCountUdp) {
		toSerialize["service_count_udp"] = o.ServiceCountUdp
	}
	if !IsNil(o.ServiceCountArp) {
		toSerialize["service_count_arp"] = o.ServiceCountArp
	}
	if !IsNil(o.ServiceCountIcmp) {
		toSerialize["service_count_icmp"] = o.ServiceCountIcmp
	}
	if !IsNil(o.LowestTtl) {
		toSerialize["lowest_ttl"] = o.LowestTtl
	}
	if !IsNil(o.LowestRtt) {
		toSerialize["lowest_rtt"] = o.LowestRtt
	}
	if !IsNil(o.Alive) {
		toSerialize["alive"] = o.Alive
	}
	if !IsNil(o.FirstDiscovered) {
		toSerialize["first_discovered"] = o.FirstDiscovered
	}
	if !IsNil(o.LastDiscovered) {
		toSerialize["last_discovered"] = o.LastDiscovered
	}
	if !IsNil(o.LastUpdated) {
		toSerialize["last_updated"] = o.LastUpdated
	}
	if !IsNil(o.Comments) {
		toSerialize["comments"] = o.Comments
	}
	return toSerialize, nil
}

func (o *AssetServiceNow) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"asset_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAssetServiceNow := _AssetServiceNow{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAssetServiceNow)

	if err != nil {
		return err
	}

	*o = AssetServiceNow(varAssetServiceNow)

	return err
}

type NullableAssetServiceNow struct {
	value *AssetServiceNow
	isSet bool
}

func (v NullableAssetServiceNow) Get() *AssetServiceNow {
	return v.value
}

func (v *NullableAssetServiceNow) Set(val *AssetServiceNow) {
	v.value = val
	v.isSet = true
}

func (v NullableAssetServiceNow) IsSet() bool {
	return v.isSet
}

func (v *NullableAssetServiceNow) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssetServiceNow(val *AssetServiceNow) *NullableAssetServiceNow {
	return &NullableAssetServiceNow{value: val, isSet: true}
}

func (v NullableAssetServiceNow) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssetServiceNow) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


