/*
runZero API

runZero API. API use is rate limited, you can make as many calls per day as you have licensed assets.

API version: 4.0.250826.0
Contact: support@runzero.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NetboxCredentialFields type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NetboxCredentialFields{}

// NetboxCredentialFields struct for NetboxCredentialFields
type NetboxCredentialFields struct {
	ApiUrl string `json:"api_url"`
	ApiKey string `json:"api_key"`
}

type _NetboxCredentialFields NetboxCredentialFields

// NewNetboxCredentialFields instantiates a new NetboxCredentialFields object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetboxCredentialFields(apiUrl string, apiKey string) *NetboxCredentialFields {
	this := NetboxCredentialFields{}
	this.ApiUrl = apiUrl
	this.ApiKey = apiKey
	return &this
}

// NewNetboxCredentialFieldsWithDefaults instantiates a new NetboxCredentialFields object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetboxCredentialFieldsWithDefaults() *NetboxCredentialFields {
	this := NetboxCredentialFields{}
	return &this
}

// GetApiUrl returns the ApiUrl field value
func (o *NetboxCredentialFields) GetApiUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApiUrl
}

// GetApiUrlOk returns a tuple with the ApiUrl field value
// and a boolean to check if the value has been set.
func (o *NetboxCredentialFields) GetApiUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApiUrl, true
}

// SetApiUrl sets field value
func (o *NetboxCredentialFields) SetApiUrl(v string) {
	o.ApiUrl = v
}

// GetApiKey returns the ApiKey field value
func (o *NetboxCredentialFields) GetApiKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApiKey
}

// GetApiKeyOk returns a tuple with the ApiKey field value
// and a boolean to check if the value has been set.
func (o *NetboxCredentialFields) GetApiKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApiKey, true
}

// SetApiKey sets field value
func (o *NetboxCredentialFields) SetApiKey(v string) {
	o.ApiKey = v
}

func (o NetboxCredentialFields) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NetboxCredentialFields) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["api_url"] = o.ApiUrl
	toSerialize["api_key"] = o.ApiKey
	return toSerialize, nil
}

func (o *NetboxCredentialFields) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"api_url",
		"api_key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNetboxCredentialFields := _NetboxCredentialFields{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNetboxCredentialFields)

	if err != nil {
		return err
	}

	*o = NetboxCredentialFields(varNetboxCredentialFields)

	return err
}

type NullableNetboxCredentialFields struct {
	value *NetboxCredentialFields
	isSet bool
}

func (v NullableNetboxCredentialFields) Get() *NetboxCredentialFields {
	return v.value
}

func (v *NullableNetboxCredentialFields) Set(val *NetboxCredentialFields) {
	v.value = val
	v.isSet = true
}

func (v NullableNetboxCredentialFields) IsSet() bool {
	return v.isSet
}

func (v *NullableNetboxCredentialFields) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetboxCredentialFields(val *NetboxCredentialFields) *NullableNetboxCredentialFields {
	return &NullableNetboxCredentialFields{value: val, isSet: true}
}

func (v NullableNetboxCredentialFields) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetboxCredentialFields) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


