/*
runZero API

runZero API. API use is rate limited, you can make as many calls per day as you have licensed assets.

API version: 4.0.250826.0
Contact: support@runzero.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package runzero

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the DirectoryUser type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DirectoryUser{}

// DirectoryUser struct for DirectoryUser
type DirectoryUser struct {
	Id                           string             `json:"id"`
	DirectoryUserId              *string            `json:"directory_user_id,omitempty"`
	DirectoryUserOrganizationId  *string            `json:"directory_user_organization_id,omitempty"`
	DirectoryUserSiteId          *string            `json:"directory_user_site_id,omitempty"`
	DirectoryUserSourceId        *int32             `json:"directory_user_source_id,omitempty"`
	DirectoryUserCreatedAt       *int64             `json:"directory_user_created_at,omitempty"`
	DirectoryUserUpdatedAt       *int64             `json:"directory_user_updated_at,omitempty"`
	DirectoryUserUserId          *string            `json:"directory_user_user_id,omitempty"`
	DirectoryUserGroupIds        []string           `json:"directory_user_group_ids,omitempty"`
	DirectoryUserDisplayName     *string            `json:"directory_user_display_name,omitempty"`
	DirectoryUserName            *string            `json:"directory_user_name,omitempty"`
	DirectoryUserFirstName       *string            `json:"directory_user_first_name,omitempty"`
	DirectoryUserLastName        *string            `json:"directory_user_last_name,omitempty"`
	DirectoryUserDescription     *string            `json:"directory_user_description,omitempty"`
	DirectoryUserEmail           *string            `json:"directory_user_email,omitempty"`
	DirectoryUserEmailNormalized *string            `json:"directory_user_email_normalized,omitempty"`
	DirectoryUserPhone           *string            `json:"directory_user_phone,omitempty"`
	DirectoryUserTitle           *string            `json:"directory_user_title,omitempty"`
	DirectoryUserLocation        *string            `json:"directory_user_location,omitempty"`
	DirectoryUserLastLogonAt     *int64             `json:"directory_user_last_logon_at,omitempty"`
	DirectoryUserAttributes      *map[string]string `json:"directory_user_attributes,omitempty"`
}

type _DirectoryUser DirectoryUser

// NewDirectoryUser instantiates a new DirectoryUser object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDirectoryUser(id string) *DirectoryUser {
	this := DirectoryUser{}
	this.Id = id
	return &this
}

// NewDirectoryUserWithDefaults instantiates a new DirectoryUser object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDirectoryUserWithDefaults() *DirectoryUser {
	this := DirectoryUser{}
	return &this
}

// GetId returns the Id field value
func (o *DirectoryUser) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DirectoryUser) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DirectoryUser) SetId(v string) {
	o.Id = v
}

// GetDirectoryUserId returns the DirectoryUserId field value if set, zero value otherwise.
func (o *DirectoryUser) GetDirectoryUserId() string {
	if o == nil || IsNil(o.DirectoryUserId) {
		var ret string
		return ret
	}
	return *o.DirectoryUserId
}

// GetDirectoryUserIdOk returns a tuple with the DirectoryUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectoryUser) GetDirectoryUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.DirectoryUserId) {
		return nil, false
	}
	return o.DirectoryUserId, true
}

// HasDirectoryUserId returns a boolean if a field has been set.
func (o *DirectoryUser) HasDirectoryUserId() bool {
	if o != nil && !IsNil(o.DirectoryUserId) {
		return true
	}

	return false
}

// SetDirectoryUserId gets a reference to the given string and assigns it to the DirectoryUserId field.
func (o *DirectoryUser) SetDirectoryUserId(v string) {
	o.DirectoryUserId = &v
}

// GetDirectoryUserOrganizationId returns the DirectoryUserOrganizationId field value if set, zero value otherwise.
func (o *DirectoryUser) GetDirectoryUserOrganizationId() string {
	if o == nil || IsNil(o.DirectoryUserOrganizationId) {
		var ret string
		return ret
	}
	return *o.DirectoryUserOrganizationId
}

// GetDirectoryUserOrganizationIdOk returns a tuple with the DirectoryUserOrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectoryUser) GetDirectoryUserOrganizationIdOk() (*string, bool) {
	if o == nil || IsNil(o.DirectoryUserOrganizationId) {
		return nil, false
	}
	return o.DirectoryUserOrganizationId, true
}

// HasDirectoryUserOrganizationId returns a boolean if a field has been set.
func (o *DirectoryUser) HasDirectoryUserOrganizationId() bool {
	if o != nil && !IsNil(o.DirectoryUserOrganizationId) {
		return true
	}

	return false
}

// SetDirectoryUserOrganizationId gets a reference to the given string and assigns it to the DirectoryUserOrganizationId field.
func (o *DirectoryUser) SetDirectoryUserOrganizationId(v string) {
	o.DirectoryUserOrganizationId = &v
}

// GetDirectoryUserSiteId returns the DirectoryUserSiteId field value if set, zero value otherwise.
func (o *DirectoryUser) GetDirectoryUserSiteId() string {
	if o == nil || IsNil(o.DirectoryUserSiteId) {
		var ret string
		return ret
	}
	return *o.DirectoryUserSiteId
}

// GetDirectoryUserSiteIdOk returns a tuple with the DirectoryUserSiteId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectoryUser) GetDirectoryUserSiteIdOk() (*string, bool) {
	if o == nil || IsNil(o.DirectoryUserSiteId) {
		return nil, false
	}
	return o.DirectoryUserSiteId, true
}

// HasDirectoryUserSiteId returns a boolean if a field has been set.
func (o *DirectoryUser) HasDirectoryUserSiteId() bool {
	if o != nil && !IsNil(o.DirectoryUserSiteId) {
		return true
	}

	return false
}

// SetDirectoryUserSiteId gets a reference to the given string and assigns it to the DirectoryUserSiteId field.
func (o *DirectoryUser) SetDirectoryUserSiteId(v string) {
	o.DirectoryUserSiteId = &v
}

// GetDirectoryUserSourceId returns the DirectoryUserSourceId field value if set, zero value otherwise.
func (o *DirectoryUser) GetDirectoryUserSourceId() int32 {
	if o == nil || IsNil(o.DirectoryUserSourceId) {
		var ret int32
		return ret
	}
	return *o.DirectoryUserSourceId
}

// GetDirectoryUserSourceIdOk returns a tuple with the DirectoryUserSourceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectoryUser) GetDirectoryUserSourceIdOk() (*int32, bool) {
	if o == nil || IsNil(o.DirectoryUserSourceId) {
		return nil, false
	}
	return o.DirectoryUserSourceId, true
}

// HasDirectoryUserSourceId returns a boolean if a field has been set.
func (o *DirectoryUser) HasDirectoryUserSourceId() bool {
	if o != nil && !IsNil(o.DirectoryUserSourceId) {
		return true
	}

	return false
}

// SetDirectoryUserSourceId gets a reference to the given int32 and assigns it to the DirectoryUserSourceId field.
func (o *DirectoryUser) SetDirectoryUserSourceId(v int32) {
	o.DirectoryUserSourceId = &v
}

// GetDirectoryUserCreatedAt returns the DirectoryUserCreatedAt field value if set, zero value otherwise.
func (o *DirectoryUser) GetDirectoryUserCreatedAt() int64 {
	if o == nil || IsNil(o.DirectoryUserCreatedAt) {
		var ret int64
		return ret
	}
	return *o.DirectoryUserCreatedAt
}

// GetDirectoryUserCreatedAtOk returns a tuple with the DirectoryUserCreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectoryUser) GetDirectoryUserCreatedAtOk() (*int64, bool) {
	if o == nil || IsNil(o.DirectoryUserCreatedAt) {
		return nil, false
	}
	return o.DirectoryUserCreatedAt, true
}

// HasDirectoryUserCreatedAt returns a boolean if a field has been set.
func (o *DirectoryUser) HasDirectoryUserCreatedAt() bool {
	if o != nil && !IsNil(o.DirectoryUserCreatedAt) {
		return true
	}

	return false
}

// SetDirectoryUserCreatedAt gets a reference to the given int64 and assigns it to the DirectoryUserCreatedAt field.
func (o *DirectoryUser) SetDirectoryUserCreatedAt(v int64) {
	o.DirectoryUserCreatedAt = &v
}

// GetDirectoryUserUpdatedAt returns the DirectoryUserUpdatedAt field value if set, zero value otherwise.
func (o *DirectoryUser) GetDirectoryUserUpdatedAt() int64 {
	if o == nil || IsNil(o.DirectoryUserUpdatedAt) {
		var ret int64
		return ret
	}
	return *o.DirectoryUserUpdatedAt
}

// GetDirectoryUserUpdatedAtOk returns a tuple with the DirectoryUserUpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectoryUser) GetDirectoryUserUpdatedAtOk() (*int64, bool) {
	if o == nil || IsNil(o.DirectoryUserUpdatedAt) {
		return nil, false
	}
	return o.DirectoryUserUpdatedAt, true
}

// HasDirectoryUserUpdatedAt returns a boolean if a field has been set.
func (o *DirectoryUser) HasDirectoryUserUpdatedAt() bool {
	if o != nil && !IsNil(o.DirectoryUserUpdatedAt) {
		return true
	}

	return false
}

// SetDirectoryUserUpdatedAt gets a reference to the given int64 and assigns it to the DirectoryUserUpdatedAt field.
func (o *DirectoryUser) SetDirectoryUserUpdatedAt(v int64) {
	o.DirectoryUserUpdatedAt = &v
}

// GetDirectoryUserUserId returns the DirectoryUserUserId field value if set, zero value otherwise.
func (o *DirectoryUser) GetDirectoryUserUserId() string {
	if o == nil || IsNil(o.DirectoryUserUserId) {
		var ret string
		return ret
	}
	return *o.DirectoryUserUserId
}

// GetDirectoryUserUserIdOk returns a tuple with the DirectoryUserUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectoryUser) GetDirectoryUserUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.DirectoryUserUserId) {
		return nil, false
	}
	return o.DirectoryUserUserId, true
}

// HasDirectoryUserUserId returns a boolean if a field has been set.
func (o *DirectoryUser) HasDirectoryUserUserId() bool {
	if o != nil && !IsNil(o.DirectoryUserUserId) {
		return true
	}

	return false
}

// SetDirectoryUserUserId gets a reference to the given string and assigns it to the DirectoryUserUserId field.
func (o *DirectoryUser) SetDirectoryUserUserId(v string) {
	o.DirectoryUserUserId = &v
}

// GetDirectoryUserGroupIds returns the DirectoryUserGroupIds field value if set, zero value otherwise.
func (o *DirectoryUser) GetDirectoryUserGroupIds() []string {
	if o == nil || IsNil(o.DirectoryUserGroupIds) {
		var ret []string
		return ret
	}
	return o.DirectoryUserGroupIds
}

// GetDirectoryUserGroupIdsOk returns a tuple with the DirectoryUserGroupIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectoryUser) GetDirectoryUserGroupIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.DirectoryUserGroupIds) {
		return nil, false
	}
	return o.DirectoryUserGroupIds, true
}

// HasDirectoryUserGroupIds returns a boolean if a field has been set.
func (o *DirectoryUser) HasDirectoryUserGroupIds() bool {
	if o != nil && !IsNil(o.DirectoryUserGroupIds) {
		return true
	}

	return false
}

// SetDirectoryUserGroupIds gets a reference to the given []string and assigns it to the DirectoryUserGroupIds field.
func (o *DirectoryUser) SetDirectoryUserGroupIds(v []string) {
	o.DirectoryUserGroupIds = v
}

// GetDirectoryUserDisplayName returns the DirectoryUserDisplayName field value if set, zero value otherwise.
func (o *DirectoryUser) GetDirectoryUserDisplayName() string {
	if o == nil || IsNil(o.DirectoryUserDisplayName) {
		var ret string
		return ret
	}
	return *o.DirectoryUserDisplayName
}

// GetDirectoryUserDisplayNameOk returns a tuple with the DirectoryUserDisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectoryUser) GetDirectoryUserDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DirectoryUserDisplayName) {
		return nil, false
	}
	return o.DirectoryUserDisplayName, true
}

// HasDirectoryUserDisplayName returns a boolean if a field has been set.
func (o *DirectoryUser) HasDirectoryUserDisplayName() bool {
	if o != nil && !IsNil(o.DirectoryUserDisplayName) {
		return true
	}

	return false
}

// SetDirectoryUserDisplayName gets a reference to the given string and assigns it to the DirectoryUserDisplayName field.
func (o *DirectoryUser) SetDirectoryUserDisplayName(v string) {
	o.DirectoryUserDisplayName = &v
}

// GetDirectoryUserName returns the DirectoryUserName field value if set, zero value otherwise.
func (o *DirectoryUser) GetDirectoryUserName() string {
	if o == nil || IsNil(o.DirectoryUserName) {
		var ret string
		return ret
	}
	return *o.DirectoryUserName
}

// GetDirectoryUserNameOk returns a tuple with the DirectoryUserName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectoryUser) GetDirectoryUserNameOk() (*string, bool) {
	if o == nil || IsNil(o.DirectoryUserName) {
		return nil, false
	}
	return o.DirectoryUserName, true
}

// HasDirectoryUserName returns a boolean if a field has been set.
func (o *DirectoryUser) HasDirectoryUserName() bool {
	if o != nil && !IsNil(o.DirectoryUserName) {
		return true
	}

	return false
}

// SetDirectoryUserName gets a reference to the given string and assigns it to the DirectoryUserName field.
func (o *DirectoryUser) SetDirectoryUserName(v string) {
	o.DirectoryUserName = &v
}

// GetDirectoryUserFirstName returns the DirectoryUserFirstName field value if set, zero value otherwise.
func (o *DirectoryUser) GetDirectoryUserFirstName() string {
	if o == nil || IsNil(o.DirectoryUserFirstName) {
		var ret string
		return ret
	}
	return *o.DirectoryUserFirstName
}

// GetDirectoryUserFirstNameOk returns a tuple with the DirectoryUserFirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectoryUser) GetDirectoryUserFirstNameOk() (*string, bool) {
	if o == nil || IsNil(o.DirectoryUserFirstName) {
		return nil, false
	}
	return o.DirectoryUserFirstName, true
}

// HasDirectoryUserFirstName returns a boolean if a field has been set.
func (o *DirectoryUser) HasDirectoryUserFirstName() bool {
	if o != nil && !IsNil(o.DirectoryUserFirstName) {
		return true
	}

	return false
}

// SetDirectoryUserFirstName gets a reference to the given string and assigns it to the DirectoryUserFirstName field.
func (o *DirectoryUser) SetDirectoryUserFirstName(v string) {
	o.DirectoryUserFirstName = &v
}

// GetDirectoryUserLastName returns the DirectoryUserLastName field value if set, zero value otherwise.
func (o *DirectoryUser) GetDirectoryUserLastName() string {
	if o == nil || IsNil(o.DirectoryUserLastName) {
		var ret string
		return ret
	}
	return *o.DirectoryUserLastName
}

// GetDirectoryUserLastNameOk returns a tuple with the DirectoryUserLastName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectoryUser) GetDirectoryUserLastNameOk() (*string, bool) {
	if o == nil || IsNil(o.DirectoryUserLastName) {
		return nil, false
	}
	return o.DirectoryUserLastName, true
}

// HasDirectoryUserLastName returns a boolean if a field has been set.
func (o *DirectoryUser) HasDirectoryUserLastName() bool {
	if o != nil && !IsNil(o.DirectoryUserLastName) {
		return true
	}

	return false
}

// SetDirectoryUserLastName gets a reference to the given string and assigns it to the DirectoryUserLastName field.
func (o *DirectoryUser) SetDirectoryUserLastName(v string) {
	o.DirectoryUserLastName = &v
}

// GetDirectoryUserDescription returns the DirectoryUserDescription field value if set, zero value otherwise.
func (o *DirectoryUser) GetDirectoryUserDescription() string {
	if o == nil || IsNil(o.DirectoryUserDescription) {
		var ret string
		return ret
	}
	return *o.DirectoryUserDescription
}

// GetDirectoryUserDescriptionOk returns a tuple with the DirectoryUserDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectoryUser) GetDirectoryUserDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.DirectoryUserDescription) {
		return nil, false
	}
	return o.DirectoryUserDescription, true
}

// HasDirectoryUserDescription returns a boolean if a field has been set.
func (o *DirectoryUser) HasDirectoryUserDescription() bool {
	if o != nil && !IsNil(o.DirectoryUserDescription) {
		return true
	}

	return false
}

// SetDirectoryUserDescription gets a reference to the given string and assigns it to the DirectoryUserDescription field.
func (o *DirectoryUser) SetDirectoryUserDescription(v string) {
	o.DirectoryUserDescription = &v
}

// GetDirectoryUserEmail returns the DirectoryUserEmail field value if set, zero value otherwise.
func (o *DirectoryUser) GetDirectoryUserEmail() string {
	if o == nil || IsNil(o.DirectoryUserEmail) {
		var ret string
		return ret
	}
	return *o.DirectoryUserEmail
}

// GetDirectoryUserEmailOk returns a tuple with the DirectoryUserEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectoryUser) GetDirectoryUserEmailOk() (*string, bool) {
	if o == nil || IsNil(o.DirectoryUserEmail) {
		return nil, false
	}
	return o.DirectoryUserEmail, true
}

// HasDirectoryUserEmail returns a boolean if a field has been set.
func (o *DirectoryUser) HasDirectoryUserEmail() bool {
	if o != nil && !IsNil(o.DirectoryUserEmail) {
		return true
	}

	return false
}

// SetDirectoryUserEmail gets a reference to the given string and assigns it to the DirectoryUserEmail field.
func (o *DirectoryUser) SetDirectoryUserEmail(v string) {
	o.DirectoryUserEmail = &v
}

// GetDirectoryUserEmailNormalized returns the DirectoryUserEmailNormalized field value if set, zero value otherwise.
func (o *DirectoryUser) GetDirectoryUserEmailNormalized() string {
	if o == nil || IsNil(o.DirectoryUserEmailNormalized) {
		var ret string
		return ret
	}
	return *o.DirectoryUserEmailNormalized
}

// GetDirectoryUserEmailNormalizedOk returns a tuple with the DirectoryUserEmailNormalized field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectoryUser) GetDirectoryUserEmailNormalizedOk() (*string, bool) {
	if o == nil || IsNil(o.DirectoryUserEmailNormalized) {
		return nil, false
	}
	return o.DirectoryUserEmailNormalized, true
}

// HasDirectoryUserEmailNormalized returns a boolean if a field has been set.
func (o *DirectoryUser) HasDirectoryUserEmailNormalized() bool {
	if o != nil && !IsNil(o.DirectoryUserEmailNormalized) {
		return true
	}

	return false
}

// SetDirectoryUserEmailNormalized gets a reference to the given string and assigns it to the DirectoryUserEmailNormalized field.
func (o *DirectoryUser) SetDirectoryUserEmailNormalized(v string) {
	o.DirectoryUserEmailNormalized = &v
}

// GetDirectoryUserPhone returns the DirectoryUserPhone field value if set, zero value otherwise.
func (o *DirectoryUser) GetDirectoryUserPhone() string {
	if o == nil || IsNil(o.DirectoryUserPhone) {
		var ret string
		return ret
	}
	return *o.DirectoryUserPhone
}

// GetDirectoryUserPhoneOk returns a tuple with the DirectoryUserPhone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectoryUser) GetDirectoryUserPhoneOk() (*string, bool) {
	if o == nil || IsNil(o.DirectoryUserPhone) {
		return nil, false
	}
	return o.DirectoryUserPhone, true
}

// HasDirectoryUserPhone returns a boolean if a field has been set.
func (o *DirectoryUser) HasDirectoryUserPhone() bool {
	if o != nil && !IsNil(o.DirectoryUserPhone) {
		return true
	}

	return false
}

// SetDirectoryUserPhone gets a reference to the given string and assigns it to the DirectoryUserPhone field.
func (o *DirectoryUser) SetDirectoryUserPhone(v string) {
	o.DirectoryUserPhone = &v
}

// GetDirectoryUserTitle returns the DirectoryUserTitle field value if set, zero value otherwise.
func (o *DirectoryUser) GetDirectoryUserTitle() string {
	if o == nil || IsNil(o.DirectoryUserTitle) {
		var ret string
		return ret
	}
	return *o.DirectoryUserTitle
}

// GetDirectoryUserTitleOk returns a tuple with the DirectoryUserTitle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectoryUser) GetDirectoryUserTitleOk() (*string, bool) {
	if o == nil || IsNil(o.DirectoryUserTitle) {
		return nil, false
	}
	return o.DirectoryUserTitle, true
}

// HasDirectoryUserTitle returns a boolean if a field has been set.
func (o *DirectoryUser) HasDirectoryUserTitle() bool {
	if o != nil && !IsNil(o.DirectoryUserTitle) {
		return true
	}

	return false
}

// SetDirectoryUserTitle gets a reference to the given string and assigns it to the DirectoryUserTitle field.
func (o *DirectoryUser) SetDirectoryUserTitle(v string) {
	o.DirectoryUserTitle = &v
}

// GetDirectoryUserLocation returns the DirectoryUserLocation field value if set, zero value otherwise.
func (o *DirectoryUser) GetDirectoryUserLocation() string {
	if o == nil || IsNil(o.DirectoryUserLocation) {
		var ret string
		return ret
	}
	return *o.DirectoryUserLocation
}

// GetDirectoryUserLocationOk returns a tuple with the DirectoryUserLocation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectoryUser) GetDirectoryUserLocationOk() (*string, bool) {
	if o == nil || IsNil(o.DirectoryUserLocation) {
		return nil, false
	}
	return o.DirectoryUserLocation, true
}

// HasDirectoryUserLocation returns a boolean if a field has been set.
func (o *DirectoryUser) HasDirectoryUserLocation() bool {
	if o != nil && !IsNil(o.DirectoryUserLocation) {
		return true
	}

	return false
}

// SetDirectoryUserLocation gets a reference to the given string and assigns it to the DirectoryUserLocation field.
func (o *DirectoryUser) SetDirectoryUserLocation(v string) {
	o.DirectoryUserLocation = &v
}

// GetDirectoryUserLastLogonAt returns the DirectoryUserLastLogonAt field value if set, zero value otherwise.
func (o *DirectoryUser) GetDirectoryUserLastLogonAt() int64 {
	if o == nil || IsNil(o.DirectoryUserLastLogonAt) {
		var ret int64
		return ret
	}
	return *o.DirectoryUserLastLogonAt
}

// GetDirectoryUserLastLogonAtOk returns a tuple with the DirectoryUserLastLogonAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectoryUser) GetDirectoryUserLastLogonAtOk() (*int64, bool) {
	if o == nil || IsNil(o.DirectoryUserLastLogonAt) {
		return nil, false
	}
	return o.DirectoryUserLastLogonAt, true
}

// HasDirectoryUserLastLogonAt returns a boolean if a field has been set.
func (o *DirectoryUser) HasDirectoryUserLastLogonAt() bool {
	if o != nil && !IsNil(o.DirectoryUserLastLogonAt) {
		return true
	}

	return false
}

// SetDirectoryUserLastLogonAt gets a reference to the given int64 and assigns it to the DirectoryUserLastLogonAt field.
func (o *DirectoryUser) SetDirectoryUserLastLogonAt(v int64) {
	o.DirectoryUserLastLogonAt = &v
}

// GetDirectoryUserAttributes returns the DirectoryUserAttributes field value if set, zero value otherwise.
func (o *DirectoryUser) GetDirectoryUserAttributes() map[string]string {
	if o == nil || IsNil(o.DirectoryUserAttributes) {
		var ret map[string]string
		return ret
	}
	return *o.DirectoryUserAttributes
}

// GetDirectoryUserAttributesOk returns a tuple with the DirectoryUserAttributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectoryUser) GetDirectoryUserAttributesOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.DirectoryUserAttributes) {
		return nil, false
	}
	return o.DirectoryUserAttributes, true
}

// HasDirectoryUserAttributes returns a boolean if a field has been set.
func (o *DirectoryUser) HasDirectoryUserAttributes() bool {
	if o != nil && !IsNil(o.DirectoryUserAttributes) {
		return true
	}

	return false
}

// SetDirectoryUserAttributes gets a reference to the given map[string]string and assigns it to the DirectoryUserAttributes field.
func (o *DirectoryUser) SetDirectoryUserAttributes(v map[string]string) {
	o.DirectoryUserAttributes = &v
}

func (o DirectoryUser) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DirectoryUser) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.DirectoryUserId) {
		toSerialize["directory_user_id"] = o.DirectoryUserId
	}
	if !IsNil(o.DirectoryUserOrganizationId) {
		toSerialize["directory_user_organization_id"] = o.DirectoryUserOrganizationId
	}
	if !IsNil(o.DirectoryUserSiteId) {
		toSerialize["directory_user_site_id"] = o.DirectoryUserSiteId
	}
	if !IsNil(o.DirectoryUserSourceId) {
		toSerialize["directory_user_source_id"] = o.DirectoryUserSourceId
	}
	if !IsNil(o.DirectoryUserCreatedAt) {
		toSerialize["directory_user_created_at"] = o.DirectoryUserCreatedAt
	}
	if !IsNil(o.DirectoryUserUpdatedAt) {
		toSerialize["directory_user_updated_at"] = o.DirectoryUserUpdatedAt
	}
	if !IsNil(o.DirectoryUserUserId) {
		toSerialize["directory_user_user_id"] = o.DirectoryUserUserId
	}
	if !IsNil(o.DirectoryUserGroupIds) {
		toSerialize["directory_user_group_ids"] = o.DirectoryUserGroupIds
	}
	if !IsNil(o.DirectoryUserDisplayName) {
		toSerialize["directory_user_display_name"] = o.DirectoryUserDisplayName
	}
	if !IsNil(o.DirectoryUserName) {
		toSerialize["directory_user_name"] = o.DirectoryUserName
	}
	if !IsNil(o.DirectoryUserFirstName) {
		toSerialize["directory_user_first_name"] = o.DirectoryUserFirstName
	}
	if !IsNil(o.DirectoryUserLastName) {
		toSerialize["directory_user_last_name"] = o.DirectoryUserLastName
	}
	if !IsNil(o.DirectoryUserDescription) {
		toSerialize["directory_user_description"] = o.DirectoryUserDescription
	}
	if !IsNil(o.DirectoryUserEmail) {
		toSerialize["directory_user_email"] = o.DirectoryUserEmail
	}
	if !IsNil(o.DirectoryUserEmailNormalized) {
		toSerialize["directory_user_email_normalized"] = o.DirectoryUserEmailNormalized
	}
	if !IsNil(o.DirectoryUserPhone) {
		toSerialize["directory_user_phone"] = o.DirectoryUserPhone
	}
	if !IsNil(o.DirectoryUserTitle) {
		toSerialize["directory_user_title"] = o.DirectoryUserTitle
	}
	if !IsNil(o.DirectoryUserLocation) {
		toSerialize["directory_user_location"] = o.DirectoryUserLocation
	}
	if !IsNil(o.DirectoryUserLastLogonAt) {
		toSerialize["directory_user_last_logon_at"] = o.DirectoryUserLastLogonAt
	}
	if !IsNil(o.DirectoryUserAttributes) {
		toSerialize["directory_user_attributes"] = o.DirectoryUserAttributes
	}
	return toSerialize, nil
}

func (o *DirectoryUser) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDirectoryUser := _DirectoryUser{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDirectoryUser)

	if err != nil {
		return err
	}

	*o = DirectoryUser(varDirectoryUser)

	return err
}

type NullableDirectoryUser struct {
	value *DirectoryUser
	isSet bool
}

func (v NullableDirectoryUser) Get() *DirectoryUser {
	return v.value
}

func (v *NullableDirectoryUser) Set(val *DirectoryUser) {
	v.value = val
	v.isSet = true
}

func (v NullableDirectoryUser) IsSet() bool {
	return v.isSet
}

func (v *NullableDirectoryUser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDirectoryUser(val *DirectoryUser) *NullableDirectoryUser {
	return &NullableDirectoryUser{value: val, isSet: true}
}

func (v NullableDirectoryUser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDirectoryUser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
