/*
runZero API

runZero API. API use is rate limited, you can make as many calls per day as you have licensed assets.

API version: 4.0.250826.0
Contact: support@runzero.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package runzero

import (
	"encoding/json"
	"fmt"

	"gopkg.in/validator.v2"
)

// ExportVulnerabilitiesJSON200Response - struct for ExportVulnerabilitiesJSON200Response
type ExportVulnerabilitiesJSON200Response struct {
	ExportVulnerabilitiesJSON200ResponseOneOf *ExportVulnerabilitiesJSON200ResponseOneOf
	ArrayOfVulnerability                      *[]Vulnerability
}

// ExportVulnerabilitiesJSON200ResponseOneOfAsExportVulnerabilitiesJSON200Response is a convenience function that returns ExportVulnerabilitiesJSON200ResponseOneOf wrapped in ExportVulnerabilitiesJSON200Response
func ExportVulnerabilitiesJSON200ResponseOneOfAsExportVulnerabilitiesJSON200Response(v *ExportVulnerabilitiesJSON200ResponseOneOf) ExportVulnerabilitiesJSON200Response {
	return ExportVulnerabilitiesJSON200Response{
		ExportVulnerabilitiesJSON200ResponseOneOf: v,
	}
}

// []VulnerabilityAsExportVulnerabilitiesJSON200Response is a convenience function that returns []Vulnerability wrapped in ExportVulnerabilitiesJSON200Response
func ArrayOfVulnerabilityAsExportVulnerabilitiesJSON200Response(v *[]Vulnerability) ExportVulnerabilitiesJSON200Response {
	return ExportVulnerabilitiesJSON200Response{
		ArrayOfVulnerability: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *ExportVulnerabilitiesJSON200Response) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ExportVulnerabilitiesJSON200ResponseOneOf
	err = newStrictDecoder(data).Decode(&dst.ExportVulnerabilitiesJSON200ResponseOneOf)
	if err == nil {
		jsonExportVulnerabilitiesJSON200ResponseOneOf, _ := json.Marshal(dst.ExportVulnerabilitiesJSON200ResponseOneOf)
		if string(jsonExportVulnerabilitiesJSON200ResponseOneOf) == "{}" { // empty struct
			dst.ExportVulnerabilitiesJSON200ResponseOneOf = nil
		} else {
			if err = validator.Validate(dst.ExportVulnerabilitiesJSON200ResponseOneOf); err != nil {
				dst.ExportVulnerabilitiesJSON200ResponseOneOf = nil
			} else {
				match++
			}
		}
	} else {
		dst.ExportVulnerabilitiesJSON200ResponseOneOf = nil
	}

	// try to unmarshal data into ArrayOfVulnerability
	err = newStrictDecoder(data).Decode(&dst.ArrayOfVulnerability)
	if err == nil {
		jsonArrayOfVulnerability, _ := json.Marshal(dst.ArrayOfVulnerability)
		if string(jsonArrayOfVulnerability) == "{}" { // empty struct
			dst.ArrayOfVulnerability = nil
		} else {
			if err = validator.Validate(dst.ArrayOfVulnerability); err != nil {
				dst.ArrayOfVulnerability = nil
			} else {
				match++
			}
		}
	} else {
		dst.ArrayOfVulnerability = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ExportVulnerabilitiesJSON200ResponseOneOf = nil
		dst.ArrayOfVulnerability = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ExportVulnerabilitiesJSON200Response)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(ExportVulnerabilitiesJSON200Response)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ExportVulnerabilitiesJSON200Response) MarshalJSON() ([]byte, error) {
	if src.ExportVulnerabilitiesJSON200ResponseOneOf != nil {
		return json.Marshal(&src.ExportVulnerabilitiesJSON200ResponseOneOf)
	}

	if src.ArrayOfVulnerability != nil {
		return json.Marshal(&src.ArrayOfVulnerability)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ExportVulnerabilitiesJSON200Response) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.ExportVulnerabilitiesJSON200ResponseOneOf != nil {
		return obj.ExportVulnerabilitiesJSON200ResponseOneOf
	}

	if obj.ArrayOfVulnerability != nil {
		return obj.ArrayOfVulnerability
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj ExportVulnerabilitiesJSON200Response) GetActualInstanceValue() interface{} {
	if obj.ExportVulnerabilitiesJSON200ResponseOneOf != nil {
		return *obj.ExportVulnerabilitiesJSON200ResponseOneOf
	}

	if obj.ArrayOfVulnerability != nil {
		return *obj.ArrayOfVulnerability
	}

	// all schemas are nil
	return nil
}

type NullableExportVulnerabilitiesJSON200Response struct {
	value *ExportVulnerabilitiesJSON200Response
	isSet bool
}

func (v NullableExportVulnerabilitiesJSON200Response) Get() *ExportVulnerabilitiesJSON200Response {
	return v.value
}

func (v *NullableExportVulnerabilitiesJSON200Response) Set(val *ExportVulnerabilitiesJSON200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableExportVulnerabilitiesJSON200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableExportVulnerabilitiesJSON200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExportVulnerabilitiesJSON200Response(val *ExportVulnerabilitiesJSON200Response) *NullableExportVulnerabilitiesJSON200Response {
	return &NullableExportVulnerabilitiesJSON200Response{value: val, isSet: true}
}

func (v NullableExportVulnerabilitiesJSON200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExportVulnerabilitiesJSON200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
