/*
runZero API

runZero API. API use is rate limited, you can make as many calls per day as you have licensed assets.

API version: 4.0.250826.0
Contact: support@runzero.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ServicePage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServicePage{}

// ServicePage A page of services returned from a paginated export.
type ServicePage struct {
	Services []Service `json:"services,omitempty"`
	// The key to use for the next page of results
	NextKey *string `json:"next_key,omitempty"`
}

// NewServicePage instantiates a new ServicePage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServicePage() *ServicePage {
	this := ServicePage{}
	return &this
}

// NewServicePageWithDefaults instantiates a new ServicePage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServicePageWithDefaults() *ServicePage {
	this := ServicePage{}
	return &this
}

// GetServices returns the Services field value if set, zero value otherwise.
func (o *ServicePage) GetServices() []Service {
	if o == nil || IsNil(o.Services) {
		var ret []Service
		return ret
	}
	return o.Services
}

// GetServicesOk returns a tuple with the Services field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServicePage) GetServicesOk() ([]Service, bool) {
	if o == nil || IsNil(o.Services) {
		return nil, false
	}
	return o.Services, true
}

// HasServices returns a boolean if a field has been set.
func (o *ServicePage) HasServices() bool {
	if o != nil && !IsNil(o.Services) {
		return true
	}

	return false
}

// SetServices gets a reference to the given []Service and assigns it to the Services field.
func (o *ServicePage) SetServices(v []Service) {
	o.Services = v
}

// GetNextKey returns the NextKey field value if set, zero value otherwise.
func (o *ServicePage) GetNextKey() string {
	if o == nil || IsNil(o.NextKey) {
		var ret string
		return ret
	}
	return *o.NextKey
}

// GetNextKeyOk returns a tuple with the NextKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServicePage) GetNextKeyOk() (*string, bool) {
	if o == nil || IsNil(o.NextKey) {
		return nil, false
	}
	return o.NextKey, true
}

// HasNextKey returns a boolean if a field has been set.
func (o *ServicePage) HasNextKey() bool {
	if o != nil && !IsNil(o.NextKey) {
		return true
	}

	return false
}

// SetNextKey gets a reference to the given string and assigns it to the NextKey field.
func (o *ServicePage) SetNextKey(v string) {
	o.NextKey = &v
}

func (o ServicePage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServicePage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Services) {
		toSerialize["services"] = o.Services
	}
	if !IsNil(o.NextKey) {
		toSerialize["next_key"] = o.NextKey
	}
	return toSerialize, nil
}

type NullableServicePage struct {
	value *ServicePage
	isSet bool
}

func (v NullableServicePage) Get() *ServicePage {
	return v.value
}

func (v *NullableServicePage) Set(val *ServicePage) {
	v.value = val
	v.isSet = true
}

func (v NullableServicePage) IsSet() bool {
	return v.isSet
}

func (v *NullableServicePage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServicePage(val *ServicePage) *NullableServicePage {
	return &NullableServicePage{value: val, isSet: true}
}

func (v NullableServicePage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServicePage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


