/*
runZero API

runZero API. API use is rate limited, you can make as many calls per day as you have licensed assets.

API version: 4.0.250826.0
Contact: support@runzero.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package runzero

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CustomIntegrationCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomIntegrationCreate{}

// CustomIntegrationCreate Request body used to register a new custom integration.
type CustomIntegrationCreate struct {
	// The unique name of the custom integration, without spaces.
	Name string `json:"name" validate:"regexp=^\\\\S+$"`
	// Base64 encoded png with maximum size 256x256 pixels
	Icon *string `json:"icon,omitempty"`
	// A text description of the custom integration
	Description *string `json:"description,omitempty"`
}

type _CustomIntegrationCreate CustomIntegrationCreate

// NewCustomIntegrationCreate instantiates a new CustomIntegrationCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomIntegrationCreate(name string) *CustomIntegrationCreate {
	this := CustomIntegrationCreate{}
	this.Name = name
	return &this
}

// NewCustomIntegrationCreateWithDefaults instantiates a new CustomIntegrationCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomIntegrationCreateWithDefaults() *CustomIntegrationCreate {
	this := CustomIntegrationCreate{}
	return &this
}

// GetName returns the Name field value
func (o *CustomIntegrationCreate) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CustomIntegrationCreate) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CustomIntegrationCreate) SetName(v string) {
	o.Name = v
}

// GetIcon returns the Icon field value if set, zero value otherwise.
func (o *CustomIntegrationCreate) GetIcon() string {
	if o == nil || IsNil(o.Icon) {
		var ret string
		return ret
	}
	return *o.Icon
}

// GetIconOk returns a tuple with the Icon field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomIntegrationCreate) GetIconOk() (*string, bool) {
	if o == nil || IsNil(o.Icon) {
		return nil, false
	}
	return o.Icon, true
}

// HasIcon returns a boolean if a field has been set.
func (o *CustomIntegrationCreate) HasIcon() bool {
	if o != nil && !IsNil(o.Icon) {
		return true
	}

	return false
}

// SetIcon gets a reference to the given string and assigns it to the Icon field.
func (o *CustomIntegrationCreate) SetIcon(v string) {
	o.Icon = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CustomIntegrationCreate) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomIntegrationCreate) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CustomIntegrationCreate) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CustomIntegrationCreate) SetDescription(v string) {
	o.Description = &v
}

func (o CustomIntegrationCreate) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomIntegrationCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Icon) {
		toSerialize["icon"] = o.Icon
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return toSerialize, nil
}

func (o *CustomIntegrationCreate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCustomIntegrationCreate := _CustomIntegrationCreate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCustomIntegrationCreate)

	if err != nil {
		return err
	}

	*o = CustomIntegrationCreate(varCustomIntegrationCreate)

	return err
}

type NullableCustomIntegrationCreate struct {
	value *CustomIntegrationCreate
	isSet bool
}

func (v NullableCustomIntegrationCreate) Get() *CustomIntegrationCreate {
	return v.value
}

func (v *NullableCustomIntegrationCreate) Set(val *CustomIntegrationCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomIntegrationCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomIntegrationCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomIntegrationCreate(val *CustomIntegrationCreate) *NullableCustomIntegrationCreate {
	return &NullableCustomIntegrationCreate{value: val, isSet: true}
}

func (v NullableCustomIntegrationCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomIntegrationCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
