/*
runZero API

runZero API. API use is rate limited, you can make as many calls per day as you have licensed assets.

API version: 4.0.250826.0
Contact: support@runzero.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the APIClientCredentials type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &APIClientCredentials{}

// APIClientCredentials Newly-issued OAuth client credentials returned when creating an API client.
type APIClientCredentials struct {
	ApiClientId *string `json:"api_client_id,omitempty"`
	ApiClientSecret *string `json:"api_client_secret,omitempty"`
}

// NewAPIClientCredentials instantiates a new APIClientCredentials object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAPIClientCredentials() *APIClientCredentials {
	this := APIClientCredentials{}
	return &this
}

// NewAPIClientCredentialsWithDefaults instantiates a new APIClientCredentials object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAPIClientCredentialsWithDefaults() *APIClientCredentials {
	this := APIClientCredentials{}
	return &this
}

// GetApiClientId returns the ApiClientId field value if set, zero value otherwise.
func (o *APIClientCredentials) GetApiClientId() string {
	if o == nil || IsNil(o.ApiClientId) {
		var ret string
		return ret
	}
	return *o.ApiClientId
}

// GetApiClientIdOk returns a tuple with the ApiClientId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIClientCredentials) GetApiClientIdOk() (*string, bool) {
	if o == nil || IsNil(o.ApiClientId) {
		return nil, false
	}
	return o.ApiClientId, true
}

// HasApiClientId returns a boolean if a field has been set.
func (o *APIClientCredentials) HasApiClientId() bool {
	if o != nil && !IsNil(o.ApiClientId) {
		return true
	}

	return false
}

// SetApiClientId gets a reference to the given string and assigns it to the ApiClientId field.
func (o *APIClientCredentials) SetApiClientId(v string) {
	o.ApiClientId = &v
}

// GetApiClientSecret returns the ApiClientSecret field value if set, zero value otherwise.
func (o *APIClientCredentials) GetApiClientSecret() string {
	if o == nil || IsNil(o.ApiClientSecret) {
		var ret string
		return ret
	}
	return *o.ApiClientSecret
}

// GetApiClientSecretOk returns a tuple with the ApiClientSecret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIClientCredentials) GetApiClientSecretOk() (*string, bool) {
	if o == nil || IsNil(o.ApiClientSecret) {
		return nil, false
	}
	return o.ApiClientSecret, true
}

// HasApiClientSecret returns a boolean if a field has been set.
func (o *APIClientCredentials) HasApiClientSecret() bool {
	if o != nil && !IsNil(o.ApiClientSecret) {
		return true
	}

	return false
}

// SetApiClientSecret gets a reference to the given string and assigns it to the ApiClientSecret field.
func (o *APIClientCredentials) SetApiClientSecret(v string) {
	o.ApiClientSecret = &v
}

func (o APIClientCredentials) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o APIClientCredentials) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ApiClientId) {
		toSerialize["api_client_id"] = o.ApiClientId
	}
	if !IsNil(o.ApiClientSecret) {
		toSerialize["api_client_secret"] = o.ApiClientSecret
	}
	return toSerialize, nil
}

type NullableAPIClientCredentials struct {
	value *APIClientCredentials
	isSet bool
}

func (v NullableAPIClientCredentials) Get() *APIClientCredentials {
	return v.value
}

func (v *NullableAPIClientCredentials) Set(val *APIClientCredentials) {
	v.value = val
	v.isSet = true
}

func (v NullableAPIClientCredentials) IsSet() bool {
	return v.isSet
}

func (v *NullableAPIClientCredentials) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAPIClientCredentials(val *APIClientCredentials) *NullableAPIClientCredentials {
	return &NullableAPIClientCredentials{value: val, isSet: true}
}

func (v NullableAPIClientCredentials) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAPIClientCredentials) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


