/*
runZero API

runZero API. API use is rate limited, you can make as many calls per day as you have licensed assets.

API version: 4.0.250826.0
Contact: support@runzero.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OrganizationAPIKey type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationAPIKey{}

// OrganizationAPIKey An API key issued for an organization.
type OrganizationAPIKey struct {
	Id string `json:"id"`
	ClientId *string `json:"client_id,omitempty"`
	OrganizationId *string `json:"organization_id,omitempty"`
	CreatedAt *int64 `json:"created_at,omitempty"`
	CreatedBy *string `json:"created_by,omitempty"`
	Comment *string `json:"comment,omitempty"`
	LastUsedAt *int64 `json:"last_used_at,omitempty"`
	LastUsedIp *string `json:"last_used_ip,omitempty"`
	LastUsedUa *string `json:"last_used_ua,omitempty"`
	Counter *int64 `json:"counter,omitempty"`
	UsageToday *int64 `json:"usage_today,omitempty"`
	UsageLimit *int64 `json:"usage_limit,omitempty"`
	Token *string `json:"token,omitempty"`
	Inactive *bool `json:"inactive,omitempty"`
	Type *string `json:"type,omitempty"`
}

type _OrganizationAPIKey OrganizationAPIKey

// NewOrganizationAPIKey instantiates a new OrganizationAPIKey object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationAPIKey(id string) *OrganizationAPIKey {
	this := OrganizationAPIKey{}
	this.Id = id
	return &this
}

// NewOrganizationAPIKeyWithDefaults instantiates a new OrganizationAPIKey object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationAPIKeyWithDefaults() *OrganizationAPIKey {
	this := OrganizationAPIKey{}
	return &this
}

// GetId returns the Id field value
func (o *OrganizationAPIKey) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *OrganizationAPIKey) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *OrganizationAPIKey) SetId(v string) {
	o.Id = v
}

// GetClientId returns the ClientId field value if set, zero value otherwise.
func (o *OrganizationAPIKey) GetClientId() string {
	if o == nil || IsNil(o.ClientId) {
		var ret string
		return ret
	}
	return *o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationAPIKey) GetClientIdOk() (*string, bool) {
	if o == nil || IsNil(o.ClientId) {
		return nil, false
	}
	return o.ClientId, true
}

// HasClientId returns a boolean if a field has been set.
func (o *OrganizationAPIKey) HasClientId() bool {
	if o != nil && !IsNil(o.ClientId) {
		return true
	}

	return false
}

// SetClientId gets a reference to the given string and assigns it to the ClientId field.
func (o *OrganizationAPIKey) SetClientId(v string) {
	o.ClientId = &v
}

// GetOrganizationId returns the OrganizationId field value if set, zero value otherwise.
func (o *OrganizationAPIKey) GetOrganizationId() string {
	if o == nil || IsNil(o.OrganizationId) {
		var ret string
		return ret
	}
	return *o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationAPIKey) GetOrganizationIdOk() (*string, bool) {
	if o == nil || IsNil(o.OrganizationId) {
		return nil, false
	}
	return o.OrganizationId, true
}

// HasOrganizationId returns a boolean if a field has been set.
func (o *OrganizationAPIKey) HasOrganizationId() bool {
	if o != nil && !IsNil(o.OrganizationId) {
		return true
	}

	return false
}

// SetOrganizationId gets a reference to the given string and assigns it to the OrganizationId field.
func (o *OrganizationAPIKey) SetOrganizationId(v string) {
	o.OrganizationId = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *OrganizationAPIKey) GetCreatedAt() int64 {
	if o == nil || IsNil(o.CreatedAt) {
		var ret int64
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationAPIKey) GetCreatedAtOk() (*int64, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *OrganizationAPIKey) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given int64 and assigns it to the CreatedAt field.
func (o *OrganizationAPIKey) SetCreatedAt(v int64) {
	o.CreatedAt = &v
}

// GetCreatedBy returns the CreatedBy field value if set, zero value otherwise.
func (o *OrganizationAPIKey) GetCreatedBy() string {
	if o == nil || IsNil(o.CreatedBy) {
		var ret string
		return ret
	}
	return *o.CreatedBy
}

// GetCreatedByOk returns a tuple with the CreatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationAPIKey) GetCreatedByOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedBy) {
		return nil, false
	}
	return o.CreatedBy, true
}

// HasCreatedBy returns a boolean if a field has been set.
func (o *OrganizationAPIKey) HasCreatedBy() bool {
	if o != nil && !IsNil(o.CreatedBy) {
		return true
	}

	return false
}

// SetCreatedBy gets a reference to the given string and assigns it to the CreatedBy field.
func (o *OrganizationAPIKey) SetCreatedBy(v string) {
	o.CreatedBy = &v
}

// GetComment returns the Comment field value if set, zero value otherwise.
func (o *OrganizationAPIKey) GetComment() string {
	if o == nil || IsNil(o.Comment) {
		var ret string
		return ret
	}
	return *o.Comment
}

// GetCommentOk returns a tuple with the Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationAPIKey) GetCommentOk() (*string, bool) {
	if o == nil || IsNil(o.Comment) {
		return nil, false
	}
	return o.Comment, true
}

// HasComment returns a boolean if a field has been set.
func (o *OrganizationAPIKey) HasComment() bool {
	if o != nil && !IsNil(o.Comment) {
		return true
	}

	return false
}

// SetComment gets a reference to the given string and assigns it to the Comment field.
func (o *OrganizationAPIKey) SetComment(v string) {
	o.Comment = &v
}

// GetLastUsedAt returns the LastUsedAt field value if set, zero value otherwise.
func (o *OrganizationAPIKey) GetLastUsedAt() int64 {
	if o == nil || IsNil(o.LastUsedAt) {
		var ret int64
		return ret
	}
	return *o.LastUsedAt
}

// GetLastUsedAtOk returns a tuple with the LastUsedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationAPIKey) GetLastUsedAtOk() (*int64, bool) {
	if o == nil || IsNil(o.LastUsedAt) {
		return nil, false
	}
	return o.LastUsedAt, true
}

// HasLastUsedAt returns a boolean if a field has been set.
func (o *OrganizationAPIKey) HasLastUsedAt() bool {
	if o != nil && !IsNil(o.LastUsedAt) {
		return true
	}

	return false
}

// SetLastUsedAt gets a reference to the given int64 and assigns it to the LastUsedAt field.
func (o *OrganizationAPIKey) SetLastUsedAt(v int64) {
	o.LastUsedAt = &v
}

// GetLastUsedIp returns the LastUsedIp field value if set, zero value otherwise.
func (o *OrganizationAPIKey) GetLastUsedIp() string {
	if o == nil || IsNil(o.LastUsedIp) {
		var ret string
		return ret
	}
	return *o.LastUsedIp
}

// GetLastUsedIpOk returns a tuple with the LastUsedIp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationAPIKey) GetLastUsedIpOk() (*string, bool) {
	if o == nil || IsNil(o.LastUsedIp) {
		return nil, false
	}
	return o.LastUsedIp, true
}

// HasLastUsedIp returns a boolean if a field has been set.
func (o *OrganizationAPIKey) HasLastUsedIp() bool {
	if o != nil && !IsNil(o.LastUsedIp) {
		return true
	}

	return false
}

// SetLastUsedIp gets a reference to the given string and assigns it to the LastUsedIp field.
func (o *OrganizationAPIKey) SetLastUsedIp(v string) {
	o.LastUsedIp = &v
}

// GetLastUsedUa returns the LastUsedUa field value if set, zero value otherwise.
func (o *OrganizationAPIKey) GetLastUsedUa() string {
	if o == nil || IsNil(o.LastUsedUa) {
		var ret string
		return ret
	}
	return *o.LastUsedUa
}

// GetLastUsedUaOk returns a tuple with the LastUsedUa field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationAPIKey) GetLastUsedUaOk() (*string, bool) {
	if o == nil || IsNil(o.LastUsedUa) {
		return nil, false
	}
	return o.LastUsedUa, true
}

// HasLastUsedUa returns a boolean if a field has been set.
func (o *OrganizationAPIKey) HasLastUsedUa() bool {
	if o != nil && !IsNil(o.LastUsedUa) {
		return true
	}

	return false
}

// SetLastUsedUa gets a reference to the given string and assigns it to the LastUsedUa field.
func (o *OrganizationAPIKey) SetLastUsedUa(v string) {
	o.LastUsedUa = &v
}

// GetCounter returns the Counter field value if set, zero value otherwise.
func (o *OrganizationAPIKey) GetCounter() int64 {
	if o == nil || IsNil(o.Counter) {
		var ret int64
		return ret
	}
	return *o.Counter
}

// GetCounterOk returns a tuple with the Counter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationAPIKey) GetCounterOk() (*int64, bool) {
	if o == nil || IsNil(o.Counter) {
		return nil, false
	}
	return o.Counter, true
}

// HasCounter returns a boolean if a field has been set.
func (o *OrganizationAPIKey) HasCounter() bool {
	if o != nil && !IsNil(o.Counter) {
		return true
	}

	return false
}

// SetCounter gets a reference to the given int64 and assigns it to the Counter field.
func (o *OrganizationAPIKey) SetCounter(v int64) {
	o.Counter = &v
}

// GetUsageToday returns the UsageToday field value if set, zero value otherwise.
func (o *OrganizationAPIKey) GetUsageToday() int64 {
	if o == nil || IsNil(o.UsageToday) {
		var ret int64
		return ret
	}
	return *o.UsageToday
}

// GetUsageTodayOk returns a tuple with the UsageToday field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationAPIKey) GetUsageTodayOk() (*int64, bool) {
	if o == nil || IsNil(o.UsageToday) {
		return nil, false
	}
	return o.UsageToday, true
}

// HasUsageToday returns a boolean if a field has been set.
func (o *OrganizationAPIKey) HasUsageToday() bool {
	if o != nil && !IsNil(o.UsageToday) {
		return true
	}

	return false
}

// SetUsageToday gets a reference to the given int64 and assigns it to the UsageToday field.
func (o *OrganizationAPIKey) SetUsageToday(v int64) {
	o.UsageToday = &v
}

// GetUsageLimit returns the UsageLimit field value if set, zero value otherwise.
func (o *OrganizationAPIKey) GetUsageLimit() int64 {
	if o == nil || IsNil(o.UsageLimit) {
		var ret int64
		return ret
	}
	return *o.UsageLimit
}

// GetUsageLimitOk returns a tuple with the UsageLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationAPIKey) GetUsageLimitOk() (*int64, bool) {
	if o == nil || IsNil(o.UsageLimit) {
		return nil, false
	}
	return o.UsageLimit, true
}

// HasUsageLimit returns a boolean if a field has been set.
func (o *OrganizationAPIKey) HasUsageLimit() bool {
	if o != nil && !IsNil(o.UsageLimit) {
		return true
	}

	return false
}

// SetUsageLimit gets a reference to the given int64 and assigns it to the UsageLimit field.
func (o *OrganizationAPIKey) SetUsageLimit(v int64) {
	o.UsageLimit = &v
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *OrganizationAPIKey) GetToken() string {
	if o == nil || IsNil(o.Token) {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationAPIKey) GetTokenOk() (*string, bool) {
	if o == nil || IsNil(o.Token) {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *OrganizationAPIKey) HasToken() bool {
	if o != nil && !IsNil(o.Token) {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *OrganizationAPIKey) SetToken(v string) {
	o.Token = &v
}

// GetInactive returns the Inactive field value if set, zero value otherwise.
func (o *OrganizationAPIKey) GetInactive() bool {
	if o == nil || IsNil(o.Inactive) {
		var ret bool
		return ret
	}
	return *o.Inactive
}

// GetInactiveOk returns a tuple with the Inactive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationAPIKey) GetInactiveOk() (*bool, bool) {
	if o == nil || IsNil(o.Inactive) {
		return nil, false
	}
	return o.Inactive, true
}

// HasInactive returns a boolean if a field has been set.
func (o *OrganizationAPIKey) HasInactive() bool {
	if o != nil && !IsNil(o.Inactive) {
		return true
	}

	return false
}

// SetInactive gets a reference to the given bool and assigns it to the Inactive field.
func (o *OrganizationAPIKey) SetInactive(v bool) {
	o.Inactive = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *OrganizationAPIKey) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationAPIKey) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *OrganizationAPIKey) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *OrganizationAPIKey) SetType(v string) {
	o.Type = &v
}

func (o OrganizationAPIKey) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationAPIKey) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.ClientId) {
		toSerialize["client_id"] = o.ClientId
	}
	if !IsNil(o.OrganizationId) {
		toSerialize["organization_id"] = o.OrganizationId
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.CreatedBy) {
		toSerialize["created_by"] = o.CreatedBy
	}
	if !IsNil(o.Comment) {
		toSerialize["comment"] = o.Comment
	}
	if !IsNil(o.LastUsedAt) {
		toSerialize["last_used_at"] = o.LastUsedAt
	}
	if !IsNil(o.LastUsedIp) {
		toSerialize["last_used_ip"] = o.LastUsedIp
	}
	if !IsNil(o.LastUsedUa) {
		toSerialize["last_used_ua"] = o.LastUsedUa
	}
	if !IsNil(o.Counter) {
		toSerialize["counter"] = o.Counter
	}
	if !IsNil(o.UsageToday) {
		toSerialize["usage_today"] = o.UsageToday
	}
	if !IsNil(o.UsageLimit) {
		toSerialize["usage_limit"] = o.UsageLimit
	}
	if !IsNil(o.Token) {
		toSerialize["token"] = o.Token
	}
	if !IsNil(o.Inactive) {
		toSerialize["inactive"] = o.Inactive
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

func (o *OrganizationAPIKey) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrganizationAPIKey := _OrganizationAPIKey{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOrganizationAPIKey)

	if err != nil {
		return err
	}

	*o = OrganizationAPIKey(varOrganizationAPIKey)

	return err
}

type NullableOrganizationAPIKey struct {
	value *OrganizationAPIKey
	isSet bool
}

func (v NullableOrganizationAPIKey) Get() *OrganizationAPIKey {
	return v.value
}

func (v *NullableOrganizationAPIKey) Set(val *OrganizationAPIKey) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationAPIKey) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationAPIKey) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationAPIKey(val *OrganizationAPIKey) *NullableOrganizationAPIKey {
	return &NullableOrganizationAPIKey{value: val, isSet: true}
}

func (v NullableOrganizationAPIKey) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationAPIKey) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


