/*
runZero API

runZero API. API use is rate limited, you can make as many calls per day as you have licensed assets.

API version: 4.0.250826.0
Contact: support@runzero.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package runzero

import (
	"encoding/json"
	"fmt"

	"gopkg.in/validator.v2"
)

// ExportServicesJSON200Response - struct for ExportServicesJSON200Response
type ExportServicesJSON200Response struct {
	ExportServicesJSON200ResponseOneOf *ExportServicesJSON200ResponseOneOf
	ArrayOfService                     *[]Service
}

// ExportServicesJSON200ResponseOneOfAsExportServicesJSON200Response is a convenience function that returns ExportServicesJSON200ResponseOneOf wrapped in ExportServicesJSON200Response
func ExportServicesJSON200ResponseOneOfAsExportServicesJSON200Response(v *ExportServicesJSON200ResponseOneOf) ExportServicesJSON200Response {
	return ExportServicesJSON200Response{
		ExportServicesJSON200ResponseOneOf: v,
	}
}

// []ServiceAsExportServicesJSON200Response is a convenience function that returns []Service wrapped in ExportServicesJSON200Response
func ArrayOfServiceAsExportServicesJSON200Response(v *[]Service) ExportServicesJSON200Response {
	return ExportServicesJSON200Response{
		ArrayOfService: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *ExportServicesJSON200Response) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ExportServicesJSON200ResponseOneOf
	err = newStrictDecoder(data).Decode(&dst.ExportServicesJSON200ResponseOneOf)
	if err == nil {
		jsonExportServicesJSON200ResponseOneOf, _ := json.Marshal(dst.ExportServicesJSON200ResponseOneOf)
		if string(jsonExportServicesJSON200ResponseOneOf) == "{}" { // empty struct
			dst.ExportServicesJSON200ResponseOneOf = nil
		} else {
			if err = validator.Validate(dst.ExportServicesJSON200ResponseOneOf); err != nil {
				dst.ExportServicesJSON200ResponseOneOf = nil
			} else {
				match++
			}
		}
	} else {
		dst.ExportServicesJSON200ResponseOneOf = nil
	}

	// try to unmarshal data into ArrayOfService
	err = newStrictDecoder(data).Decode(&dst.ArrayOfService)
	if err == nil {
		jsonArrayOfService, _ := json.Marshal(dst.ArrayOfService)
		if string(jsonArrayOfService) == "{}" { // empty struct
			dst.ArrayOfService = nil
		} else {
			if err = validator.Validate(dst.ArrayOfService); err != nil {
				dst.ArrayOfService = nil
			} else {
				match++
			}
		}
	} else {
		dst.ArrayOfService = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ExportServicesJSON200ResponseOneOf = nil
		dst.ArrayOfService = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ExportServicesJSON200Response)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(ExportServicesJSON200Response)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ExportServicesJSON200Response) MarshalJSON() ([]byte, error) {
	if src.ExportServicesJSON200ResponseOneOf != nil {
		return json.Marshal(&src.ExportServicesJSON200ResponseOneOf)
	}

	if src.ArrayOfService != nil {
		return json.Marshal(&src.ArrayOfService)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ExportServicesJSON200Response) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.ExportServicesJSON200ResponseOneOf != nil {
		return obj.ExportServicesJSON200ResponseOneOf
	}

	if obj.ArrayOfService != nil {
		return obj.ArrayOfService
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj ExportServicesJSON200Response) GetActualInstanceValue() interface{} {
	if obj.ExportServicesJSON200ResponseOneOf != nil {
		return *obj.ExportServicesJSON200ResponseOneOf
	}

	if obj.ArrayOfService != nil {
		return *obj.ArrayOfService
	}

	// all schemas are nil
	return nil
}

type NullableExportServicesJSON200Response struct {
	value *ExportServicesJSON200Response
	isSet bool
}

func (v NullableExportServicesJSON200Response) Get() *ExportServicesJSON200Response {
	return v.value
}

func (v *NullableExportServicesJSON200Response) Set(val *ExportServicesJSON200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableExportServicesJSON200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableExportServicesJSON200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExportServicesJSON200Response(val *ExportServicesJSON200Response) *NullableExportServicesJSON200Response {
	return &NullableExportServicesJSON200Response{value: val, isSet: true}
}

func (v NullableExportServicesJSON200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExportServicesJSON200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
