/*
runZero API

runZero API. API use is rate limited, you can make as many calls per day as you have licensed assets.

API version: 4.0.250826.0
Contact: support@runzero.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GCPCredentialFields type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GCPCredentialFields{}

// GCPCredentialFields struct for GCPCredentialFields
type GCPCredentialFields struct {
	CrossProject *string `json:"cross_project,omitempty"`
	AuthProviderX509CertUrl *string `json:"auth_provider_x509_cert_url,omitempty"`
	AuthUri *string `json:"auth_uri,omitempty"`
	ClientEmail *string `json:"client_email,omitempty"`
	ClientId *string `json:"client_id,omitempty"`
	ClientX509CertUrl *string `json:"client_x509_cert_url,omitempty"`
	// base64 encoded private key, beginning with -----BEGIN PRIVATE KEY-----
	PrivateKey *string `json:"private_key,omitempty"`
	PrivateKeyId *string `json:"private_key_id,omitempty"`
	ProjectId *string `json:"project_id,omitempty"`
	TokenUri *string `json:"token_uri,omitempty"`
	Type *string `json:"type,omitempty"`
	UniverseDomain *string `json:"universe_domain,omitempty"`
}

// NewGCPCredentialFields instantiates a new GCPCredentialFields object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGCPCredentialFields() *GCPCredentialFields {
	this := GCPCredentialFields{}
	return &this
}

// NewGCPCredentialFieldsWithDefaults instantiates a new GCPCredentialFields object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGCPCredentialFieldsWithDefaults() *GCPCredentialFields {
	this := GCPCredentialFields{}
	return &this
}

// GetCrossProject returns the CrossProject field value if set, zero value otherwise.
func (o *GCPCredentialFields) GetCrossProject() string {
	if o == nil || IsNil(o.CrossProject) {
		var ret string
		return ret
	}
	return *o.CrossProject
}

// GetCrossProjectOk returns a tuple with the CrossProject field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GCPCredentialFields) GetCrossProjectOk() (*string, bool) {
	if o == nil || IsNil(o.CrossProject) {
		return nil, false
	}
	return o.CrossProject, true
}

// HasCrossProject returns a boolean if a field has been set.
func (o *GCPCredentialFields) HasCrossProject() bool {
	if o != nil && !IsNil(o.CrossProject) {
		return true
	}

	return false
}

// SetCrossProject gets a reference to the given string and assigns it to the CrossProject field.
func (o *GCPCredentialFields) SetCrossProject(v string) {
	o.CrossProject = &v
}

// GetAuthProviderX509CertUrl returns the AuthProviderX509CertUrl field value if set, zero value otherwise.
func (o *GCPCredentialFields) GetAuthProviderX509CertUrl() string {
	if o == nil || IsNil(o.AuthProviderX509CertUrl) {
		var ret string
		return ret
	}
	return *o.AuthProviderX509CertUrl
}

// GetAuthProviderX509CertUrlOk returns a tuple with the AuthProviderX509CertUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GCPCredentialFields) GetAuthProviderX509CertUrlOk() (*string, bool) {
	if o == nil || IsNil(o.AuthProviderX509CertUrl) {
		return nil, false
	}
	return o.AuthProviderX509CertUrl, true
}

// HasAuthProviderX509CertUrl returns a boolean if a field has been set.
func (o *GCPCredentialFields) HasAuthProviderX509CertUrl() bool {
	if o != nil && !IsNil(o.AuthProviderX509CertUrl) {
		return true
	}

	return false
}

// SetAuthProviderX509CertUrl gets a reference to the given string and assigns it to the AuthProviderX509CertUrl field.
func (o *GCPCredentialFields) SetAuthProviderX509CertUrl(v string) {
	o.AuthProviderX509CertUrl = &v
}

// GetAuthUri returns the AuthUri field value if set, zero value otherwise.
func (o *GCPCredentialFields) GetAuthUri() string {
	if o == nil || IsNil(o.AuthUri) {
		var ret string
		return ret
	}
	return *o.AuthUri
}

// GetAuthUriOk returns a tuple with the AuthUri field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GCPCredentialFields) GetAuthUriOk() (*string, bool) {
	if o == nil || IsNil(o.AuthUri) {
		return nil, false
	}
	return o.AuthUri, true
}

// HasAuthUri returns a boolean if a field has been set.
func (o *GCPCredentialFields) HasAuthUri() bool {
	if o != nil && !IsNil(o.AuthUri) {
		return true
	}

	return false
}

// SetAuthUri gets a reference to the given string and assigns it to the AuthUri field.
func (o *GCPCredentialFields) SetAuthUri(v string) {
	o.AuthUri = &v
}

// GetClientEmail returns the ClientEmail field value if set, zero value otherwise.
func (o *GCPCredentialFields) GetClientEmail() string {
	if o == nil || IsNil(o.ClientEmail) {
		var ret string
		return ret
	}
	return *o.ClientEmail
}

// GetClientEmailOk returns a tuple with the ClientEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GCPCredentialFields) GetClientEmailOk() (*string, bool) {
	if o == nil || IsNil(o.ClientEmail) {
		return nil, false
	}
	return o.ClientEmail, true
}

// HasClientEmail returns a boolean if a field has been set.
func (o *GCPCredentialFields) HasClientEmail() bool {
	if o != nil && !IsNil(o.ClientEmail) {
		return true
	}

	return false
}

// SetClientEmail gets a reference to the given string and assigns it to the ClientEmail field.
func (o *GCPCredentialFields) SetClientEmail(v string) {
	o.ClientEmail = &v
}

// GetClientId returns the ClientId field value if set, zero value otherwise.
func (o *GCPCredentialFields) GetClientId() string {
	if o == nil || IsNil(o.ClientId) {
		var ret string
		return ret
	}
	return *o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GCPCredentialFields) GetClientIdOk() (*string, bool) {
	if o == nil || IsNil(o.ClientId) {
		return nil, false
	}
	return o.ClientId, true
}

// HasClientId returns a boolean if a field has been set.
func (o *GCPCredentialFields) HasClientId() bool {
	if o != nil && !IsNil(o.ClientId) {
		return true
	}

	return false
}

// SetClientId gets a reference to the given string and assigns it to the ClientId field.
func (o *GCPCredentialFields) SetClientId(v string) {
	o.ClientId = &v
}

// GetClientX509CertUrl returns the ClientX509CertUrl field value if set, zero value otherwise.
func (o *GCPCredentialFields) GetClientX509CertUrl() string {
	if o == nil || IsNil(o.ClientX509CertUrl) {
		var ret string
		return ret
	}
	return *o.ClientX509CertUrl
}

// GetClientX509CertUrlOk returns a tuple with the ClientX509CertUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GCPCredentialFields) GetClientX509CertUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ClientX509CertUrl) {
		return nil, false
	}
	return o.ClientX509CertUrl, true
}

// HasClientX509CertUrl returns a boolean if a field has been set.
func (o *GCPCredentialFields) HasClientX509CertUrl() bool {
	if o != nil && !IsNil(o.ClientX509CertUrl) {
		return true
	}

	return false
}

// SetClientX509CertUrl gets a reference to the given string and assigns it to the ClientX509CertUrl field.
func (o *GCPCredentialFields) SetClientX509CertUrl(v string) {
	o.ClientX509CertUrl = &v
}

// GetPrivateKey returns the PrivateKey field value if set, zero value otherwise.
func (o *GCPCredentialFields) GetPrivateKey() string {
	if o == nil || IsNil(o.PrivateKey) {
		var ret string
		return ret
	}
	return *o.PrivateKey
}

// GetPrivateKeyOk returns a tuple with the PrivateKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GCPCredentialFields) GetPrivateKeyOk() (*string, bool) {
	if o == nil || IsNil(o.PrivateKey) {
		return nil, false
	}
	return o.PrivateKey, true
}

// HasPrivateKey returns a boolean if a field has been set.
func (o *GCPCredentialFields) HasPrivateKey() bool {
	if o != nil && !IsNil(o.PrivateKey) {
		return true
	}

	return false
}

// SetPrivateKey gets a reference to the given string and assigns it to the PrivateKey field.
func (o *GCPCredentialFields) SetPrivateKey(v string) {
	o.PrivateKey = &v
}

// GetPrivateKeyId returns the PrivateKeyId field value if set, zero value otherwise.
func (o *GCPCredentialFields) GetPrivateKeyId() string {
	if o == nil || IsNil(o.PrivateKeyId) {
		var ret string
		return ret
	}
	return *o.PrivateKeyId
}

// GetPrivateKeyIdOk returns a tuple with the PrivateKeyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GCPCredentialFields) GetPrivateKeyIdOk() (*string, bool) {
	if o == nil || IsNil(o.PrivateKeyId) {
		return nil, false
	}
	return o.PrivateKeyId, true
}

// HasPrivateKeyId returns a boolean if a field has been set.
func (o *GCPCredentialFields) HasPrivateKeyId() bool {
	if o != nil && !IsNil(o.PrivateKeyId) {
		return true
	}

	return false
}

// SetPrivateKeyId gets a reference to the given string and assigns it to the PrivateKeyId field.
func (o *GCPCredentialFields) SetPrivateKeyId(v string) {
	o.PrivateKeyId = &v
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise.
func (o *GCPCredentialFields) GetProjectId() string {
	if o == nil || IsNil(o.ProjectId) {
		var ret string
		return ret
	}
	return *o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GCPCredentialFields) GetProjectIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProjectId) {
		return nil, false
	}
	return o.ProjectId, true
}

// HasProjectId returns a boolean if a field has been set.
func (o *GCPCredentialFields) HasProjectId() bool {
	if o != nil && !IsNil(o.ProjectId) {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given string and assigns it to the ProjectId field.
func (o *GCPCredentialFields) SetProjectId(v string) {
	o.ProjectId = &v
}

// GetTokenUri returns the TokenUri field value if set, zero value otherwise.
func (o *GCPCredentialFields) GetTokenUri() string {
	if o == nil || IsNil(o.TokenUri) {
		var ret string
		return ret
	}
	return *o.TokenUri
}

// GetTokenUriOk returns a tuple with the TokenUri field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GCPCredentialFields) GetTokenUriOk() (*string, bool) {
	if o == nil || IsNil(o.TokenUri) {
		return nil, false
	}
	return o.TokenUri, true
}

// HasTokenUri returns a boolean if a field has been set.
func (o *GCPCredentialFields) HasTokenUri() bool {
	if o != nil && !IsNil(o.TokenUri) {
		return true
	}

	return false
}

// SetTokenUri gets a reference to the given string and assigns it to the TokenUri field.
func (o *GCPCredentialFields) SetTokenUri(v string) {
	o.TokenUri = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *GCPCredentialFields) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GCPCredentialFields) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *GCPCredentialFields) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *GCPCredentialFields) SetType(v string) {
	o.Type = &v
}

// GetUniverseDomain returns the UniverseDomain field value if set, zero value otherwise.
func (o *GCPCredentialFields) GetUniverseDomain() string {
	if o == nil || IsNil(o.UniverseDomain) {
		var ret string
		return ret
	}
	return *o.UniverseDomain
}

// GetUniverseDomainOk returns a tuple with the UniverseDomain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GCPCredentialFields) GetUniverseDomainOk() (*string, bool) {
	if o == nil || IsNil(o.UniverseDomain) {
		return nil, false
	}
	return o.UniverseDomain, true
}

// HasUniverseDomain returns a boolean if a field has been set.
func (o *GCPCredentialFields) HasUniverseDomain() bool {
	if o != nil && !IsNil(o.UniverseDomain) {
		return true
	}

	return false
}

// SetUniverseDomain gets a reference to the given string and assigns it to the UniverseDomain field.
func (o *GCPCredentialFields) SetUniverseDomain(v string) {
	o.UniverseDomain = &v
}

func (o GCPCredentialFields) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GCPCredentialFields) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CrossProject) {
		toSerialize["cross_project"] = o.CrossProject
	}
	if !IsNil(o.AuthProviderX509CertUrl) {
		toSerialize["auth_provider_x509_cert_url"] = o.AuthProviderX509CertUrl
	}
	if !IsNil(o.AuthUri) {
		toSerialize["auth_uri"] = o.AuthUri
	}
	if !IsNil(o.ClientEmail) {
		toSerialize["client_email"] = o.ClientEmail
	}
	if !IsNil(o.ClientId) {
		toSerialize["client_id"] = o.ClientId
	}
	if !IsNil(o.ClientX509CertUrl) {
		toSerialize["client_x509_cert_url"] = o.ClientX509CertUrl
	}
	if !IsNil(o.PrivateKey) {
		toSerialize["private_key"] = o.PrivateKey
	}
	if !IsNil(o.PrivateKeyId) {
		toSerialize["private_key_id"] = o.PrivateKeyId
	}
	if !IsNil(o.ProjectId) {
		toSerialize["project_id"] = o.ProjectId
	}
	if !IsNil(o.TokenUri) {
		toSerialize["token_uri"] = o.TokenUri
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.UniverseDomain) {
		toSerialize["universe_domain"] = o.UniverseDomain
	}
	return toSerialize, nil
}

type NullableGCPCredentialFields struct {
	value *GCPCredentialFields
	isSet bool
}

func (v NullableGCPCredentialFields) Get() *GCPCredentialFields {
	return v.value
}

func (v *NullableGCPCredentialFields) Set(val *GCPCredentialFields) {
	v.value = val
	v.isSet = true
}

func (v NullableGCPCredentialFields) IsSet() bool {
	return v.isSet
}

func (v *NullableGCPCredentialFields) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGCPCredentialFields(val *GCPCredentialFields) *NullableGCPCredentialFields {
	return &NullableGCPCredentialFields{value: val, isSet: true}
}

func (v NullableGCPCredentialFields) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGCPCredentialFields) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


