/*
runZero API

runZero API. API use is rate limited, you can make as many calls per day as you have licensed assets.

API version: 4.0.250826.0
Contact: support@runzero.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package runzero

import (
	"encoding/json"
)

// checks if the FindingLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FindingLinks{}

// FindingLinks struct for FindingLinks
type FindingLinks struct {
	Cves []FindingLinksCvesInner `json:"cves,omitempty"`
	// URLs of relevant runZero blog postings.
	RzBlog []FindingLinksCvesInner `json:"rz_blog,omitempty"`
	// Additional relevant URLs.
	Urls []FindingLinksCvesInner `json:"urls,omitempty"`
}

// NewFindingLinks instantiates a new FindingLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFindingLinks() *FindingLinks {
	this := FindingLinks{}
	return &this
}

// NewFindingLinksWithDefaults instantiates a new FindingLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFindingLinksWithDefaults() *FindingLinks {
	this := FindingLinks{}
	return &this
}

// GetCves returns the Cves field value if set, zero value otherwise.
func (o *FindingLinks) GetCves() []FindingLinksCvesInner {
	if o == nil || IsNil(o.Cves) {
		var ret []FindingLinksCvesInner
		return ret
	}
	return o.Cves
}

// GetCvesOk returns a tuple with the Cves field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindingLinks) GetCvesOk() ([]FindingLinksCvesInner, bool) {
	if o == nil || IsNil(o.Cves) {
		return nil, false
	}
	return o.Cves, true
}

// HasCves returns a boolean if a field has been set.
func (o *FindingLinks) HasCves() bool {
	if o != nil && !IsNil(o.Cves) {
		return true
	}

	return false
}

// SetCves gets a reference to the given []FindingLinksCvesInner and assigns it to the Cves field.
func (o *FindingLinks) SetCves(v []FindingLinksCvesInner) {
	o.Cves = v
}

// GetRzBlog returns the RzBlog field value if set, zero value otherwise.
func (o *FindingLinks) GetRzBlog() []FindingLinksCvesInner {
	if o == nil || IsNil(o.RzBlog) {
		var ret []FindingLinksCvesInner
		return ret
	}
	return o.RzBlog
}

// GetRzBlogOk returns a tuple with the RzBlog field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindingLinks) GetRzBlogOk() ([]FindingLinksCvesInner, bool) {
	if o == nil || IsNil(o.RzBlog) {
		return nil, false
	}
	return o.RzBlog, true
}

// HasRzBlog returns a boolean if a field has been set.
func (o *FindingLinks) HasRzBlog() bool {
	if o != nil && !IsNil(o.RzBlog) {
		return true
	}

	return false
}

// SetRzBlog gets a reference to the given []FindingLinksCvesInner and assigns it to the RzBlog field.
func (o *FindingLinks) SetRzBlog(v []FindingLinksCvesInner) {
	o.RzBlog = v
}

// GetUrls returns the Urls field value if set, zero value otherwise.
func (o *FindingLinks) GetUrls() []FindingLinksCvesInner {
	if o == nil || IsNil(o.Urls) {
		var ret []FindingLinksCvesInner
		return ret
	}
	return o.Urls
}

// GetUrlsOk returns a tuple with the Urls field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindingLinks) GetUrlsOk() ([]FindingLinksCvesInner, bool) {
	if o == nil || IsNil(o.Urls) {
		return nil, false
	}
	return o.Urls, true
}

// HasUrls returns a boolean if a field has been set.
func (o *FindingLinks) HasUrls() bool {
	if o != nil && !IsNil(o.Urls) {
		return true
	}

	return false
}

// SetUrls gets a reference to the given []FindingLinksCvesInner and assigns it to the Urls field.
func (o *FindingLinks) SetUrls(v []FindingLinksCvesInner) {
	o.Urls = v
}

func (o FindingLinks) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FindingLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Cves) {
		toSerialize["cves"] = o.Cves
	}
	if !IsNil(o.RzBlog) {
		toSerialize["rz_blog"] = o.RzBlog
	}
	if !IsNil(o.Urls) {
		toSerialize["urls"] = o.Urls
	}
	return toSerialize, nil
}

type NullableFindingLinks struct {
	value *FindingLinks
	isSet bool
}

func (v NullableFindingLinks) Get() *FindingLinks {
	return v.value
}

func (v *NullableFindingLinks) Set(val *FindingLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableFindingLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableFindingLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFindingLinks(val *FindingLinks) *NullableFindingLinks {
	return &NullableFindingLinks{value: val, isSet: true}
}

func (v NullableFindingLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFindingLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
