/*
runZero API

runZero API. API use is rate limited, you can make as many calls per day as you have licensed assets.

API version: 4.0.250826.0
Contact: support@runzero.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SoftwarePage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SoftwarePage{}

// SoftwarePage A page of software inventory entries returned from a paginated export.
type SoftwarePage struct {
	Software []Software `json:"software,omitempty"`
	// The key to use for the next page of results
	NextKey *string `json:"next_key,omitempty"`
}

// NewSoftwarePage instantiates a new SoftwarePage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSoftwarePage() *SoftwarePage {
	this := SoftwarePage{}
	return &this
}

// NewSoftwarePageWithDefaults instantiates a new SoftwarePage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSoftwarePageWithDefaults() *SoftwarePage {
	this := SoftwarePage{}
	return &this
}

// GetSoftware returns the Software field value if set, zero value otherwise.
func (o *SoftwarePage) GetSoftware() []Software {
	if o == nil || IsNil(o.Software) {
		var ret []Software
		return ret
	}
	return o.Software
}

// GetSoftwareOk returns a tuple with the Software field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SoftwarePage) GetSoftwareOk() ([]Software, bool) {
	if o == nil || IsNil(o.Software) {
		return nil, false
	}
	return o.Software, true
}

// HasSoftware returns a boolean if a field has been set.
func (o *SoftwarePage) HasSoftware() bool {
	if o != nil && !IsNil(o.Software) {
		return true
	}

	return false
}

// SetSoftware gets a reference to the given []Software and assigns it to the Software field.
func (o *SoftwarePage) SetSoftware(v []Software) {
	o.Software = v
}

// GetNextKey returns the NextKey field value if set, zero value otherwise.
func (o *SoftwarePage) GetNextKey() string {
	if o == nil || IsNil(o.NextKey) {
		var ret string
		return ret
	}
	return *o.NextKey
}

// GetNextKeyOk returns a tuple with the NextKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SoftwarePage) GetNextKeyOk() (*string, bool) {
	if o == nil || IsNil(o.NextKey) {
		return nil, false
	}
	return o.NextKey, true
}

// HasNextKey returns a boolean if a field has been set.
func (o *SoftwarePage) HasNextKey() bool {
	if o != nil && !IsNil(o.NextKey) {
		return true
	}

	return false
}

// SetNextKey gets a reference to the given string and assigns it to the NextKey field.
func (o *SoftwarePage) SetNextKey(v string) {
	o.NextKey = &v
}

func (o SoftwarePage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SoftwarePage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Software) {
		toSerialize["software"] = o.Software
	}
	if !IsNil(o.NextKey) {
		toSerialize["next_key"] = o.NextKey
	}
	return toSerialize, nil
}

type NullableSoftwarePage struct {
	value *SoftwarePage
	isSet bool
}

func (v NullableSoftwarePage) Get() *SoftwarePage {
	return v.value
}

func (v *NullableSoftwarePage) Set(val *SoftwarePage) {
	v.value = val
	v.isSet = true
}

func (v NullableSoftwarePage) IsSet() bool {
	return v.isSet
}

func (v *NullableSoftwarePage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSoftwarePage(val *SoftwarePage) *NullableSoftwarePage {
	return &NullableSoftwarePage{value: val, isSet: true}
}

func (v NullableSoftwarePage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSoftwarePage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


