/*
runZero API

runZero API. API use is rate limited, you can make as many calls per day as you have licensed assets.

API version: 4.0.250826.0
Contact: support@runzero.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// ServiceExportResponse - Response body for the service export endpoint. Bare array unless `page_size` is provided.
type ServiceExportResponse struct {
	ServicePage *ServicePage
	ArrayOfService *[]Service
}

// ServicePageAsServiceExportResponse is a convenience function that returns ServicePage wrapped in ServiceExportResponse
func ServicePageAsServiceExportResponse(v *ServicePage) ServiceExportResponse {
	return ServiceExportResponse{
		ServicePage: v,
	}
}

// []ServiceAsServiceExportResponse is a convenience function that returns []Service wrapped in ServiceExportResponse
func ArrayOfServiceAsServiceExportResponse(v *[]Service) ServiceExportResponse {
	return ServiceExportResponse{
		ArrayOfService: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *ServiceExportResponse) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ServicePage
	err = newStrictDecoder(data).Decode(&dst.ServicePage)
	if err == nil {
		jsonServicePage, _ := json.Marshal(dst.ServicePage)
		if string(jsonServicePage) == "{}" { // empty struct
			dst.ServicePage = nil
		} else {
			if err = validator.Validate(dst.ServicePage); err != nil {
				dst.ServicePage = nil
			} else {
				match++
			}
		}
	} else {
		dst.ServicePage = nil
	}

	// try to unmarshal data into ArrayOfService
	err = newStrictDecoder(data).Decode(&dst.ArrayOfService)
	if err == nil {
		jsonArrayOfService, _ := json.Marshal(dst.ArrayOfService)
		if string(jsonArrayOfService) == "{}" { // empty struct
			dst.ArrayOfService = nil
		} else {
			if err = validator.Validate(dst.ArrayOfService); err != nil {
				dst.ArrayOfService = nil
			} else {
				match++
			}
		}
	} else {
		dst.ArrayOfService = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ServicePage = nil
		dst.ArrayOfService = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ServiceExportResponse)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(ServiceExportResponse)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ServiceExportResponse) MarshalJSON() ([]byte, error) {
	if src.ServicePage != nil {
		return json.Marshal(&src.ServicePage)
	}

	if src.ArrayOfService != nil {
		return json.Marshal(&src.ArrayOfService)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ServiceExportResponse) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.ServicePage != nil {
		return obj.ServicePage
	}

	if obj.ArrayOfService != nil {
		return obj.ArrayOfService
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj ServiceExportResponse) GetActualInstanceValue() (interface{}) {
	if obj.ServicePage != nil {
		return *obj.ServicePage
	}

	if obj.ArrayOfService != nil {
		return *obj.ArrayOfService
	}

	// all schemas are nil
	return nil
}

type NullableServiceExportResponse struct {
	value *ServiceExportResponse
	isSet bool
}

func (v NullableServiceExportResponse) Get() *ServiceExportResponse {
	return v.value
}

func (v *NullableServiceExportResponse) Set(val *ServiceExportResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceExportResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceExportResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceExportResponse(val *ServiceExportResponse) *NullableServiceExportResponse {
	return &NullableServiceExportResponse{value: val, isSet: true}
}

func (v NullableServiceExportResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceExportResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


