/*
runZero API

runZero API. API use is rate limited, you can make as many calls per day as you have licensed assets.

API version: 4.0.250826.0
Contact: support@runzero.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the BaseResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BaseResponse{}

// BaseResponse Minimal identifying information with lifecycle metadata
type BaseResponse struct {
	// The unique ID of the object
	Id string `json:"id"`
	// The unique ID of the runZero client/customer account that owns the object
	ClientId string `json:"client_id"`
	// The unique ID of the entity that created the object
	CreatedById string `json:"created_by_id"`
	// A timestamp indicating creation time of the object
	CreatedAt time.Time `json:"created_at"`
	// A timestamp indicating last modified time of the object
	UpdatedAt time.Time `json:"updated_at"`
	// A timestamp indicating deletion time of the object
	DestroyedAt *time.Time `json:"destroyed_at,omitempty"`
}

type _BaseResponse BaseResponse

// NewBaseResponse instantiates a new BaseResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBaseResponse(id string, clientId string, createdById string, createdAt time.Time, updatedAt time.Time) *BaseResponse {
	this := BaseResponse{}
	this.Id = id
	this.ClientId = clientId
	this.CreatedById = createdById
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewBaseResponseWithDefaults instantiates a new BaseResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBaseResponseWithDefaults() *BaseResponse {
	this := BaseResponse{}
	return &this
}

// GetId returns the Id field value
func (o *BaseResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *BaseResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *BaseResponse) SetId(v string) {
	o.Id = v
}

// GetClientId returns the ClientId field value
func (o *BaseResponse) GetClientId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value
// and a boolean to check if the value has been set.
func (o *BaseResponse) GetClientIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientId, true
}

// SetClientId sets field value
func (o *BaseResponse) SetClientId(v string) {
	o.ClientId = v
}

// GetCreatedById returns the CreatedById field value
func (o *BaseResponse) GetCreatedById() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedById
}

// GetCreatedByIdOk returns a tuple with the CreatedById field value
// and a boolean to check if the value has been set.
func (o *BaseResponse) GetCreatedByIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedById, true
}

// SetCreatedById sets field value
func (o *BaseResponse) SetCreatedById(v string) {
	o.CreatedById = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *BaseResponse) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *BaseResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *BaseResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *BaseResponse) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *BaseResponse) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *BaseResponse) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetDestroyedAt returns the DestroyedAt field value if set, zero value otherwise.
func (o *BaseResponse) GetDestroyedAt() time.Time {
	if o == nil || IsNil(o.DestroyedAt) {
		var ret time.Time
		return ret
	}
	return *o.DestroyedAt
}

// GetDestroyedAtOk returns a tuple with the DestroyedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseResponse) GetDestroyedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DestroyedAt) {
		return nil, false
	}
	return o.DestroyedAt, true
}

// HasDestroyedAt returns a boolean if a field has been set.
func (o *BaseResponse) HasDestroyedAt() bool {
	if o != nil && !IsNil(o.DestroyedAt) {
		return true
	}

	return false
}

// SetDestroyedAt gets a reference to the given time.Time and assigns it to the DestroyedAt field.
func (o *BaseResponse) SetDestroyedAt(v time.Time) {
	o.DestroyedAt = &v
}

func (o BaseResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BaseResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["client_id"] = o.ClientId
	toSerialize["created_by_id"] = o.CreatedById
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	if !IsNil(o.DestroyedAt) {
		toSerialize["destroyed_at"] = o.DestroyedAt
	}
	return toSerialize, nil
}

func (o *BaseResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"client_id",
		"created_by_id",
		"created_at",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBaseResponse := _BaseResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBaseResponse)

	if err != nil {
		return err
	}

	*o = BaseResponse(varBaseResponse)

	return err
}

type NullableBaseResponse struct {
	value *BaseResponse
	isSet bool
}

func (v NullableBaseResponse) Get() *BaseResponse {
	return v.value
}

func (v *NullableBaseResponse) Set(val *BaseResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBaseResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBaseResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBaseResponse(val *BaseResponse) *NullableBaseResponse {
	return &NullableBaseResponse{value: val, isSet: true}
}

func (v NullableBaseResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBaseResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


