/*
runZero API

runZero API. API use is rate limited, you can make as many calls per day as you have licensed assets.

API version: 4.0.250826.0
Contact: support@runzero.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TenableScCredentialFields type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TenableScCredentialFields{}

// TenableScCredentialFields struct for TenableScCredentialFields
type TenableScCredentialFields struct {
	ApiUrl string `json:"api_url"`
	AccessKey string `json:"access_key"`
	SecretKey string `json:"secret_key"`
	Insecure *string `json:"insecure,omitempty"`
	Thumbprints *string `json:"thumbprints,omitempty"`
}

type _TenableScCredentialFields TenableScCredentialFields

// NewTenableScCredentialFields instantiates a new TenableScCredentialFields object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTenableScCredentialFields(apiUrl string, accessKey string, secretKey string) *TenableScCredentialFields {
	this := TenableScCredentialFields{}
	this.ApiUrl = apiUrl
	this.AccessKey = accessKey
	this.SecretKey = secretKey
	return &this
}

// NewTenableScCredentialFieldsWithDefaults instantiates a new TenableScCredentialFields object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTenableScCredentialFieldsWithDefaults() *TenableScCredentialFields {
	this := TenableScCredentialFields{}
	return &this
}

// GetApiUrl returns the ApiUrl field value
func (o *TenableScCredentialFields) GetApiUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApiUrl
}

// GetApiUrlOk returns a tuple with the ApiUrl field value
// and a boolean to check if the value has been set.
func (o *TenableScCredentialFields) GetApiUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApiUrl, true
}

// SetApiUrl sets field value
func (o *TenableScCredentialFields) SetApiUrl(v string) {
	o.ApiUrl = v
}

// GetAccessKey returns the AccessKey field value
func (o *TenableScCredentialFields) GetAccessKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccessKey
}

// GetAccessKeyOk returns a tuple with the AccessKey field value
// and a boolean to check if the value has been set.
func (o *TenableScCredentialFields) GetAccessKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessKey, true
}

// SetAccessKey sets field value
func (o *TenableScCredentialFields) SetAccessKey(v string) {
	o.AccessKey = v
}

// GetSecretKey returns the SecretKey field value
func (o *TenableScCredentialFields) GetSecretKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SecretKey
}

// GetSecretKeyOk returns a tuple with the SecretKey field value
// and a boolean to check if the value has been set.
func (o *TenableScCredentialFields) GetSecretKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SecretKey, true
}

// SetSecretKey sets field value
func (o *TenableScCredentialFields) SetSecretKey(v string) {
	o.SecretKey = v
}

// GetInsecure returns the Insecure field value if set, zero value otherwise.
func (o *TenableScCredentialFields) GetInsecure() string {
	if o == nil || IsNil(o.Insecure) {
		var ret string
		return ret
	}
	return *o.Insecure
}

// GetInsecureOk returns a tuple with the Insecure field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenableScCredentialFields) GetInsecureOk() (*string, bool) {
	if o == nil || IsNil(o.Insecure) {
		return nil, false
	}
	return o.Insecure, true
}

// HasInsecure returns a boolean if a field has been set.
func (o *TenableScCredentialFields) HasInsecure() bool {
	if o != nil && !IsNil(o.Insecure) {
		return true
	}

	return false
}

// SetInsecure gets a reference to the given string and assigns it to the Insecure field.
func (o *TenableScCredentialFields) SetInsecure(v string) {
	o.Insecure = &v
}

// GetThumbprints returns the Thumbprints field value if set, zero value otherwise.
func (o *TenableScCredentialFields) GetThumbprints() string {
	if o == nil || IsNil(o.Thumbprints) {
		var ret string
		return ret
	}
	return *o.Thumbprints
}

// GetThumbprintsOk returns a tuple with the Thumbprints field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenableScCredentialFields) GetThumbprintsOk() (*string, bool) {
	if o == nil || IsNil(o.Thumbprints) {
		return nil, false
	}
	return o.Thumbprints, true
}

// HasThumbprints returns a boolean if a field has been set.
func (o *TenableScCredentialFields) HasThumbprints() bool {
	if o != nil && !IsNil(o.Thumbprints) {
		return true
	}

	return false
}

// SetThumbprints gets a reference to the given string and assigns it to the Thumbprints field.
func (o *TenableScCredentialFields) SetThumbprints(v string) {
	o.Thumbprints = &v
}

func (o TenableScCredentialFields) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TenableScCredentialFields) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["api_url"] = o.ApiUrl
	toSerialize["access_key"] = o.AccessKey
	toSerialize["secret_key"] = o.SecretKey
	if !IsNil(o.Insecure) {
		toSerialize["insecure"] = o.Insecure
	}
	if !IsNil(o.Thumbprints) {
		toSerialize["thumbprints"] = o.Thumbprints
	}
	return toSerialize, nil
}

func (o *TenableScCredentialFields) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"api_url",
		"access_key",
		"secret_key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTenableScCredentialFields := _TenableScCredentialFields{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTenableScCredentialFields)

	if err != nil {
		return err
	}

	*o = TenableScCredentialFields(varTenableScCredentialFields)

	return err
}

type NullableTenableScCredentialFields struct {
	value *TenableScCredentialFields
	isSet bool
}

func (v NullableTenableScCredentialFields) Get() *TenableScCredentialFields {
	return v.value
}

func (v *NullableTenableScCredentialFields) Set(val *TenableScCredentialFields) {
	v.value = val
	v.isSet = true
}

func (v NullableTenableScCredentialFields) IsSet() bool {
	return v.isSet
}

func (v *NullableTenableScCredentialFields) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTenableScCredentialFields(val *TenableScCredentialFields) *NullableTenableScCredentialFields {
	return &NullableTenableScCredentialFields{value: val, isSet: true}
}

func (v NullableTenableScCredentialFields) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTenableScCredentialFields) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


